let a = [];
let b = [];
let c = [];
// begin of element type [elements]
// begin of element [button]
import ElementButtonButton1 from './elements/button/ElementButtonButton1';
c.push(ElementButtonButton1);
import ElementButtonButton2 from './elements/button/ElementButtonButton2';
c.push(ElementButtonButton2);
import ElementButtonEmphasis1 from './elements/button/ElementButtonEmphasis1';
c.push(ElementButtonEmphasis1);
import ElementButtonEmphasis2 from './elements/button/ElementButtonEmphasis2';
c.push(ElementButtonEmphasis2);
import ElementButtonAnimated1 from './elements/button/ElementButtonAnimated1';
c.push(ElementButtonAnimated1);
import ElementButtonLabeled1 from './elements/button/ElementButtonLabeled1';
c.push(ElementButtonLabeled1);
import ElementButtonLabeled2 from './elements/button/ElementButtonLabeled2';
c.push(ElementButtonLabeled2);
import ElementButtonIcon1 from './elements/button/ElementButtonIcon1';
c.push(ElementButtonIcon1);
import ElementButtonLabeledIcon1 from './elements/button/ElementButtonLabeledIcon1';
c.push(ElementButtonLabeledIcon1);
import ElementButtonBasic1 from './elements/button/ElementButtonBasic1';
c.push(ElementButtonBasic1);
import ElementButtonBasic2 from './elements/button/ElementButtonBasic2';
c.push(ElementButtonBasic2);
import ElementButtonBasic3 from './elements/button/ElementButtonBasic3';
c.push(ElementButtonBasic3);
import ElementButtonTertiary1 from './elements/button/ElementButtonTertiary1';
c.push(ElementButtonTertiary1);
import ElementButtonTertiary2 from './elements/button/ElementButtonTertiary2';
c.push(ElementButtonTertiary2);
import ElementButtonInverted1 from './elements/button/ElementButtonInverted1';
c.push(ElementButtonInverted1);
import ElementButtonInverted2 from './elements/button/ElementButtonInverted2';
c.push(ElementButtonInverted2);
import ElementButtonButtons1 from './elements/button/ElementButtonButtons1';
c.push(ElementButtonButtons1);
import ElementButtonIconButtons1 from './elements/button/ElementButtonIconButtons1';
c.push(ElementButtonIconButtons1);
import ElementButtonConditionals1 from './elements/button/ElementButtonConditionals1';
c.push(ElementButtonConditionals1);
import ElementButtonConditionals2 from './elements/button/ElementButtonConditionals2';
c.push(ElementButtonConditionals2);
import ElementButtonActive1 from './elements/button/ElementButtonActive1';
c.push(ElementButtonActive1);
import ElementButtonDisabled1 from './elements/button/ElementButtonDisabled1';
c.push(ElementButtonDisabled1);
import ElementButtonLoading1 from './elements/button/ElementButtonLoading1';
c.push(ElementButtonLoading1);
import ElementButtonSocial1 from './elements/button/ElementButtonSocial1';
c.push(ElementButtonSocial1);
import ElementButtonSize1 from './elements/button/ElementButtonSize1';
c.push(ElementButtonSize1);
import ElementButtonFloated1 from './elements/button/ElementButtonFloated1';
c.push(ElementButtonFloated1);
import ElementButtonColored1 from './elements/button/ElementButtonColored1';
c.push(ElementButtonColored1);
import ElementButtonCompact1 from './elements/button/ElementButtonCompact1';
c.push(ElementButtonCompact1);
import ElementButtonToggle1 from './elements/button/ElementButtonToggle1';
c.push(ElementButtonToggle1);
import ElementButtonPositive1 from './elements/button/ElementButtonPositive1';
c.push(ElementButtonPositive1);
import ElementButtonNegative1 from './elements/button/ElementButtonNegative1';
c.push(ElementButtonNegative1);
import ElementButtonFluid1 from './elements/button/ElementButtonFluid1';
c.push(ElementButtonFluid1);
import ElementButtonCircular1 from './elements/button/ElementButtonCircular1';
c.push(ElementButtonCircular1);
import ElementButtonCircular2 from './elements/button/ElementButtonCircular2';
c.push(ElementButtonCircular2);
import ElementButtonVerticallyAttached1 from './elements/button/ElementButtonVerticallyAttached1';
c.push(ElementButtonVerticallyAttached1);
import ElementButtonVerticallyAttached2 from './elements/button/ElementButtonVerticallyAttached2';
c.push(ElementButtonVerticallyAttached2);
import ElementButtonHorizontallyAttached1 from './elements/button/ElementButtonHorizontallyAttached1';
c.push(ElementButtonHorizontallyAttached1);
import ElementButtonVerticalButtons1 from './elements/button/ElementButtonVerticalButtons1';
c.push(ElementButtonVerticalButtons1);
import ElementButtonIconButtons1A from './elements/button/ElementButtonIconButtons1A';
c.push(ElementButtonIconButtons1A);
import ElementButtonLabeledIconButtons1 from './elements/button/ElementButtonLabeledIconButtons1';
c.push(ElementButtonLabeledIconButtons1);
import ElementButtonMixedGroup1 from './elements/button/ElementButtonMixedGroup1';
c.push(ElementButtonMixedGroup1);
import ElementButtonEqualWidth1 from './elements/button/ElementButtonEqualWidth1';
c.push(ElementButtonEqualWidth1);
import ElementButtonColoredButtons1 from './elements/button/ElementButtonColoredButtons1';
c.push(ElementButtonColoredButtons1);
import ElementButtonBasicButtons1 from './elements/button/ElementButtonBasicButtons1';
c.push(ElementButtonBasicButtons1);
import ElementButtonBasicButtons2 from './elements/button/ElementButtonBasicButtons2';
c.push(ElementButtonBasicButtons2);
import ElementButtonGroupSizes1 from './elements/button/ElementButtonGroupSizes1';
c.push(ElementButtonGroupSizes1);
import ElementButtonGroupSizes2 from './elements/button/ElementButtonGroupSizes2';
c.push(ElementButtonGroupSizes2);
import ElementButtonGroupSizes3 from './elements/button/ElementButtonGroupSizes3';
c.push(ElementButtonGroupSizes3);
b.push(['button', c]); c = [];
// end of element [button]
// begin of element [divider]
import ElementDividerDivider1 from './elements/divider/ElementDividerDivider1';
c.push(ElementDividerDivider1);
import ElementDividerVerticalDivider1 from './elements/divider/ElementDividerVerticalDivider1';
c.push(ElementDividerVerticalDivider1);
import ElementDividerVerticalDivider2 from './elements/divider/ElementDividerVerticalDivider2';
c.push(ElementDividerVerticalDivider2);
import ElementDividerHorizontalDivider1 from './elements/divider/ElementDividerHorizontalDivider1';
c.push(ElementDividerHorizontalDivider1);
import ElementDividerHorizontalDivider2 from './elements/divider/ElementDividerHorizontalDivider2';
c.push(ElementDividerHorizontalDivider2);
import ElementDividerHorizontalAlignment1 from './elements/divider/ElementDividerHorizontalAlignment1';
c.push(ElementDividerHorizontalAlignment1);
import ElementDividerInverted1 from './elements/divider/ElementDividerInverted1';
c.push(ElementDividerInverted1);
import ElementDividerFitted1 from './elements/divider/ElementDividerFitted1';
c.push(ElementDividerFitted1);
import ElementDividerHidden1 from './elements/divider/ElementDividerHidden1';
c.push(ElementDividerHidden1);
import ElementDividerSection1 from './elements/divider/ElementDividerSection1';
c.push(ElementDividerSection1);
import ElementDividerClearing1 from './elements/divider/ElementDividerClearing1';
c.push(ElementDividerClearing1);
b.push(['divider', c]); c = [];
// end of element [divider]
// begin of element [flag]
import ElementFlag1 from './elements/flag/ElementFlag1';
c.push(ElementFlag1);
b.push(['flag', c]); c = [];
// end of element [flag]
// begin of element [header]
import ElementHeaderPageHeaders1 from './elements/header/ElementHeaderPageHeaders1';
c.push(ElementHeaderPageHeaders1);
import ElementHeaderContentHeaders1 from './elements/header/ElementHeaderContentHeaders1';
c.push(ElementHeaderContentHeaders1);
import ElementHeaderIconHeaders1 from './elements/header/ElementHeaderIconHeaders1';
c.push(ElementHeaderIconHeaders1);
import ElementHeaderIconHeaders2 from './elements/header/ElementHeaderIconHeaders2';
c.push(ElementHeaderIconHeaders2);
import ElementHeaderSubHeaders1 from './elements/header/ElementHeaderSubHeaders1';
c.push(ElementHeaderSubHeaders1);
import ElementHeaderSubHeaders2 from './elements/header/ElementHeaderSubHeaders2';
c.push(ElementHeaderSubHeaders2);
import ElementHeaderImage1 from './elements/header/ElementHeaderImage1';
c.push(ElementHeaderImage1);
import ElementHeaderImage2 from './elements/header/ElementHeaderImage2';
c.push(ElementHeaderImage2);
import ElementHeaderImage3 from './elements/header/ElementHeaderImage3';
c.push(ElementHeaderImage3);
import ElementHeaderIcon1 from './elements/header/ElementHeaderIcon1';
c.push(ElementHeaderIcon1);
import ElementHeaderIcon2 from './elements/header/ElementHeaderIcon2';
c.push(ElementHeaderIcon2);
import ElementHeaderSubheader1 from './elements/header/ElementHeaderSubheader1';
c.push(ElementHeaderSubheader1);
import ElementHeaderSubheader2 from './elements/header/ElementHeaderSubheader2';
c.push(ElementHeaderSubheader2);
import ElementHeaderDisabled1 from './elements/header/ElementHeaderDisabled1';
c.push(ElementHeaderDisabled1);
import ElementHeaderDividing1 from './elements/header/ElementHeaderDividing1';
c.push(ElementHeaderDividing1);
import ElementHeaderBlock1 from './elements/header/ElementHeaderBlock1';
c.push(ElementHeaderBlock1);
import ElementHeaderAttached1 from './elements/header/ElementHeaderAttached1';
c.push(ElementHeaderAttached1);
import ElementHeaderFloating1 from './elements/header/ElementHeaderFloating1';
c.push(ElementHeaderFloating1);
import ElementHeaderTextAlignment1 from './elements/header/ElementHeaderTextAlignment1';
c.push(ElementHeaderTextAlignment1);
import ElementHeaderColored1 from './elements/header/ElementHeaderColored1';
c.push(ElementHeaderColored1);
import ElementHeaderInverted1 from './elements/header/ElementHeaderInverted1';
c.push(ElementHeaderInverted1);
b.push(['header', c]); c = [];
// end of element [header]
// begin of element [icon]
import ElementIcon1 from './elements/icon/ElementIcon1';
c.push(ElementIcon1);
import ElementIcon1A from './elements/icon/ElementIcon1A';
c.push(ElementIcon1A);
b.push(['icon', c]); c = [];
// end of element [icon]
// begin of element [image]
import ElementImageImage1 from './elements/image/ElementImageImage1';
c.push(ElementImageImage1);
import ElementImageImage2 from './elements/image/ElementImageImage2';
c.push(ElementImageImage2);
import ElementImageImage3 from './elements/image/ElementImageImage3';
c.push(ElementImageImage3);
import ElementImageImageLink1 from './elements/image/ElementImageImageLink1';
c.push(ElementImageImageLink1);
import ElementImageHidden1 from './elements/image/ElementImageHidden1';
c.push(ElementImageHidden1);
import ElementImageDisabled1 from './elements/image/ElementImageDisabled1';
c.push(ElementImageDisabled1);
import ElementImageAvatar1 from './elements/image/ElementImageAvatar1';
c.push(ElementImageAvatar1);
import ElementImageBordered1 from './elements/image/ElementImageBordered1';
c.push(ElementImageBordered1);
import ElementImageFluid1 from './elements/image/ElementImageFluid1';
c.push(ElementImageFluid1);
import ElementImageRounded1 from './elements/image/ElementImageRounded1';
c.push(ElementImageRounded1);
import ElementImageCircular1 from './elements/image/ElementImageCircular1';
c.push(ElementImageCircular1);
import ElementImageVerticallyAligned1 from './elements/image/ElementImageVerticallyAligned1';
c.push(ElementImageVerticallyAligned1);
import ElementImageCentered1 from './elements/image/ElementImageCentered1';
c.push(ElementImageCentered1);
import ElementImageSpaced1 from './elements/image/ElementImageSpaced1';
c.push(ElementImageSpaced1);
import ElementImageSpaced2 from './elements/image/ElementImageSpaced2';
c.push(ElementImageSpaced2);
import ElementImageFloated1 from './elements/image/ElementImageFloated1';
c.push(ElementImageFloated1);
import ElementImageSize1 from './elements/image/ElementImageSize1';
c.push(ElementImageSize1);
import ElementImageSize1A from './elements/image/ElementImageSize1A';
c.push(ElementImageSize1A);
import ElementImageSize2 from './elements/image/ElementImageSize2';
c.push(ElementImageSize2);
b.push(['image', c]); c = [];
// end of element [image]
// begin of element [input]
import ElementInputInput1 from './elements/input/ElementInputInput1';
c.push(ElementInputInput1);
import ElementInputFocus1 from './elements/input/ElementInputFocus1';
c.push(ElementInputFocus1);
import ElementInputLoading1 from './elements/input/ElementInputLoading1';
c.push(ElementInputLoading1);
import ElementInputLoading2 from './elements/input/ElementInputLoading2';
c.push(ElementInputLoading2);
import ElementInputLoading3 from './elements/input/ElementInputLoading3';
c.push(ElementInputLoading3);
import ElementInputLoading4 from './elements/input/ElementInputLoading4';
c.push(ElementInputLoading4);
import ElementInputDisabled1 from './elements/input/ElementInputDisabled1';
c.push(ElementInputDisabled1);
import ElementInputDisabled2 from './elements/input/ElementInputDisabled2';
c.push(ElementInputDisabled2);
import ElementInputDisabled3 from './elements/input/ElementInputDisabled3';
c.push(ElementInputDisabled3);
import ElementInputError1 from './elements/input/ElementInputError1';
c.push(ElementInputError1);
import ElementInputIcon1 from './elements/input/ElementInputIcon1';
c.push(ElementInputIcon1);
import ElementInputIcon2 from './elements/input/ElementInputIcon2';
c.push(ElementInputIcon2);
import ElementInputIcon3 from './elements/input/ElementInputIcon3';
c.push(ElementInputIcon3);
import ElementInputIcon4 from './elements/input/ElementInputIcon4';
c.push(ElementInputIcon4);
import ElementInputLabeled1 from './elements/input/ElementInputLabeled1';
c.push(ElementInputLabeled1);
import ElementInputLabeled2 from './elements/input/ElementInputLabeled2';
c.push(ElementInputLabeled2);
import ElementInputLabeled3 from './elements/input/ElementInputLabeled3';
c.push(ElementInputLabeled3);
import ElementInputLabeled4 from './elements/input/ElementInputLabeled4';
c.push(ElementInputLabeled4);
import ElementInputLabeled5 from './elements/input/ElementInputLabeled5';
c.push(ElementInputLabeled5);
import ElementInputLabeled6 from './elements/input/ElementInputLabeled6';
c.push(ElementInputLabeled6);
import ElementInputLabeled7 from './elements/input/ElementInputLabeled7';
c.push(ElementInputLabeled7);
import ElementInputAction1 from './elements/input/ElementInputAction1';
c.push(ElementInputAction1);
import ElementInputAction2 from './elements/input/ElementInputAction2';
c.push(ElementInputAction2);
import ElementInputAction3 from './elements/input/ElementInputAction3';
c.push(ElementInputAction3);
import ElementInputAction4 from './elements/input/ElementInputAction4';
c.push(ElementInputAction4);
import ElementInputAction5 from './elements/input/ElementInputAction5';
c.push(ElementInputAction5);
import ElementInputAction6 from './elements/input/ElementInputAction6';
c.push(ElementInputAction6);
import ElementInputTransparent1 from './elements/input/ElementInputTransparent1';
c.push(ElementInputTransparent1);
import ElementInputTransparent2 from './elements/input/ElementInputTransparent2';
c.push(ElementInputTransparent2);
import ElementInputTransparent3 from './elements/input/ElementInputTransparent3';
c.push(ElementInputTransparent3);
import ElementInputInverted1 from './elements/input/ElementInputInverted1';
c.push(ElementInputInverted1);
import ElementInputFluid1 from './elements/input/ElementInputFluid1';
c.push(ElementInputFluid1);
import ElementInputSize1 from './elements/input/ElementInputSize1';
c.push(ElementInputSize1);
import ElementInputSize2 from './elements/input/ElementInputSize2';
c.push(ElementInputSize2);
import ElementInputSize3 from './elements/input/ElementInputSize3';
c.push(ElementInputSize3);
import ElementInputSize4 from './elements/input/ElementInputSize4';
c.push(ElementInputSize4);
import ElementInputSize5 from './elements/input/ElementInputSize5';
c.push(ElementInputSize5);
import ElementInputSize6 from './elements/input/ElementInputSize6';
c.push(ElementInputSize6);
import ElementInputTextarea1 from './elements/input/ElementInputTextarea1';
c.push(ElementInputTextarea1);
b.push(['input', c]); c = [];
// end of element [input]
// begin of element [label]
import ElementLabelLabel1 from './elements/label/ElementLabelLabel1';
c.push(ElementLabelLabel1);
import ElementLabelImage1 from './elements/label/ElementLabelImage1';
c.push(ElementLabelImage1);
import ElementLabelImage2 from './elements/label/ElementLabelImage2';
c.push(ElementLabelImage2);
import ElementLabelImage3 from './elements/label/ElementLabelImage3';
c.push(ElementLabelImage3);
import ElementLabelPointing1 from './elements/label/ElementLabelPointing1';
c.push(ElementLabelPointing1);
import ElementLabelPointing2 from './elements/label/ElementLabelPointing2';
c.push(ElementLabelPointing2);
import ElementLabelCorner1 from './elements/label/ElementLabelCorner1';
c.push(ElementLabelCorner1);
import ElementLabelTag1 from './elements/label/ElementLabelTag1';
c.push(ElementLabelTag1);
import ElementLabelRibbon1 from './elements/label/ElementLabelRibbon1';
c.push(ElementLabelRibbon1);
import ElementLabelRibbon2 from './elements/label/ElementLabelRibbon2';
c.push(ElementLabelRibbon2);
import ElementLabelRibbon3 from './elements/label/ElementLabelRibbon3';
c.push(ElementLabelRibbon3);
import ElementLabelRibbon4 from './elements/label/ElementLabelRibbon4';
c.push(ElementLabelRibbon4);
import ElementLabelAttached1 from './elements/label/ElementLabelAttached1';
c.push(ElementLabelAttached1);
import ElementLabelHorizontal1 from './elements/label/ElementLabelHorizontal1';
c.push(ElementLabelHorizontal1);
import ElementLabelFloating1 from './elements/label/ElementLabelFloating1';
c.push(ElementLabelFloating1);
import ElementLabelFloatingleft1 from './elements/label/ElementLabelFloatingleft1';
c.push(ElementLabelFloatingleft1);
import ElementLabelFloatingaligned1 from './elements/label/ElementLabelFloatingaligned1';
c.push(ElementLabelFloatingaligned1);
import ElementLabelDetail1 from './elements/label/ElementLabelDetail1';
c.push(ElementLabelDetail1);
import ElementLabelIcon1 from './elements/label/ElementLabelIcon1';
c.push(ElementLabelIcon1);
import ElementLabelIcon2 from './elements/label/ElementLabelIcon2';
c.push(ElementLabelIcon2);
import ElementLabelIcon3 from './elements/label/ElementLabelIcon3';
c.push(ElementLabelIcon3);
import ElementLabelIcon4 from './elements/label/ElementLabelIcon4';
c.push(ElementLabelIcon4);
import ElementLabelImage1A from './elements/label/ElementLabelImage1A';
c.push(ElementLabelImage1A);
import ElementLabelLink1 from './elements/label/ElementLabelLink1';
c.push(ElementLabelLink1);
import ElementLabelLink2 from './elements/label/ElementLabelLink2';
c.push(ElementLabelLink2);
import ElementLabelCircular1 from './elements/label/ElementLabelCircular1';
c.push(ElementLabelCircular1);
import ElementLabelCircular2 from './elements/label/ElementLabelCircular2';
c.push(ElementLabelCircular2);
import ElementLabelBasic1 from './elements/label/ElementLabelBasic1';
c.push(ElementLabelBasic1);
import ElementLabelColored1 from './elements/label/ElementLabelColored1';
c.push(ElementLabelColored1);
import ElementLabelBasicTagLabels1 from './elements/label/ElementLabelBasicTagLabels1';
c.push(ElementLabelBasicTagLabels1);
import ElementLabelSize1 from './elements/label/ElementLabelSize1';
c.push(ElementLabelSize1);
import ElementLabelGroupSize1 from './elements/label/ElementLabelGroupSize1';
c.push(ElementLabelGroupSize1);
import ElementLabelColoredGroup1 from './elements/label/ElementLabelColoredGroup1';
c.push(ElementLabelColoredGroup1);
import ElementLabelBasicGroup1 from './elements/label/ElementLabelBasicGroup1';
c.push(ElementLabelBasicGroup1);
import ElementLabelTagGroup1 from './elements/label/ElementLabelTagGroup1';
c.push(ElementLabelTagGroup1);
import ElementLabelCircularGroup1 from './elements/label/ElementLabelCircularGroup1';
c.push(ElementLabelCircularGroup1);
import ElementLabelAllVariantsofLabelcanbeinverted1 from './elements/label/ElementLabelAllVariantsofLabelcanbeinverted1';
c.push(ElementLabelAllVariantsofLabelcanbeinverted1);
b.push(['label', c]); c = [];
// end of element [label]
// begin of element [list]
import ElementListList1 from './elements/list/ElementListList1';
c.push(ElementListList1);
import ElementListList2 from './elements/list/ElementListList2';
c.push(ElementListList2);
import ElementListList3 from './elements/list/ElementListList3';
c.push(ElementListList3);
import ElementListList4 from './elements/list/ElementListList4';
c.push(ElementListList4);
import ElementListBulleted1 from './elements/list/ElementListBulleted1';
c.push(ElementListBulleted1);
import ElementListBulleted2 from './elements/list/ElementListBulleted2';
c.push(ElementListBulleted2);
import ElementListBulleted3 from './elements/list/ElementListBulleted3';
c.push(ElementListBulleted3);
import ElementListOrdered1 from './elements/list/ElementListOrdered1';
c.push(ElementListOrdered1);
import ElementListOrdered2 from './elements/list/ElementListOrdered2';
c.push(ElementListOrdered2);
import ElementListOrdered3 from './elements/list/ElementListOrdered3';
c.push(ElementListOrdered3);
import ElementListOrdered4 from './elements/list/ElementListOrdered4';
c.push(ElementListOrdered4);
import ElementListLink1 from './elements/list/ElementListLink1';
c.push(ElementListLink1);
import ElementListItem1 from './elements/list/ElementListItem1';
c.push(ElementListItem1);
import ElementListIcon1 from './elements/list/ElementListIcon1';
c.push(ElementListIcon1);
import ElementListImage1 from './elements/list/ElementListImage1';
c.push(ElementListImage1);
import ElementListLink1A from './elements/list/ElementListLink1A';
c.push(ElementListLink1A);
import ElementListLink2 from './elements/list/ElementListLink2';
c.push(ElementListLink2);
import ElementListHeader1 from './elements/list/ElementListHeader1';
c.push(ElementListHeader1);
import ElementListDescription1 from './elements/list/ElementListDescription1';
c.push(ElementListDescription1);
import ElementListHorizontal1 from './elements/list/ElementListHorizontal1';
c.push(ElementListHorizontal1);
import ElementListHorizontal2 from './elements/list/ElementListHorizontal2';
c.push(ElementListHorizontal2);
import ElementListHorizontal3 from './elements/list/ElementListHorizontal3';
c.push(ElementListHorizontal3);
import ElementListInverted1 from './elements/list/ElementListInverted1';
c.push(ElementListInverted1);
import ElementListSelection1 from './elements/list/ElementListSelection1';
c.push(ElementListSelection1);
import ElementListAnimated1 from './elements/list/ElementListAnimated1';
c.push(ElementListAnimated1);
import ElementListRelaxed1 from './elements/list/ElementListRelaxed1';
c.push(ElementListRelaxed1);
import ElementListRelaxed2 from './elements/list/ElementListRelaxed2';
c.push(ElementListRelaxed2);
import ElementListRelaxed3 from './elements/list/ElementListRelaxed3';
c.push(ElementListRelaxed3);
import ElementListRelaxed4 from './elements/list/ElementListRelaxed4';
c.push(ElementListRelaxed4);
import ElementListDivided1 from './elements/list/ElementListDivided1';
c.push(ElementListDivided1);
import ElementListCelled1 from './elements/list/ElementListCelled1';
c.push(ElementListCelled1);
import ElementListCelled2 from './elements/list/ElementListCelled2';
c.push(ElementListCelled2);
import ElementListCelled3 from './elements/list/ElementListCelled3';
c.push(ElementListCelled3);
import ElementListSize1 from './elements/list/ElementListSize1';
c.push(ElementListSize1);
import ElementListSize2 from './elements/list/ElementListSize2';
c.push(ElementListSize2);
import ElementListSize3 from './elements/list/ElementListSize3';
c.push(ElementListSize3);
import ElementListSize4 from './elements/list/ElementListSize4';
c.push(ElementListSize4);
import ElementListSize5 from './elements/list/ElementListSize5';
c.push(ElementListSize5);
import ElementListSize6 from './elements/list/ElementListSize6';
c.push(ElementListSize6);
import ElementListSize7 from './elements/list/ElementListSize7';
c.push(ElementListSize7);
import ElementListVerticallyAligned1 from './elements/list/ElementListVerticallyAligned1';
c.push(ElementListVerticallyAligned1);
import ElementListFloated1 from './elements/list/ElementListFloated1';
c.push(ElementListFloated1);
import ElementListFloated2 from './elements/list/ElementListFloated2';
c.push(ElementListFloated2);
b.push(['list', c]); c = [];
// end of element [list]
// begin of element [loader]
import ElementLoaderLoader1 from './elements/loader/ElementLoaderLoader1';
c.push(ElementLoaderLoader1);
import ElementLoaderTextLoader1 from './elements/loader/ElementLoaderTextLoader1';
c.push(ElementLoaderTextLoader1);
import ElementLoaderTextLoader2 from './elements/loader/ElementLoaderTextLoader2';
c.push(ElementLoaderTextLoader2);
import ElementLoaderIndeterminate1 from './elements/loader/ElementLoaderIndeterminate1';
c.push(ElementLoaderIndeterminate1);
import ElementLoaderActive1 from './elements/loader/ElementLoaderActive1';
c.push(ElementLoaderActive1);
import ElementLoaderDisabled1 from './elements/loader/ElementLoaderDisabled1';
c.push(ElementLoaderDisabled1);
import ElementLoaderInline1 from './elements/loader/ElementLoaderInline1';
c.push(ElementLoaderInline1);
import ElementLoaderInlineCenter1 from './elements/loader/ElementLoaderInlineCenter1';
c.push(ElementLoaderInlineCenter1);
import ElementLoaderSpeed1 from './elements/loader/ElementLoaderSpeed1';
c.push(ElementLoaderSpeed1);
import ElementLoaderColors1 from './elements/loader/ElementLoaderColors1';
c.push(ElementLoaderColors1);
import ElementLoaderSize1 from './elements/loader/ElementLoaderSize1';
c.push(ElementLoaderSize1);
import ElementLoaderInverted1 from './elements/loader/ElementLoaderInverted1';
c.push(ElementLoaderInverted1);
import ElementLoaderInverted2 from './elements/loader/ElementLoaderInverted2';
c.push(ElementLoaderInverted2);
import ElementLoaderStyles1 from './elements/loader/ElementLoaderStyles1';
c.push(ElementLoaderStyles1);
b.push(['loader', c]); c = [];
// end of element [loader]
// begin of element [placeholder]
import ElementPlaceholderPlaceholder1 from './elements/placeholder/ElementPlaceholderPlaceholder1';
c.push(ElementPlaceholderPlaceholder1);
import ElementPlaceholderPlaceholder2 from './elements/placeholder/ElementPlaceholderPlaceholder2';
c.push(ElementPlaceholderPlaceholder2);
import ElementPlaceholderPlaceholder3 from './elements/placeholder/ElementPlaceholderPlaceholder3';
c.push(ElementPlaceholderPlaceholder3);
import ElementPlaceholderLines1 from './elements/placeholder/ElementPlaceholderLines1';
c.push(ElementPlaceholderLines1);
import ElementPlaceholderHeaders1 from './elements/placeholder/ElementPlaceholderHeaders1';
c.push(ElementPlaceholderHeaders1);
import ElementPlaceholderHeaders2 from './elements/placeholder/ElementPlaceholderHeaders2';
c.push(ElementPlaceholderHeaders2);
import ElementPlaceholderParagraph1 from './elements/placeholder/ElementPlaceholderParagraph1';
c.push(ElementPlaceholderParagraph1);
import ElementPlaceholderImage1 from './elements/placeholder/ElementPlaceholderImage1';
c.push(ElementPlaceholderImage1);
import ElementPlaceholderImage2 from './elements/placeholder/ElementPlaceholderImage2';
c.push(ElementPlaceholderImage2);
import ElementPlaceholderImage3 from './elements/placeholder/ElementPlaceholderImage3';
c.push(ElementPlaceholderImage3);
import ElementPlaceholderLineLength1 from './elements/placeholder/ElementPlaceholderLineLength1';
c.push(ElementPlaceholderLineLength1);
import ElementPlaceholderLineLength2 from './elements/placeholder/ElementPlaceholderLineLength2';
c.push(ElementPlaceholderLineLength2);
import ElementPlaceholderFluid1 from './elements/placeholder/ElementPlaceholderFluid1';
c.push(ElementPlaceholderFluid1);
import ElementPlaceholderInverted1 from './elements/placeholder/ElementPlaceholderInverted1';
c.push(ElementPlaceholderInverted1);
b.push(['placeholder', c]); c = [];
// end of element [placeholder]
// begin of element [rail]
import ElementRail1 from './elements/rail/ElementRail1';
c.push(ElementRail1);
import ElementRailRail1 from './elements/rail/ElementRailRail1';
c.push(ElementRailRail1);
import ElementRailInternal1 from './elements/rail/ElementRailInternal1';
c.push(ElementRailInternal1);
import ElementRailDividing1 from './elements/rail/ElementRailDividing1';
c.push(ElementRailDividing1);
import ElementRailAttached1 from './elements/rail/ElementRailAttached1';
c.push(ElementRailAttached1);
import ElementRailAttached2 from './elements/rail/ElementRailAttached2';
c.push(ElementRailAttached2);
import ElementRailClose1 from './elements/rail/ElementRailClose1';
c.push(ElementRailClose1);
import ElementRailClose2 from './elements/rail/ElementRailClose2';
c.push(ElementRailClose2);
import ElementRailSize1 from './elements/rail/ElementRailSize1';
c.push(ElementRailSize1);
b.push(['rail', c]); c = [];
// end of element [rail]
// begin of element [reveal]
import ElementRevealFade1 from './elements/reveal/ElementRevealFade1';
c.push(ElementRevealFade1);
import ElementRevealFade2 from './elements/reveal/ElementRevealFade2';
c.push(ElementRevealFade2);
import ElementRevealMove1 from './elements/reveal/ElementRevealMove1';
c.push(ElementRevealMove1);
import ElementRevealMove2 from './elements/reveal/ElementRevealMove2';
c.push(ElementRevealMove2);
import ElementRevealMove3 from './elements/reveal/ElementRevealMove3';
c.push(ElementRevealMove3);
import ElementRevealMove4 from './elements/reveal/ElementRevealMove4';
c.push(ElementRevealMove4);
import ElementRevealRotate1 from './elements/reveal/ElementRevealRotate1';
c.push(ElementRevealRotate1);
import ElementRevealRotate2 from './elements/reveal/ElementRevealRotate2';
c.push(ElementRevealRotate2);
import ElementRevealVisibleContent1 from './elements/reveal/ElementRevealVisibleContent1';
c.push(ElementRevealVisibleContent1);
import ElementRevealHiddenContent1 from './elements/reveal/ElementRevealHiddenContent1';
c.push(ElementRevealHiddenContent1);
import ElementRevealActive1 from './elements/reveal/ElementRevealActive1';
c.push(ElementRevealActive1);
import ElementRevealInstant1 from './elements/reveal/ElementRevealInstant1';
c.push(ElementRevealInstant1);
import ElementRevealDisabled1 from './elements/reveal/ElementRevealDisabled1';
c.push(ElementRevealDisabled1);
b.push(['reveal', c]); c = [];
// end of element [reveal]
// begin of element [segment]
import ElementSegmentSegment1 from './elements/segment/ElementSegmentSegment1';
c.push(ElementSegmentSegment1);
import ElementSegmentPlaceholderSegment1 from './elements/segment/ElementSegmentPlaceholderSegment1';
c.push(ElementSegmentPlaceholderSegment1);
import ElementSegmentPlaceholderSegment2 from './elements/segment/ElementSegmentPlaceholderSegment2';
c.push(ElementSegmentPlaceholderSegment2);
import ElementSegmentPlaceholderSegment3 from './elements/segment/ElementSegmentPlaceholderSegment3';
c.push(ElementSegmentPlaceholderSegment3);
import ElementSegmentRaised1 from './elements/segment/ElementSegmentRaised1';
c.push(ElementSegmentRaised1);
import ElementSegmentStacked1 from './elements/segment/ElementSegmentStacked1';
c.push(ElementSegmentStacked1);
import ElementSegmentStacked2 from './elements/segment/ElementSegmentStacked2';
c.push(ElementSegmentStacked2);
import ElementSegmentPiled1 from './elements/segment/ElementSegmentPiled1';
c.push(ElementSegmentPiled1);
import ElementSegmentVerticalSegment1 from './elements/segment/ElementSegmentVerticalSegment1';
c.push(ElementSegmentVerticalSegment1);
import ElementSegmentSegments1 from './elements/segment/ElementSegmentSegments1';
c.push(ElementSegmentSegments1);
import ElementSegmentSegments2 from './elements/segment/ElementSegmentSegments2';
c.push(ElementSegmentSegments2);
import ElementSegmentSegments3 from './elements/segment/ElementSegmentSegments3';
c.push(ElementSegmentSegments3);
import ElementSegmentSegments4 from './elements/segment/ElementSegmentSegments4';
c.push(ElementSegmentSegments4);
import ElementSegmentNestedSegments1 from './elements/segment/ElementSegmentNestedSegments1';
c.push(ElementSegmentNestedSegments1);
import ElementSegmentHorizontalSegments1 from './elements/segment/ElementSegmentHorizontalSegments1';
c.push(ElementSegmentHorizontalSegments1);
import ElementSegmentHorizontalSegments2 from './elements/segment/ElementSegmentHorizontalSegments2';
c.push(ElementSegmentHorizontalSegments2);
import ElementSegmentHorizontalstackableSegments1 from './elements/segment/ElementSegmentHorizontalstackableSegments1';
c.push(ElementSegmentHorizontalstackableSegments1);
import ElementSegmentRaisedSegments1 from './elements/segment/ElementSegmentRaisedSegments1';
c.push(ElementSegmentRaisedSegments1);
import ElementSegmentStackedSegments1 from './elements/segment/ElementSegmentStackedSegments1';
c.push(ElementSegmentStackedSegments1);
import ElementSegmentPiledSegments1 from './elements/segment/ElementSegmentPiledSegments1';
c.push(ElementSegmentPiledSegments1);
import ElementSegmentDisabled1 from './elements/segment/ElementSegmentDisabled1';
c.push(ElementSegmentDisabled1);
import ElementSegmentLoading1 from './elements/segment/ElementSegmentLoading1';
c.push(ElementSegmentLoading1);
import ElementSegmentLoading2 from './elements/segment/ElementSegmentLoading2';
c.push(ElementSegmentLoading2);
import ElementSegmentInverted1 from './elements/segment/ElementSegmentInverted1';
c.push(ElementSegmentInverted1);
import ElementSegmentAttached1 from './elements/segment/ElementSegmentAttached1';
c.push(ElementSegmentAttached1);
import ElementSegmentAttached2 from './elements/segment/ElementSegmentAttached2';
c.push(ElementSegmentAttached2);
import ElementSegmentPadded1 from './elements/segment/ElementSegmentPadded1';
c.push(ElementSegmentPadded1);
import ElementSegmentPadded2 from './elements/segment/ElementSegmentPadded2';
c.push(ElementSegmentPadded2);
import ElementSegmentFitted1 from './elements/segment/ElementSegmentFitted1';
c.push(ElementSegmentFitted1);
import ElementSegmentCompact1 from './elements/segment/ElementSegmentCompact1';
c.push(ElementSegmentCompact1);
import ElementSegmentCompact2 from './elements/segment/ElementSegmentCompact2';
c.push(ElementSegmentCompact2);
import ElementSegmentColored1 from './elements/segment/ElementSegmentColored1';
c.push(ElementSegmentColored1);
import ElementSegmentColored2 from './elements/segment/ElementSegmentColored2';
c.push(ElementSegmentColored2);
import ElementSegmentEmphasis1 from './elements/segment/ElementSegmentEmphasis1';
c.push(ElementSegmentEmphasis1);
import ElementSegmentEmphasis2 from './elements/segment/ElementSegmentEmphasis2';
c.push(ElementSegmentEmphasis2);
import ElementSegmentEmphasis3 from './elements/segment/ElementSegmentEmphasis3';
c.push(ElementSegmentEmphasis3);
import ElementSegmentCircular1 from './elements/segment/ElementSegmentCircular1';
c.push(ElementSegmentCircular1);
import ElementSegmentClearing1 from './elements/segment/ElementSegmentClearing1';
c.push(ElementSegmentClearing1);
import ElementSegmentFloated1 from './elements/segment/ElementSegmentFloated1';
c.push(ElementSegmentFloated1);
import ElementSegmentTextAlignment1 from './elements/segment/ElementSegmentTextAlignment1';
c.push(ElementSegmentTextAlignment1);
import ElementSegmentBasic1 from './elements/segment/ElementSegmentBasic1';
c.push(ElementSegmentBasic1);
b.push(['segment', c]); c = [];
// end of element [segment]
// begin of element [step]
import ElementStepStep1 from './elements/step/ElementStepStep1';
c.push(ElementStepStep1);
import ElementStepSteps1 from './elements/step/ElementStepSteps1';
c.push(ElementStepSteps1);
import ElementStepOrdered1 from './elements/step/ElementStepOrdered1';
c.push(ElementStepOrdered1);
import ElementStepVertical1 from './elements/step/ElementStepVertical1';
c.push(ElementStepVertical1);
import ElementStepDescription1 from './elements/step/ElementStepDescription1';
c.push(ElementStepDescription1);
import ElementStepIcon1 from './elements/step/ElementStepIcon1';
c.push(ElementStepIcon1);
import ElementStepLink1 from './elements/step/ElementStepLink1';
c.push(ElementStepLink1);
import ElementStepLink2 from './elements/step/ElementStepLink2';
c.push(ElementStepLink2);
import ElementStepActive1 from './elements/step/ElementStepActive1';
c.push(ElementStepActive1);
import ElementStepCompleted1 from './elements/step/ElementStepCompleted1';
c.push(ElementStepCompleted1);
import ElementStepCompleted2 from './elements/step/ElementStepCompleted2';
c.push(ElementStepCompleted2);
import ElementStepDisabled1 from './elements/step/ElementStepDisabled1';
c.push(ElementStepDisabled1);
import ElementStepStackable1 from './elements/step/ElementStepStackable1';
c.push(ElementStepStackable1);
import ElementStepFluid1 from './elements/step/ElementStepFluid1';
c.push(ElementStepFluid1);
import ElementStepUnstackable1 from './elements/step/ElementStepUnstackable1';
c.push(ElementStepUnstackable1);
import ElementStepAttached1 from './elements/step/ElementStepAttached1';
c.push(ElementStepAttached1);
import ElementStepEvenlyDivided1 from './elements/step/ElementStepEvenlyDivided1';
c.push(ElementStepEvenlyDivided1);
import ElementStepEvenlyDivided2 from './elements/step/ElementStepEvenlyDivided2';
c.push(ElementStepEvenlyDivided2);
import ElementStepSize1 from './elements/step/ElementStepSize1';
c.push(ElementStepSize1);
import ElementStepSize2 from './elements/step/ElementStepSize2';
c.push(ElementStepSize2);
import ElementStepSize3 from './elements/step/ElementStepSize3';
c.push(ElementStepSize3);
import ElementStepSize4 from './elements/step/ElementStepSize4';
c.push(ElementStepSize4);
import ElementStepSize5 from './elements/step/ElementStepSize5';
c.push(ElementStepSize5);
import ElementStepSize6 from './elements/step/ElementStepSize6';
c.push(ElementStepSize6);
import ElementStepSize7 from './elements/step/ElementStepSize7';
c.push(ElementStepSize7);
import ElementStepInverted1 from './elements/step/ElementStepInverted1';
c.push(ElementStepInverted1);
import ElementStepInverted2 from './elements/step/ElementStepInverted2';
c.push(ElementStepInverted2);
import ElementStepInverted3 from './elements/step/ElementStepInverted3';
c.push(ElementStepInverted3);
b.push(['step', c]); c = [];
// end of element [step]
// begin of element [text]
import ElementText1 from './elements/text/ElementText1';
c.push(ElementText1);
b.push(['text', c]); c = [];
// end of element [text]
a.push(['elements', b]); b = [];
// end of element type [elements]
// begin of element type [collections]
// begin of element [breadcrumb]
import CollectionBreadcrumbBreadcrumb1 from './collections/breadcrumb/CollectionBreadcrumbBreadcrumb1';
c.push(CollectionBreadcrumbBreadcrumb1);
import CollectionBreadcrumbBreadcrumb2 from './collections/breadcrumb/CollectionBreadcrumbBreadcrumb2';
c.push(CollectionBreadcrumbBreadcrumb2);
import CollectionBreadcrumbDivider1 from './collections/breadcrumb/CollectionBreadcrumbDivider1';
c.push(CollectionBreadcrumbDivider1);
import CollectionBreadcrumbDivider2 from './collections/breadcrumb/CollectionBreadcrumbDivider2';
c.push(CollectionBreadcrumbDivider2);
import CollectionBreadcrumbSection1 from './collections/breadcrumb/CollectionBreadcrumbSection1';
c.push(CollectionBreadcrumbSection1);
import CollectionBreadcrumbLink1 from './collections/breadcrumb/CollectionBreadcrumbLink1';
c.push(CollectionBreadcrumbLink1);
import CollectionBreadcrumbActive1 from './collections/breadcrumb/CollectionBreadcrumbActive1';
c.push(CollectionBreadcrumbActive1);
import CollectionBreadcrumbInverted1 from './collections/breadcrumb/CollectionBreadcrumbInverted1';
c.push(CollectionBreadcrumbInverted1);
import CollectionBreadcrumbSize1 from './collections/breadcrumb/CollectionBreadcrumbSize1';
c.push(CollectionBreadcrumbSize1);
import CollectionBreadcrumbSize2 from './collections/breadcrumb/CollectionBreadcrumbSize2';
c.push(CollectionBreadcrumbSize2);
import CollectionBreadcrumbSize3 from './collections/breadcrumb/CollectionBreadcrumbSize3';
c.push(CollectionBreadcrumbSize3);
import CollectionBreadcrumbSize4 from './collections/breadcrumb/CollectionBreadcrumbSize4';
c.push(CollectionBreadcrumbSize4);
import CollectionBreadcrumbSize5 from './collections/breadcrumb/CollectionBreadcrumbSize5';
c.push(CollectionBreadcrumbSize5);
import CollectionBreadcrumbSize6 from './collections/breadcrumb/CollectionBreadcrumbSize6';
c.push(CollectionBreadcrumbSize6);
import CollectionBreadcrumbSize7 from './collections/breadcrumb/CollectionBreadcrumbSize7';
c.push(CollectionBreadcrumbSize7);
b.push(['breadcrumb', c]); c = [];
// end of element [breadcrumb]
// begin of element [form]
import CollectionFormForm1 from './collections/form/CollectionFormForm1';
c.push(CollectionFormForm1);
import CollectionFormForm2 from './collections/form/CollectionFormForm2';
c.push(CollectionFormForm2);
import CollectionFormField1 from './collections/form/CollectionFormField1';
c.push(CollectionFormField1);
import CollectionFormFields1 from './collections/form/CollectionFormFields1';
c.push(CollectionFormFields1);
import CollectionFormFields2 from './collections/form/CollectionFormFields2';
c.push(CollectionFormFields2);
import CollectionFormFields3 from './collections/form/CollectionFormFields3';
c.push(CollectionFormFields3);
import CollectionFormTextArea1 from './collections/form/CollectionFormTextArea1';
c.push(CollectionFormTextArea1);
import CollectionFormCheckbox1 from './collections/form/CollectionFormCheckbox1';
c.push(CollectionFormCheckbox1);
import CollectionFormRadioCheckbox1 from './collections/form/CollectionFormRadioCheckbox1';
c.push(CollectionFormRadioCheckbox1);
import CollectionFormDropdown1 from './collections/form/CollectionFormDropdown1';
c.push(CollectionFormDropdown1);
import CollectionFormDropdown2 from './collections/form/CollectionFormDropdown2';
c.push(CollectionFormDropdown2);
import CollectionFormMultipleSelect1 from './collections/form/CollectionFormMultipleSelect1';
c.push(CollectionFormMultipleSelect1);
import CollectionFormHTMLSelect1 from './collections/form/CollectionFormHTMLSelect1';
c.push(CollectionFormHTMLSelect1);
import CollectionFormCalendar1 from './collections/form/CollectionFormCalendar1';
c.push(CollectionFormCalendar1);
import CollectionFormMessage1 from './collections/form/CollectionFormMessage1';
c.push(CollectionFormMessage1);
import CollectionFormLoading1 from './collections/form/CollectionFormLoading1';
c.push(CollectionFormLoading1);
import CollectionFormSuccess1 from './collections/form/CollectionFormSuccess1';
c.push(CollectionFormSuccess1);
import CollectionFormError1 from './collections/form/CollectionFormError1';
c.push(CollectionFormError1);
import CollectionFormWarning1 from './collections/form/CollectionFormWarning1';
c.push(CollectionFormWarning1);
import CollectionFormFieldError1 from './collections/form/CollectionFormFieldError1';
c.push(CollectionFormFieldError1);
import CollectionFormDisabledField1 from './collections/form/CollectionFormDisabledField1';
c.push(CollectionFormDisabledField1);
import CollectionFormReadOnlyField1 from './collections/form/CollectionFormReadOnlyField1';
c.push(CollectionFormReadOnlyField1);
import CollectionFormSize1 from './collections/form/CollectionFormSize1';
c.push(CollectionFormSize1);
import CollectionFormSize2 from './collections/form/CollectionFormSize2';
c.push(CollectionFormSize2);
import CollectionFormSize3 from './collections/form/CollectionFormSize3';
c.push(CollectionFormSize3);
import CollectionFormSize4 from './collections/form/CollectionFormSize4';
c.push(CollectionFormSize4);
import CollectionFormSize5 from './collections/form/CollectionFormSize5';
c.push(CollectionFormSize5);
import CollectionFormSize6 from './collections/form/CollectionFormSize6';
c.push(CollectionFormSize6);
import CollectionFormSize7 from './collections/form/CollectionFormSize7';
c.push(CollectionFormSize7);
import CollectionFormEqualWidthForm1 from './collections/form/CollectionFormEqualWidthForm1';
c.push(CollectionFormEqualWidthForm1);
import CollectionFormInverted1 from './collections/form/CollectionFormInverted1';
c.push(CollectionFormInverted1);
import CollectionFormInlineField1 from './collections/form/CollectionFormInlineField1';
c.push(CollectionFormInlineField1);
import CollectionFormWidth1 from './collections/form/CollectionFormWidth1';
c.push(CollectionFormWidth1);
import CollectionFormRequired1 from './collections/form/CollectionFormRequired1';
c.push(CollectionFormRequired1);
import CollectionFormTransparentTextarea1 from './collections/form/CollectionFormTransparentTextarea1';
c.push(CollectionFormTransparentTextarea1);
import CollectionFormEvenlyDivided1 from './collections/form/CollectionFormEvenlyDivided1';
c.push(CollectionFormEvenlyDivided1);
import CollectionFormGroupedFields1 from './collections/form/CollectionFormGroupedFields1';
c.push(CollectionFormGroupedFields1);
import CollectionFormEqualWidthFields1 from './collections/form/CollectionFormEqualWidthFields1';
c.push(CollectionFormEqualWidthFields1);
import CollectionFormInlineFields1 from './collections/form/CollectionFormInlineFields1';
c.push(CollectionFormInlineFields1);
import CollectionFormInlineFields2 from './collections/form/CollectionFormInlineFields2';
c.push(CollectionFormInlineFields2);
b.push(['form', c]); c = [];
// end of element [form]
// begin of element [grid]
import CollectionGrid1 from './collections/grid/CollectionGrid1';
c.push(CollectionGrid1);
import CollectionGrid1A from './collections/grid/CollectionGrid1A';
c.push(CollectionGrid1A);
b.push(['grid', c]); c = [];
// end of element [grid]
// begin of element [menu]
import CollectionMenuMenu1 from './collections/menu/CollectionMenuMenu1';
c.push(CollectionMenuMenu1);
import CollectionMenuMenu2 from './collections/menu/CollectionMenuMenu2';
c.push(CollectionMenuMenu2);
import CollectionMenuMenu3 from './collections/menu/CollectionMenuMenu3';
c.push(CollectionMenuMenu3);
import CollectionMenuSecondaryMenu1 from './collections/menu/CollectionMenuSecondaryMenu1';
c.push(CollectionMenuSecondaryMenu1);
import CollectionMenuPointing1 from './collections/menu/CollectionMenuPointing1';
c.push(CollectionMenuPointing1);
import CollectionMenuPointing2 from './collections/menu/CollectionMenuPointing2';
c.push(CollectionMenuPointing2);
import CollectionMenuTabular1 from './collections/menu/CollectionMenuTabular1';
c.push(CollectionMenuTabular1);
import CollectionMenuTabular2 from './collections/menu/CollectionMenuTabular2';
c.push(CollectionMenuTabular2);
import CollectionMenuTabular3 from './collections/menu/CollectionMenuTabular3';
c.push(CollectionMenuTabular3);
import CollectionMenuTabular4 from './collections/menu/CollectionMenuTabular4';
c.push(CollectionMenuTabular4);
import CollectionMenuTabular5 from './collections/menu/CollectionMenuTabular5';
c.push(CollectionMenuTabular5);
import CollectionMenuText1 from './collections/menu/CollectionMenuText1';
c.push(CollectionMenuText1);
import CollectionMenuVerticalMenu1 from './collections/menu/CollectionMenuVerticalMenu1';
c.push(CollectionMenuVerticalMenu1);
import CollectionMenuVerticalMenu2 from './collections/menu/CollectionMenuVerticalMenu2';
c.push(CollectionMenuVerticalMenu2);
import CollectionMenuVerticalMenu3 from './collections/menu/CollectionMenuVerticalMenu3';
c.push(CollectionMenuVerticalMenu3);
import CollectionMenuVerticalMenu4 from './collections/menu/CollectionMenuVerticalMenu4';
c.push(CollectionMenuVerticalMenu4);
import CollectionMenuVerticalMenu5 from './collections/menu/CollectionMenuVerticalMenu5';
c.push(CollectionMenuVerticalMenu5);
import CollectionMenuPagination1 from './collections/menu/CollectionMenuPagination1';
c.push(CollectionMenuPagination1);
import CollectionMenuHeader1 from './collections/menu/CollectionMenuHeader1';
c.push(CollectionMenuHeader1);
import CollectionMenuHeader2 from './collections/menu/CollectionMenuHeader2';
c.push(CollectionMenuHeader2);
import CollectionMenuText1A from './collections/menu/CollectionMenuText1A';
c.push(CollectionMenuText1A);
import CollectionMenuInput1 from './collections/menu/CollectionMenuInput1';
c.push(CollectionMenuInput1);
import CollectionMenuButton1 from './collections/menu/CollectionMenuButton1';
c.push(CollectionMenuButton1);
import CollectionMenuLinkItem1 from './collections/menu/CollectionMenuLinkItem1';
c.push(CollectionMenuLinkItem1);
import CollectionMenuDropdownItem1 from './collections/menu/CollectionMenuDropdownItem1';
c.push(CollectionMenuDropdownItem1);
import CollectionMenuPopupMenu1 from './collections/menu/CollectionMenuPopupMenu1';
c.push(CollectionMenuPopupMenu1);
import CollectionMenuSearch1 from './collections/menu/CollectionMenuSearch1';
c.push(CollectionMenuSearch1);
import CollectionMenuMenu1A from './collections/menu/CollectionMenuMenu1A';
c.push(CollectionMenuMenu1A);
import CollectionMenuSubMenu1 from './collections/menu/CollectionMenuSubMenu1';
c.push(CollectionMenuSubMenu1);
import CollectionMenuHover1 from './collections/menu/CollectionMenuHover1';
c.push(CollectionMenuHover1);
import CollectionMenuActive1 from './collections/menu/CollectionMenuActive1';
c.push(CollectionMenuActive1);
import CollectionMenuFixed1 from './collections/menu/CollectionMenuFixed1';
c.push(CollectionMenuFixed1);
import CollectionMenuFixed2 from './collections/menu/CollectionMenuFixed2';
c.push(CollectionMenuFixed2);
import CollectionMenuStackable1 from './collections/menu/CollectionMenuStackable1';
c.push(CollectionMenuStackable1);
import CollectionMenuInverted1 from './collections/menu/CollectionMenuInverted1';
c.push(CollectionMenuInverted1);
import CollectionMenuInverted2 from './collections/menu/CollectionMenuInverted2';
c.push(CollectionMenuInverted2);
import CollectionMenuInverted3 from './collections/menu/CollectionMenuInverted3';
c.push(CollectionMenuInverted3);
import CollectionMenuInverted4 from './collections/menu/CollectionMenuInverted4';
c.push(CollectionMenuInverted4);
import CollectionMenuInverted5 from './collections/menu/CollectionMenuInverted5';
c.push(CollectionMenuInverted5);
import CollectionMenuColored1 from './collections/menu/CollectionMenuColored1';
c.push(CollectionMenuColored1);
import CollectionMenuColored2 from './collections/menu/CollectionMenuColored2';
c.push(CollectionMenuColored2);
import CollectionMenuColored3 from './collections/menu/CollectionMenuColored3';
c.push(CollectionMenuColored3);
import CollectionMenuColored4 from './collections/menu/CollectionMenuColored4';
c.push(CollectionMenuColored4);
import CollectionMenuIcons1 from './collections/menu/CollectionMenuIcons1';
c.push(CollectionMenuIcons1);
import CollectionMenuLabeledIcon1 from './collections/menu/CollectionMenuLabeledIcon1';
c.push(CollectionMenuLabeledIcon1);
import CollectionMenuFluid1 from './collections/menu/CollectionMenuFluid1';
c.push(CollectionMenuFluid1);
import CollectionMenuCompact1 from './collections/menu/CollectionMenuCompact1';
c.push(CollectionMenuCompact1);
import CollectionMenuCompact2 from './collections/menu/CollectionMenuCompact2';
c.push(CollectionMenuCompact2);
import CollectionMenuEvenlyDivided1 from './collections/menu/CollectionMenuEvenlyDivided1';
c.push(CollectionMenuEvenlyDivided1);
import CollectionMenu1 from './collections/menu/CollectionMenu1';
c.push(CollectionMenu1);
import CollectionMenuAttached1 from './collections/menu/CollectionMenuAttached1';
c.push(CollectionMenuAttached1);
import CollectionMenuAttached2 from './collections/menu/CollectionMenuAttached2';
c.push(CollectionMenuAttached2);
import CollectionMenuSize1 from './collections/menu/CollectionMenuSize1';
c.push(CollectionMenuSize1);
import CollectionMenuSize2 from './collections/menu/CollectionMenuSize2';
c.push(CollectionMenuSize2);
import CollectionMenuSize3 from './collections/menu/CollectionMenuSize3';
c.push(CollectionMenuSize3);
import CollectionMenuSize4 from './collections/menu/CollectionMenuSize4';
c.push(CollectionMenuSize4);
import CollectionMenuSize5 from './collections/menu/CollectionMenuSize5';
c.push(CollectionMenuSize5);
import CollectionMenuSize6 from './collections/menu/CollectionMenuSize6';
c.push(CollectionMenuSize6);
import CollectionMenu1A from './collections/menu/CollectionMenu1A';
c.push(CollectionMenu1A);
import CollectionMenu2 from './collections/menu/CollectionMenu2';
c.push(CollectionMenu2);
import CollectionMenu3 from './collections/menu/CollectionMenu3';
c.push(CollectionMenu3);
import CollectionMenu4 from './collections/menu/CollectionMenu4';
c.push(CollectionMenu4);
import CollectionMenuFitted1 from './collections/menu/CollectionMenuFitted1';
c.push(CollectionMenuFitted1);
import CollectionMenuBorderless1 from './collections/menu/CollectionMenuBorderless1';
c.push(CollectionMenuBorderless1);
b.push(['menu', c]); c = [];
// end of element [menu]
// begin of element [message]
import CollectionMessageMessage1 from './collections/message/CollectionMessageMessage1';
c.push(CollectionMessageMessage1);
import CollectionMessageListMessage1 from './collections/message/CollectionMessageListMessage1';
c.push(CollectionMessageListMessage1);
import CollectionMessageIconMessage1 from './collections/message/CollectionMessageIconMessage1';
c.push(CollectionMessageIconMessage1);
import CollectionMessageIconMessage2 from './collections/message/CollectionMessageIconMessage2';
c.push(CollectionMessageIconMessage2);
import CollectionMessageDismissableBlock1 from './collections/message/CollectionMessageDismissableBlock1';
c.push(CollectionMessageDismissableBlock1);
import CollectionMessageHidden1 from './collections/message/CollectionMessageHidden1';
c.push(CollectionMessageHidden1);
import CollectionMessageVisible1 from './collections/message/CollectionMessageVisible1';
c.push(CollectionMessageVisible1);
import CollectionMessageFloating1 from './collections/message/CollectionMessageFloating1';
c.push(CollectionMessageFloating1);
import CollectionMessageCompact1 from './collections/message/CollectionMessageCompact1';
c.push(CollectionMessageCompact1);
import CollectionMessageAttached1 from './collections/message/CollectionMessageAttached1';
c.push(CollectionMessageAttached1);
import CollectionMessageWarning1 from './collections/message/CollectionMessageWarning1';
c.push(CollectionMessageWarning1);
import CollectionMessageInfo1 from './collections/message/CollectionMessageInfo1';
c.push(CollectionMessageInfo1);
import CollectionMessagePositiveSuccess1 from './collections/message/CollectionMessagePositiveSuccess1';
c.push(CollectionMessagePositiveSuccess1);
import CollectionMessagePositiveSuccess2 from './collections/message/CollectionMessagePositiveSuccess2';
c.push(CollectionMessagePositiveSuccess2);
import CollectionMessageNegativeError1 from './collections/message/CollectionMessageNegativeError1';
c.push(CollectionMessageNegativeError1);
import CollectionMessageNegativeError2 from './collections/message/CollectionMessageNegativeError2';
c.push(CollectionMessageNegativeError2);
import CollectionMessageColored1 from './collections/message/CollectionMessageColored1';
c.push(CollectionMessageColored1);
import CollectionMessageSize1 from './collections/message/CollectionMessageSize1';
c.push(CollectionMessageSize1);
b.push(['message', c]); c = [];
// end of element [message]
// begin of element [table]
import CollectionTableTable1 from './collections/table/CollectionTableTable1';
c.push(CollectionTableTable1);
import CollectionTableTable2 from './collections/table/CollectionTableTable2';
c.push(CollectionTableTable2);
import CollectionTableTable3 from './collections/table/CollectionTableTable3';
c.push(CollectionTableTable3);
import CollectionTableTable4 from './collections/table/CollectionTableTable4';
c.push(CollectionTableTable4);
import CollectionTableDefinition1 from './collections/table/CollectionTableDefinition1';
c.push(CollectionTableDefinition1);
import CollectionTableDefinition2 from './collections/table/CollectionTableDefinition2';
c.push(CollectionTableDefinition2);
import CollectionTableStructured1 from './collections/table/CollectionTableStructured1';
c.push(CollectionTableStructured1);
import CollectionTablePositiveNegative1 from './collections/table/CollectionTablePositiveNegative1';
c.push(CollectionTablePositiveNegative1);
import CollectionTableError1 from './collections/table/CollectionTableError1';
c.push(CollectionTableError1);
import CollectionTableWarning1 from './collections/table/CollectionTableWarning1';
c.push(CollectionTableWarning1);
import CollectionTableActive1 from './collections/table/CollectionTableActive1';
c.push(CollectionTableActive1);
import CollectionTableDisabled1 from './collections/table/CollectionTableDisabled1';
c.push(CollectionTableDisabled1);
import CollectionTableColoredCells1 from './collections/table/CollectionTableColoredCells1';
c.push(CollectionTableColoredCells1);
import CollectionTableSingleLine1 from './collections/table/CollectionTableSingleLine1';
c.push(CollectionTableSingleLine1);
import CollectionTableFixed1 from './collections/table/CollectionTableFixed1';
c.push(CollectionTableFixed1);
import CollectionTableFixed2 from './collections/table/CollectionTableFixed2';
c.push(CollectionTableFixed2);
import CollectionTableStacking1 from './collections/table/CollectionTableStacking1';
c.push(CollectionTableStacking1);
import CollectionTableSelectableRow1 from './collections/table/CollectionTableSelectableRow1';
c.push(CollectionTableSelectableRow1);
import CollectionTableSelectableRow2 from './collections/table/CollectionTableSelectableRow2';
c.push(CollectionTableSelectableRow2);
import CollectionTableSelectableCell1 from './collections/table/CollectionTableSelectableCell1';
c.push(CollectionTableSelectableCell1);
import CollectionTableVerticalAlignment1 from './collections/table/CollectionTableVerticalAlignment1';
c.push(CollectionTableVerticalAlignment1);
import CollectionTableTextAlignment1 from './collections/table/CollectionTableTextAlignment1';
c.push(CollectionTableTextAlignment1);
import CollectionTableStriped1 from './collections/table/CollectionTableStriped1';
c.push(CollectionTableStriped1);
import CollectionTableCelled1 from './collections/table/CollectionTableCelled1';
c.push(CollectionTableCelled1);
import CollectionTableBasic1 from './collections/table/CollectionTableBasic1';
c.push(CollectionTableBasic1);
import CollectionTableBasic2 from './collections/table/CollectionTableBasic2';
c.push(CollectionTableBasic2);
import CollectionTableCollapsingCell1 from './collections/table/CollectionTableCollapsingCell1';
c.push(CollectionTableCollapsingCell1);
import CollectionTableColumnCount1 from './collections/table/CollectionTableColumnCount1';
c.push(CollectionTableColumnCount1);
import CollectionTableColumnWidth1 from './collections/table/CollectionTableColumnWidth1';
c.push(CollectionTableColumnWidth1);
import CollectionTableCollapsing1 from './collections/table/CollectionTableCollapsing1';
c.push(CollectionTableCollapsing1);
import CollectionTableColored1 from './collections/table/CollectionTableColored1';
c.push(CollectionTableColored1);
import CollectionTableInverted1 from './collections/table/CollectionTableInverted1';
c.push(CollectionTableInverted1);
import CollectionTableInverted2 from './collections/table/CollectionTableInverted2';
c.push(CollectionTableInverted2);
import CollectionTableSortable1 from './collections/table/CollectionTableSortable1';
c.push(CollectionTableSortable1);
import CollectionTableFullWidthHeaderFooter1 from './collections/table/CollectionTableFullWidthHeaderFooter1';
c.push(CollectionTableFullWidthHeaderFooter1);
import CollectionTablePadded1 from './collections/table/CollectionTablePadded1';
c.push(CollectionTablePadded1);
import CollectionTablePadded2 from './collections/table/CollectionTablePadded2';
c.push(CollectionTablePadded2);
import CollectionTableCompact1 from './collections/table/CollectionTableCompact1';
c.push(CollectionTableCompact1);
import CollectionTableCompact2 from './collections/table/CollectionTableCompact2';
c.push(CollectionTableCompact2);
import CollectionTableSize1 from './collections/table/CollectionTableSize1';
c.push(CollectionTableSize1);
import CollectionTableSize2 from './collections/table/CollectionTableSize2';
c.push(CollectionTableSize2);
b.push(['table', c]); c = [];
// end of element [table]
a.push(['collections', b]); b = [];
// end of element type [collections]
// begin of element type [views]
// begin of element [advertisement]
import ViewAdvertisementAd1 from './views/advertisement/ViewAdvertisementAd1';
c.push(ViewAdvertisementAd1);
import ViewAdvertisementCommonUnits1 from './views/advertisement/ViewAdvertisementCommonUnits1';
c.push(ViewAdvertisementCommonUnits1);
import ViewAdvertisementMobile1 from './views/advertisement/ViewAdvertisementMobile1';
c.push(ViewAdvertisementMobile1);
import ViewAdvertisementRectangle1 from './views/advertisement/ViewAdvertisementRectangle1';
c.push(ViewAdvertisementRectangle1);
import ViewAdvertisementButton1 from './views/advertisement/ViewAdvertisementButton1';
c.push(ViewAdvertisementButton1);
import ViewAdvertisementSkyscraper1 from './views/advertisement/ViewAdvertisementSkyscraper1';
c.push(ViewAdvertisementSkyscraper1);
import ViewAdvertisementBanner1 from './views/advertisement/ViewAdvertisementBanner1';
c.push(ViewAdvertisementBanner1);
import ViewAdvertisementLeaderboards1 from './views/advertisement/ViewAdvertisementLeaderboards1';
c.push(ViewAdvertisementLeaderboards1);
import ViewAdvertisementPanorama1 from './views/advertisement/ViewAdvertisementPanorama1';
c.push(ViewAdvertisementPanorama1);
import ViewAdvertisementNetboard1 from './views/advertisement/ViewAdvertisementNetboard1';
c.push(ViewAdvertisementNetboard1);
import ViewAdvertisementCentered1 from './views/advertisement/ViewAdvertisementCentered1';
c.push(ViewAdvertisementCentered1);
import ViewAdvertisementTest1 from './views/advertisement/ViewAdvertisementTest1';
c.push(ViewAdvertisementTest1);
b.push(['advertisement', c]); c = [];
// end of element [advertisement]
// begin of element [card]
import ViewCardCard1 from './views/card/ViewCardCard1';
c.push(ViewCardCard1);
import ViewCardCard2 from './views/card/ViewCardCard2';
c.push(ViewCardCard2);
import ViewCardCards1 from './views/card/ViewCardCards1';
c.push(ViewCardCards1);
import ViewCardCards2 from './views/card/ViewCardCards2';
c.push(ViewCardCards2);
import ViewCardContentBlock1 from './views/card/ViewCardContentBlock1';
c.push(ViewCardContentBlock1);
import ViewCardImage1 from './views/card/ViewCardImage1';
c.push(ViewCardImage1);
import ViewCardImage2 from './views/card/ViewCardImage2';
c.push(ViewCardImage2);
import ViewCardHeader1 from './views/card/ViewCardHeader1';
c.push(ViewCardHeader1);
import ViewCardMetadata1 from './views/card/ViewCardMetadata1';
c.push(ViewCardMetadata1);
import ViewCardLink1 from './views/card/ViewCardLink1';
c.push(ViewCardLink1);
import ViewCardButtons1 from './views/card/ViewCardButtons1';
c.push(ViewCardButtons1);
import ViewCardApproval1 from './views/card/ViewCardApproval1';
c.push(ViewCardApproval1);
import ViewCardDescription1 from './views/card/ViewCardDescription1';
c.push(ViewCardDescription1);
import ViewCardExtraContent1 from './views/card/ViewCardExtraContent1';
c.push(ViewCardExtraContent1);
import ViewCardFluidCard1 from './views/card/ViewCardFluidCard1';
c.push(ViewCardFluidCard1);
import ViewCardCenteredCard1 from './views/card/ViewCardCenteredCard1';
c.push(ViewCardCenteredCard1);
import ViewCardHorizontalCards1 from './views/card/ViewCardHorizontalCards1';
c.push(ViewCardHorizontalCards1);
import ViewCardHorizontalCards2 from './views/card/ViewCardHorizontalCards2';
c.push(ViewCardHorizontalCards2);
import ViewCardRaisedCard1 from './views/card/ViewCardRaisedCard1';
c.push(ViewCardRaisedCard1);
import ViewCardRaisedCard2 from './views/card/ViewCardRaisedCard2';
c.push(ViewCardRaisedCard2);
import ViewCardLinkCard1 from './views/card/ViewCardLinkCard1';
c.push(ViewCardLinkCard1);
import ViewCardLinkCard2 from './views/card/ViewCardLinkCard2';
c.push(ViewCardLinkCard2);
import ViewCardFloatedContent1 from './views/card/ViewCardFloatedContent1';
c.push(ViewCardFloatedContent1);
import ViewCardTextAlignment1 from './views/card/ViewCardTextAlignment1';
c.push(ViewCardTextAlignment1);
import ViewCardInverted1 from './views/card/ViewCardInverted1';
c.push(ViewCardInverted1);
import ViewCardColored1 from './views/card/ViewCardColored1';
c.push(ViewCardColored1);
import ViewCardColumnCount1 from './views/card/ViewCardColumnCount1';
c.push(ViewCardColumnCount1);
import ViewCardStackable1 from './views/card/ViewCardStackable1';
c.push(ViewCardStackable1);
import ViewCardDoubling1 from './views/card/ViewCardDoubling1';
c.push(ViewCardDoubling1);
b.push(['card', c]); c = [];
// end of element [card]
// begin of element [comment]
import ViewCommentComments1 from './views/comment/ViewCommentComments1';
c.push(ViewCommentComments1);
import ViewCommentAvatar1 from './views/comment/ViewCommentAvatar1';
c.push(ViewCommentAvatar1);
import ViewCommentMetadata1 from './views/comment/ViewCommentMetadata1';
c.push(ViewCommentMetadata1);
import ViewCommentActions1 from './views/comment/ViewCommentActions1';
c.push(ViewCommentActions1);
import ViewCommentReplyForm1 from './views/comment/ViewCommentReplyForm1';
c.push(ViewCommentReplyForm1);
import ViewCommentReplyForm2 from './views/comment/ViewCommentReplyForm2';
c.push(ViewCommentReplyForm2);
import ViewCommentCollapsed1 from './views/comment/ViewCommentCollapsed1';
c.push(ViewCommentCollapsed1);
import ViewCommentThreaded1 from './views/comment/ViewCommentThreaded1';
c.push(ViewCommentThreaded1);
import ViewCommentMinimal1 from './views/comment/ViewCommentMinimal1';
c.push(ViewCommentMinimal1);
import ViewCommentSize1 from './views/comment/ViewCommentSize1';
c.push(ViewCommentSize1);
import ViewCommentSize2 from './views/comment/ViewCommentSize2';
c.push(ViewCommentSize2);
import ViewCommentInverted1 from './views/comment/ViewCommentInverted1';
c.push(ViewCommentInverted1);
b.push(['comment', c]); c = [];
// end of element [comment]
// begin of element [feed]
import ViewFeedFeed1 from './views/feed/ViewFeedFeed1';
c.push(ViewFeedFeed1);
import ViewFeedLabel1 from './views/feed/ViewFeedLabel1';
c.push(ViewFeedLabel1);
import ViewFeedLabel2 from './views/feed/ViewFeedLabel2';
c.push(ViewFeedLabel2);
import ViewFeedDate1 from './views/feed/ViewFeedDate1';
c.push(ViewFeedDate1);
import ViewFeedDate2 from './views/feed/ViewFeedDate2';
c.push(ViewFeedDate2);
import ViewFeedAdditionalinformation1 from './views/feed/ViewFeedAdditionalinformation1';
c.push(ViewFeedAdditionalinformation1);
import ViewFeedSize1 from './views/feed/ViewFeedSize1';
c.push(ViewFeedSize1);
import ViewFeedSize2 from './views/feed/ViewFeedSize2';
c.push(ViewFeedSize2);
b.push(['feed', c]); c = [];
// end of element [feed]
// begin of element [item]
import ViewItemItems1 from './views/item/ViewItemItems1';
c.push(ViewItemItems1);
import ViewItemImage1 from './views/item/ViewItemImage1';
c.push(ViewItemImage1);
import ViewItemContent1 from './views/item/ViewItemContent1';
c.push(ViewItemContent1);
import ViewItemHeader1 from './views/item/ViewItemHeader1';
c.push(ViewItemHeader1);
import ViewItemMetadata1 from './views/item/ViewItemMetadata1';
c.push(ViewItemMetadata1);
import ViewItemLink1 from './views/item/ViewItemLink1';
c.push(ViewItemLink1);
import ViewItemDescription1 from './views/item/ViewItemDescription1';
c.push(ViewItemDescription1);
import ViewItemExtraContent1 from './views/item/ViewItemExtraContent1';
c.push(ViewItemExtraContent1);
import ViewItemRating1 from './views/item/ViewItemRating1';
c.push(ViewItemRating1);
import ViewItemStacking1 from './views/item/ViewItemStacking1';
c.push(ViewItemStacking1);
import ViewItemDivided1 from './views/item/ViewItemDivided1';
c.push(ViewItemDivided1);
import ViewItemRelaxed1 from './views/item/ViewItemRelaxed1';
c.push(ViewItemRelaxed1);
import ViewItemRelaxed2 from './views/item/ViewItemRelaxed2';
c.push(ViewItemRelaxed2);
import ViewItemLinkItem1 from './views/item/ViewItemLinkItem1';
c.push(ViewItemLinkItem1);
import ViewItemVerticalAlignment1 from './views/item/ViewItemVerticalAlignment1';
c.push(ViewItemVerticalAlignment1);
import ViewItemFloatedContent1 from './views/item/ViewItemFloatedContent1';
c.push(ViewItemFloatedContent1);
import ViewItemInverted1 from './views/item/ViewItemInverted1';
c.push(ViewItemInverted1);
b.push(['item', c]); c = [];
// end of element [item]
// begin of element [statistic]
import ViewStatisticStatistic1 from './views/statistic/ViewStatisticStatistic1';
c.push(ViewStatisticStatistic1);
import ViewStatisticStatistic2 from './views/statistic/ViewStatisticStatistic2';
c.push(ViewStatisticStatistic2);
import ViewStatisticStatisticGroup1 from './views/statistic/ViewStatisticStatisticGroup1';
c.push(ViewStatisticStatisticGroup1);
import ViewStatisticValue1 from './views/statistic/ViewStatisticValue1';
c.push(ViewStatisticValue1);
import ViewStatisticLabel1 from './views/statistic/ViewStatisticLabel1';
c.push(ViewStatisticLabel1);
import ViewStatisticHorizontalStatistic1 from './views/statistic/ViewStatisticHorizontalStatistic1';
c.push(ViewStatisticHorizontalStatistic1);
import ViewStatisticHorizontalStatistic2 from './views/statistic/ViewStatisticHorizontalStatistic2';
c.push(ViewStatisticHorizontalStatistic2);
import ViewStatisticColored1 from './views/statistic/ViewStatisticColored1';
c.push(ViewStatisticColored1);
import ViewStatisticInverted1 from './views/statistic/ViewStatisticInverted1';
c.push(ViewStatisticInverted1);
import ViewStatisticStackable1 from './views/statistic/ViewStatisticStackable1';
c.push(ViewStatisticStackable1);
import ViewStatisticEvenlyDivided1 from './views/statistic/ViewStatisticEvenlyDivided1';
c.push(ViewStatisticEvenlyDivided1);
import ViewStatisticFloated1 from './views/statistic/ViewStatisticFloated1';
c.push(ViewStatisticFloated1);
import ViewStatisticSize1 from './views/statistic/ViewStatisticSize1';
c.push(ViewStatisticSize1);
import ViewStatisticSize2 from './views/statistic/ViewStatisticSize2';
c.push(ViewStatisticSize2);
b.push(['statistic', c]); c = [];
// end of element [statistic]
a.push(['views', b]); b = [];
// end of element type [views]
export default a;
