let a = [];
let b = [];
let c = [];
// begin of element type [elements]
// begin of element [button]
import ElementButtonButton1 from './elements/button/ElementButtonButton1';
c.append(ElementButtonButton1);
import ElementButtonButton2 from './elements/button/ElementButtonButton2';
c.append(ElementButtonButton2);
import ElementButtonEmphasis1 from './elements/button/ElementButtonEmphasis1';
c.append(ElementButtonEmphasis1);
import ElementButtonEmphasis2 from './elements/button/ElementButtonEmphasis2';
c.append(ElementButtonEmphasis2);
import ElementButtonAnimated1 from './elements/button/ElementButtonAnimated1';
c.append(ElementButtonAnimated1);
import ElementButtonLabeled1 from './elements/button/ElementButtonLabeled1';
c.append(ElementButtonLabeled1);
import ElementButtonLabeled2 from './elements/button/ElementButtonLabeled2';
c.append(ElementButtonLabeled2);
import ElementButtonIcon1 from './elements/button/ElementButtonIcon1';
c.append(ElementButtonIcon1);
import ElementButtonLabeledIcon1 from './elements/button/ElementButtonLabeledIcon1';
c.append(ElementButtonLabeledIcon1);
import ElementButtonBasic1 from './elements/button/ElementButtonBasic1';
c.append(ElementButtonBasic1);
import ElementButtonBasic2 from './elements/button/ElementButtonBasic2';
c.append(ElementButtonBasic2);
import ElementButtonBasic3 from './elements/button/ElementButtonBasic3';
c.append(ElementButtonBasic3);
import ElementButtonTertiary1 from './elements/button/ElementButtonTertiary1';
c.append(ElementButtonTertiary1);
import ElementButtonTertiary2 from './elements/button/ElementButtonTertiary2';
c.append(ElementButtonTertiary2);
import ElementButtonInverted1 from './elements/button/ElementButtonInverted1';
c.append(ElementButtonInverted1);
import ElementButtonInverted2 from './elements/button/ElementButtonInverted2';
c.append(ElementButtonInverted2);
import ElementButtonButtons1 from './elements/button/ElementButtonButtons1';
c.append(ElementButtonButtons1);
import ElementButtonIconButtons1 from './elements/button/ElementButtonIconButtons1';
c.append(ElementButtonIconButtons1);
import ElementButtonConditionals1 from './elements/button/ElementButtonConditionals1';
c.append(ElementButtonConditionals1);
import ElementButtonConditionals2 from './elements/button/ElementButtonConditionals2';
c.append(ElementButtonConditionals2);
import ElementButtonActive1 from './elements/button/ElementButtonActive1';
c.append(ElementButtonActive1);
import ElementButtonDisabled1 from './elements/button/ElementButtonDisabled1';
c.append(ElementButtonDisabled1);
import ElementButtonLoading1 from './elements/button/ElementButtonLoading1';
c.append(ElementButtonLoading1);
import ElementButtonSocial1 from './elements/button/ElementButtonSocial1';
c.append(ElementButtonSocial1);
import ElementButtonSize1 from './elements/button/ElementButtonSize1';
c.append(ElementButtonSize1);
import ElementButtonFloated1 from './elements/button/ElementButtonFloated1';
c.append(ElementButtonFloated1);
import ElementButtonColored1 from './elements/button/ElementButtonColored1';
c.append(ElementButtonColored1);
import ElementButtonCompact1 from './elements/button/ElementButtonCompact1';
c.append(ElementButtonCompact1);
import ElementButtonToggle1 from './elements/button/ElementButtonToggle1';
c.append(ElementButtonToggle1);
import ElementButtonPositive1 from './elements/button/ElementButtonPositive1';
c.append(ElementButtonPositive1);
import ElementButtonNegative1 from './elements/button/ElementButtonNegative1';
c.append(ElementButtonNegative1);
import ElementButtonFluid1 from './elements/button/ElementButtonFluid1';
c.append(ElementButtonFluid1);
import ElementButtonCircular1 from './elements/button/ElementButtonCircular1';
c.append(ElementButtonCircular1);
import ElementButtonCircular2 from './elements/button/ElementButtonCircular2';
c.append(ElementButtonCircular2);
import ElementButtonVerticallyAttached1 from './elements/button/ElementButtonVerticallyAttached1';
c.append(ElementButtonVerticallyAttached1);
import ElementButtonVerticallyAttached2 from './elements/button/ElementButtonVerticallyAttached2';
c.append(ElementButtonVerticallyAttached2);
import ElementButtonHorizontallyAttached1 from './elements/button/ElementButtonHorizontallyAttached1';
c.append(ElementButtonHorizontallyAttached1);
import ElementButtonVerticalButtons1 from './elements/button/ElementButtonVerticalButtons1';
c.append(ElementButtonVerticalButtons1);
import ElementButtonIconButtons1A from './elements/button/ElementButtonIconButtons1A';
c.append(ElementButtonIconButtons1A);
import ElementButtonLabeledIconButtons1 from './elements/button/ElementButtonLabeledIconButtons1';
c.append(ElementButtonLabeledIconButtons1);
import ElementButtonMixedGroup1 from './elements/button/ElementButtonMixedGroup1';
c.append(ElementButtonMixedGroup1);
import ElementButtonEqualWidth1 from './elements/button/ElementButtonEqualWidth1';
c.append(ElementButtonEqualWidth1);
import ElementButtonColoredButtons1 from './elements/button/ElementButtonColoredButtons1';
c.append(ElementButtonColoredButtons1);
import ElementButtonBasicButtons1 from './elements/button/ElementButtonBasicButtons1';
c.append(ElementButtonBasicButtons1);
import ElementButtonBasicButtons2 from './elements/button/ElementButtonBasicButtons2';
c.append(ElementButtonBasicButtons2);
import ElementButtonGroupSizes1 from './elements/button/ElementButtonGroupSizes1';
c.append(ElementButtonGroupSizes1);
import ElementButtonGroupSizes2 from './elements/button/ElementButtonGroupSizes2';
c.append(ElementButtonGroupSizes2);
import ElementButtonGroupSizes3 from './elements/button/ElementButtonGroupSizes3';
c.append(ElementButtonGroupSizes3);
b.append(['button', c]); c = [];
// end of element [button]
// begin of element [divider]
import ElementDividerDivider1 from './elements/divider/ElementDividerDivider1';
c.append(ElementDividerDivider1);
import ElementDividerVerticalDivider1 from './elements/divider/ElementDividerVerticalDivider1';
c.append(ElementDividerVerticalDivider1);
import ElementDividerVerticalDivider2 from './elements/divider/ElementDividerVerticalDivider2';
c.append(ElementDividerVerticalDivider2);
import ElementDividerHorizontalDivider1 from './elements/divider/ElementDividerHorizontalDivider1';
c.append(ElementDividerHorizontalDivider1);
import ElementDividerHorizontalDivider2 from './elements/divider/ElementDividerHorizontalDivider2';
c.append(ElementDividerHorizontalDivider2);
import ElementDividerHorizontalAlignment1 from './elements/divider/ElementDividerHorizontalAlignment1';
c.append(ElementDividerHorizontalAlignment1);
import ElementDividerInverted1 from './elements/divider/ElementDividerInverted1';
c.append(ElementDividerInverted1);
import ElementDividerFitted1 from './elements/divider/ElementDividerFitted1';
c.append(ElementDividerFitted1);
import ElementDividerHidden1 from './elements/divider/ElementDividerHidden1';
c.append(ElementDividerHidden1);
import ElementDividerSection1 from './elements/divider/ElementDividerSection1';
c.append(ElementDividerSection1);
import ElementDividerClearing1 from './elements/divider/ElementDividerClearing1';
c.append(ElementDividerClearing1);
b.append(['divider', c]); c = [];
// end of element [divider]
// begin of element [flag]
import ElementFlag1 from './elements/flag/ElementFlag1';
c.append(ElementFlag1);
b.append(['flag', c]); c = [];
// end of element [flag]
// begin of element [header]
import ElementHeaderPageHeaders1 from './elements/header/ElementHeaderPageHeaders1';
c.append(ElementHeaderPageHeaders1);
import ElementHeaderContentHeaders1 from './elements/header/ElementHeaderContentHeaders1';
c.append(ElementHeaderContentHeaders1);
import ElementHeaderIconHeaders1 from './elements/header/ElementHeaderIconHeaders1';
c.append(ElementHeaderIconHeaders1);
import ElementHeaderIconHeaders2 from './elements/header/ElementHeaderIconHeaders2';
c.append(ElementHeaderIconHeaders2);
import ElementHeaderSubHeaders1 from './elements/header/ElementHeaderSubHeaders1';
c.append(ElementHeaderSubHeaders1);
import ElementHeaderSubHeaders2 from './elements/header/ElementHeaderSubHeaders2';
c.append(ElementHeaderSubHeaders2);
import ElementHeaderImage1 from './elements/header/ElementHeaderImage1';
c.append(ElementHeaderImage1);
import ElementHeaderImage2 from './elements/header/ElementHeaderImage2';
c.append(ElementHeaderImage2);
import ElementHeaderImage3 from './elements/header/ElementHeaderImage3';
c.append(ElementHeaderImage3);
import ElementHeaderIcon1 from './elements/header/ElementHeaderIcon1';
c.append(ElementHeaderIcon1);
import ElementHeaderIcon2 from './elements/header/ElementHeaderIcon2';
c.append(ElementHeaderIcon2);
import ElementHeaderSubheader1 from './elements/header/ElementHeaderSubheader1';
c.append(ElementHeaderSubheader1);
import ElementHeaderSubheader2 from './elements/header/ElementHeaderSubheader2';
c.append(ElementHeaderSubheader2);
import ElementHeaderDisabled1 from './elements/header/ElementHeaderDisabled1';
c.append(ElementHeaderDisabled1);
import ElementHeaderDividing1 from './elements/header/ElementHeaderDividing1';
c.append(ElementHeaderDividing1);
import ElementHeaderBlock1 from './elements/header/ElementHeaderBlock1';
c.append(ElementHeaderBlock1);
import ElementHeaderAttached1 from './elements/header/ElementHeaderAttached1';
c.append(ElementHeaderAttached1);
import ElementHeaderFloating1 from './elements/header/ElementHeaderFloating1';
c.append(ElementHeaderFloating1);
import ElementHeaderTextAlignment1 from './elements/header/ElementHeaderTextAlignment1';
c.append(ElementHeaderTextAlignment1);
import ElementHeaderColored1 from './elements/header/ElementHeaderColored1';
c.append(ElementHeaderColored1);
import ElementHeaderInverted1 from './elements/header/ElementHeaderInverted1';
c.append(ElementHeaderInverted1);
b.append(['header', c]); c = [];
// end of element [header]
// begin of element [icon]
import ElementIcon1 from './elements/icon/ElementIcon1';
c.append(ElementIcon1);
import ElementIcon1A from './elements/icon/ElementIcon1A';
c.append(ElementIcon1A);
b.append(['icon', c]); c = [];
// end of element [icon]
// begin of element [image]
import ElementImageImage1 from './elements/image/ElementImageImage1';
c.append(ElementImageImage1);
import ElementImageImage2 from './elements/image/ElementImageImage2';
c.append(ElementImageImage2);
import ElementImageImage3 from './elements/image/ElementImageImage3';
c.append(ElementImageImage3);
import ElementImageImageLink1 from './elements/image/ElementImageImageLink1';
c.append(ElementImageImageLink1);
import ElementImageHidden1 from './elements/image/ElementImageHidden1';
c.append(ElementImageHidden1);
import ElementImageDisabled1 from './elements/image/ElementImageDisabled1';
c.append(ElementImageDisabled1);
import ElementImageAvatar1 from './elements/image/ElementImageAvatar1';
c.append(ElementImageAvatar1);
import ElementImageBordered1 from './elements/image/ElementImageBordered1';
c.append(ElementImageBordered1);
import ElementImageFluid1 from './elements/image/ElementImageFluid1';
c.append(ElementImageFluid1);
import ElementImageRounded1 from './elements/image/ElementImageRounded1';
c.append(ElementImageRounded1);
import ElementImageCircular1 from './elements/image/ElementImageCircular1';
c.append(ElementImageCircular1);
import ElementImageVerticallyAligned1 from './elements/image/ElementImageVerticallyAligned1';
c.append(ElementImageVerticallyAligned1);
import ElementImageCentered1 from './elements/image/ElementImageCentered1';
c.append(ElementImageCentered1);
import ElementImageSpaced1 from './elements/image/ElementImageSpaced1';
c.append(ElementImageSpaced1);
import ElementImageSpaced2 from './elements/image/ElementImageSpaced2';
c.append(ElementImageSpaced2);
import ElementImageFloated1 from './elements/image/ElementImageFloated1';
c.append(ElementImageFloated1);
import ElementImageSize1 from './elements/image/ElementImageSize1';
c.append(ElementImageSize1);
import ElementImageSize1A from './elements/image/ElementImageSize1A';
c.append(ElementImageSize1A);
import ElementImageSize2 from './elements/image/ElementImageSize2';
c.append(ElementImageSize2);
b.append(['image', c]); c = [];
// end of element [image]
// begin of element [input]
import ElementInputInput1 from './elements/input/ElementInputInput1';
c.append(ElementInputInput1);
import ElementInputFocus1 from './elements/input/ElementInputFocus1';
c.append(ElementInputFocus1);
import ElementInputLoading1 from './elements/input/ElementInputLoading1';
c.append(ElementInputLoading1);
import ElementInputLoading2 from './elements/input/ElementInputLoading2';
c.append(ElementInputLoading2);
import ElementInputLoading3 from './elements/input/ElementInputLoading3';
c.append(ElementInputLoading3);
import ElementInputLoading4 from './elements/input/ElementInputLoading4';
c.append(ElementInputLoading4);
import ElementInputDisabled1 from './elements/input/ElementInputDisabled1';
c.append(ElementInputDisabled1);
import ElementInputDisabled2 from './elements/input/ElementInputDisabled2';
c.append(ElementInputDisabled2);
import ElementInputDisabled3 from './elements/input/ElementInputDisabled3';
c.append(ElementInputDisabled3);
import ElementInputError1 from './elements/input/ElementInputError1';
c.append(ElementInputError1);
import ElementInputIcon1 from './elements/input/ElementInputIcon1';
c.append(ElementInputIcon1);
import ElementInputIcon2 from './elements/input/ElementInputIcon2';
c.append(ElementInputIcon2);
import ElementInputIcon3 from './elements/input/ElementInputIcon3';
c.append(ElementInputIcon3);
import ElementInputIcon4 from './elements/input/ElementInputIcon4';
c.append(ElementInputIcon4);
import ElementInputLabeled1 from './elements/input/ElementInputLabeled1';
c.append(ElementInputLabeled1);
import ElementInputLabeled2 from './elements/input/ElementInputLabeled2';
c.append(ElementInputLabeled2);
import ElementInputLabeled3 from './elements/input/ElementInputLabeled3';
c.append(ElementInputLabeled3);
import ElementInputLabeled4 from './elements/input/ElementInputLabeled4';
c.append(ElementInputLabeled4);
import ElementInputLabeled5 from './elements/input/ElementInputLabeled5';
c.append(ElementInputLabeled5);
import ElementInputLabeled6 from './elements/input/ElementInputLabeled6';
c.append(ElementInputLabeled6);
import ElementInputLabeled7 from './elements/input/ElementInputLabeled7';
c.append(ElementInputLabeled7);
import ElementInputAction1 from './elements/input/ElementInputAction1';
c.append(ElementInputAction1);
import ElementInputAction2 from './elements/input/ElementInputAction2';
c.append(ElementInputAction2);
import ElementInputAction3 from './elements/input/ElementInputAction3';
c.append(ElementInputAction3);
import ElementInputAction4 from './elements/input/ElementInputAction4';
c.append(ElementInputAction4);
import ElementInputAction5 from './elements/input/ElementInputAction5';
c.append(ElementInputAction5);
import ElementInputAction6 from './elements/input/ElementInputAction6';
c.append(ElementInputAction6);
import ElementInputTransparent1 from './elements/input/ElementInputTransparent1';
c.append(ElementInputTransparent1);
import ElementInputTransparent2 from './elements/input/ElementInputTransparent2';
c.append(ElementInputTransparent2);
import ElementInputTransparent3 from './elements/input/ElementInputTransparent3';
c.append(ElementInputTransparent3);
import ElementInputInverted1 from './elements/input/ElementInputInverted1';
c.append(ElementInputInverted1);
import ElementInputFluid1 from './elements/input/ElementInputFluid1';
c.append(ElementInputFluid1);
import ElementInputSize1 from './elements/input/ElementInputSize1';
c.append(ElementInputSize1);
import ElementInputSize2 from './elements/input/ElementInputSize2';
c.append(ElementInputSize2);
import ElementInputSize3 from './elements/input/ElementInputSize3';
c.append(ElementInputSize3);
import ElementInputSize4 from './elements/input/ElementInputSize4';
c.append(ElementInputSize4);
import ElementInputSize5 from './elements/input/ElementInputSize5';
c.append(ElementInputSize5);
import ElementInputSize6 from './elements/input/ElementInputSize6';
c.append(ElementInputSize6);
import ElementInputTextarea1 from './elements/input/ElementInputTextarea1';
c.append(ElementInputTextarea1);
b.append(['input', c]); c = [];
// end of element [input]
// begin of element [label]
import ElementLabelLabel1 from './elements/label/ElementLabelLabel1';
c.append(ElementLabelLabel1);
import ElementLabelImage1 from './elements/label/ElementLabelImage1';
c.append(ElementLabelImage1);
import ElementLabelImage2 from './elements/label/ElementLabelImage2';
c.append(ElementLabelImage2);
import ElementLabelImage3 from './elements/label/ElementLabelImage3';
c.append(ElementLabelImage3);
import ElementLabelPointing1 from './elements/label/ElementLabelPointing1';
c.append(ElementLabelPointing1);
import ElementLabelPointing2 from './elements/label/ElementLabelPointing2';
c.append(ElementLabelPointing2);
import ElementLabelCorner1 from './elements/label/ElementLabelCorner1';
c.append(ElementLabelCorner1);
import ElementLabelTag1 from './elements/label/ElementLabelTag1';
c.append(ElementLabelTag1);
import ElementLabelRibbon1 from './elements/label/ElementLabelRibbon1';
c.append(ElementLabelRibbon1);
import ElementLabelRibbon2 from './elements/label/ElementLabelRibbon2';
c.append(ElementLabelRibbon2);
import ElementLabelRibbon3 from './elements/label/ElementLabelRibbon3';
c.append(ElementLabelRibbon3);
import ElementLabelRibbon4 from './elements/label/ElementLabelRibbon4';
c.append(ElementLabelRibbon4);
import ElementLabelAttached1 from './elements/label/ElementLabelAttached1';
c.append(ElementLabelAttached1);
import ElementLabelHorizontal1 from './elements/label/ElementLabelHorizontal1';
c.append(ElementLabelHorizontal1);
import ElementLabelFloating1 from './elements/label/ElementLabelFloating1';
c.append(ElementLabelFloating1);
import ElementLabelFloatingleft1 from './elements/label/ElementLabelFloatingleft1';
c.append(ElementLabelFloatingleft1);
import ElementLabelFloatingaligned1 from './elements/label/ElementLabelFloatingaligned1';
c.append(ElementLabelFloatingaligned1);
import ElementLabelDetail1 from './elements/label/ElementLabelDetail1';
c.append(ElementLabelDetail1);
import ElementLabelIcon1 from './elements/label/ElementLabelIcon1';
c.append(ElementLabelIcon1);
import ElementLabelIcon2 from './elements/label/ElementLabelIcon2';
c.append(ElementLabelIcon2);
import ElementLabelIcon3 from './elements/label/ElementLabelIcon3';
c.append(ElementLabelIcon3);
import ElementLabelIcon4 from './elements/label/ElementLabelIcon4';
c.append(ElementLabelIcon4);
import ElementLabelImage1A from './elements/label/ElementLabelImage1A';
c.append(ElementLabelImage1A);
import ElementLabelLink1 from './elements/label/ElementLabelLink1';
c.append(ElementLabelLink1);
import ElementLabelLink2 from './elements/label/ElementLabelLink2';
c.append(ElementLabelLink2);
import ElementLabelCircular1 from './elements/label/ElementLabelCircular1';
c.append(ElementLabelCircular1);
import ElementLabelCircular2 from './elements/label/ElementLabelCircular2';
c.append(ElementLabelCircular2);
import ElementLabelBasic1 from './elements/label/ElementLabelBasic1';
c.append(ElementLabelBasic1);
import ElementLabelColored1 from './elements/label/ElementLabelColored1';
c.append(ElementLabelColored1);
import ElementLabelBasicTagLabels1 from './elements/label/ElementLabelBasicTagLabels1';
c.append(ElementLabelBasicTagLabels1);
import ElementLabelSize1 from './elements/label/ElementLabelSize1';
c.append(ElementLabelSize1);
import ElementLabelGroupSize1 from './elements/label/ElementLabelGroupSize1';
c.append(ElementLabelGroupSize1);
import ElementLabelColoredGroup1 from './elements/label/ElementLabelColoredGroup1';
c.append(ElementLabelColoredGroup1);
import ElementLabelBasicGroup1 from './elements/label/ElementLabelBasicGroup1';
c.append(ElementLabelBasicGroup1);
import ElementLabelTagGroup1 from './elements/label/ElementLabelTagGroup1';
c.append(ElementLabelTagGroup1);
import ElementLabelCircularGroup1 from './elements/label/ElementLabelCircularGroup1';
c.append(ElementLabelCircularGroup1);
import ElementLabelAllVariantsofLabelcanbeinverted1 from './elements/label/ElementLabelAllVariantsofLabelcanbeinverted1';
c.append(ElementLabelAllVariantsofLabelcanbeinverted1);
b.append(['label', c]); c = [];
// end of element [label]
// begin of element [list]
import ElementListList1 from './elements/list/ElementListList1';
c.append(ElementListList1);
import ElementListList2 from './elements/list/ElementListList2';
c.append(ElementListList2);
import ElementListList3 from './elements/list/ElementListList3';
c.append(ElementListList3);
import ElementListList4 from './elements/list/ElementListList4';
c.append(ElementListList4);
import ElementListBulleted1 from './elements/list/ElementListBulleted1';
c.append(ElementListBulleted1);
import ElementListBulleted2 from './elements/list/ElementListBulleted2';
c.append(ElementListBulleted2);
import ElementListBulleted3 from './elements/list/ElementListBulleted3';
c.append(ElementListBulleted3);
import ElementListOrdered1 from './elements/list/ElementListOrdered1';
c.append(ElementListOrdered1);
import ElementListOrdered2 from './elements/list/ElementListOrdered2';
c.append(ElementListOrdered2);
import ElementListOrdered3 from './elements/list/ElementListOrdered3';
c.append(ElementListOrdered3);
import ElementListOrdered4 from './elements/list/ElementListOrdered4';
c.append(ElementListOrdered4);
import ElementListLink1 from './elements/list/ElementListLink1';
c.append(ElementListLink1);
import ElementListItem1 from './elements/list/ElementListItem1';
c.append(ElementListItem1);
import ElementListIcon1 from './elements/list/ElementListIcon1';
c.append(ElementListIcon1);
import ElementListImage1 from './elements/list/ElementListImage1';
c.append(ElementListImage1);
import ElementListLink1A from './elements/list/ElementListLink1A';
c.append(ElementListLink1A);
import ElementListLink2 from './elements/list/ElementListLink2';
c.append(ElementListLink2);
import ElementListHeader1 from './elements/list/ElementListHeader1';
c.append(ElementListHeader1);
import ElementListDescription1 from './elements/list/ElementListDescription1';
c.append(ElementListDescription1);
import ElementListHorizontal1 from './elements/list/ElementListHorizontal1';
c.append(ElementListHorizontal1);
import ElementListHorizontal2 from './elements/list/ElementListHorizontal2';
c.append(ElementListHorizontal2);
import ElementListHorizontal3 from './elements/list/ElementListHorizontal3';
c.append(ElementListHorizontal3);
import ElementListInverted1 from './elements/list/ElementListInverted1';
c.append(ElementListInverted1);
import ElementListSelection1 from './elements/list/ElementListSelection1';
c.append(ElementListSelection1);
import ElementListAnimated1 from './elements/list/ElementListAnimated1';
c.append(ElementListAnimated1);
import ElementListRelaxed1 from './elements/list/ElementListRelaxed1';
c.append(ElementListRelaxed1);
import ElementListRelaxed2 from './elements/list/ElementListRelaxed2';
c.append(ElementListRelaxed2);
import ElementListRelaxed3 from './elements/list/ElementListRelaxed3';
c.append(ElementListRelaxed3);
import ElementListRelaxed4 from './elements/list/ElementListRelaxed4';
c.append(ElementListRelaxed4);
import ElementListDivided1 from './elements/list/ElementListDivided1';
c.append(ElementListDivided1);
import ElementListCelled1 from './elements/list/ElementListCelled1';
c.append(ElementListCelled1);
import ElementListCelled2 from './elements/list/ElementListCelled2';
c.append(ElementListCelled2);
import ElementListCelled3 from './elements/list/ElementListCelled3';
c.append(ElementListCelled3);
import ElementListSize1 from './elements/list/ElementListSize1';
c.append(ElementListSize1);
import ElementListSize2 from './elements/list/ElementListSize2';
c.append(ElementListSize2);
import ElementListSize3 from './elements/list/ElementListSize3';
c.append(ElementListSize3);
import ElementListSize4 from './elements/list/ElementListSize4';
c.append(ElementListSize4);
import ElementListSize5 from './elements/list/ElementListSize5';
c.append(ElementListSize5);
import ElementListSize6 from './elements/list/ElementListSize6';
c.append(ElementListSize6);
import ElementListSize7 from './elements/list/ElementListSize7';
c.append(ElementListSize7);
import ElementListVerticallyAligned1 from './elements/list/ElementListVerticallyAligned1';
c.append(ElementListVerticallyAligned1);
import ElementListFloated1 from './elements/list/ElementListFloated1';
c.append(ElementListFloated1);
import ElementListFloated2 from './elements/list/ElementListFloated2';
c.append(ElementListFloated2);
b.append(['list', c]); c = [];
// end of element [list]
// begin of element [loader]
import ElementLoaderLoader1 from './elements/loader/ElementLoaderLoader1';
c.append(ElementLoaderLoader1);
import ElementLoaderTextLoader1 from './elements/loader/ElementLoaderTextLoader1';
c.append(ElementLoaderTextLoader1);
import ElementLoaderTextLoader2 from './elements/loader/ElementLoaderTextLoader2';
c.append(ElementLoaderTextLoader2);
import ElementLoaderIndeterminate1 from './elements/loader/ElementLoaderIndeterminate1';
c.append(ElementLoaderIndeterminate1);
import ElementLoaderActive1 from './elements/loader/ElementLoaderActive1';
c.append(ElementLoaderActive1);
import ElementLoaderDisabled1 from './elements/loader/ElementLoaderDisabled1';
c.append(ElementLoaderDisabled1);
import ElementLoaderInline1 from './elements/loader/ElementLoaderInline1';
c.append(ElementLoaderInline1);
import ElementLoaderInlineCenter1 from './elements/loader/ElementLoaderInlineCenter1';
c.append(ElementLoaderInlineCenter1);
import ElementLoaderSpeed1 from './elements/loader/ElementLoaderSpeed1';
c.append(ElementLoaderSpeed1);
import ElementLoaderColors1 from './elements/loader/ElementLoaderColors1';
c.append(ElementLoaderColors1);
import ElementLoaderSize1 from './elements/loader/ElementLoaderSize1';
c.append(ElementLoaderSize1);
import ElementLoaderInverted1 from './elements/loader/ElementLoaderInverted1';
c.append(ElementLoaderInverted1);
import ElementLoaderInverted2 from './elements/loader/ElementLoaderInverted2';
c.append(ElementLoaderInverted2);
import ElementLoaderStyles1 from './elements/loader/ElementLoaderStyles1';
c.append(ElementLoaderStyles1);
b.append(['loader', c]); c = [];
// end of element [loader]
// begin of element [placeholder]
import ElementPlaceholderPlaceholder1 from './elements/placeholder/ElementPlaceholderPlaceholder1';
c.append(ElementPlaceholderPlaceholder1);
import ElementPlaceholderPlaceholder2 from './elements/placeholder/ElementPlaceholderPlaceholder2';
c.append(ElementPlaceholderPlaceholder2);
import ElementPlaceholderPlaceholder3 from './elements/placeholder/ElementPlaceholderPlaceholder3';
c.append(ElementPlaceholderPlaceholder3);
import ElementPlaceholderLines1 from './elements/placeholder/ElementPlaceholderLines1';
c.append(ElementPlaceholderLines1);
import ElementPlaceholderHeaders1 from './elements/placeholder/ElementPlaceholderHeaders1';
c.append(ElementPlaceholderHeaders1);
import ElementPlaceholderHeaders2 from './elements/placeholder/ElementPlaceholderHeaders2';
c.append(ElementPlaceholderHeaders2);
import ElementPlaceholderParagraph1 from './elements/placeholder/ElementPlaceholderParagraph1';
c.append(ElementPlaceholderParagraph1);
import ElementPlaceholderImage1 from './elements/placeholder/ElementPlaceholderImage1';
c.append(ElementPlaceholderImage1);
import ElementPlaceholderImage2 from './elements/placeholder/ElementPlaceholderImage2';
c.append(ElementPlaceholderImage2);
import ElementPlaceholderImage3 from './elements/placeholder/ElementPlaceholderImage3';
c.append(ElementPlaceholderImage3);
import ElementPlaceholderLineLength1 from './elements/placeholder/ElementPlaceholderLineLength1';
c.append(ElementPlaceholderLineLength1);
import ElementPlaceholderLineLength2 from './elements/placeholder/ElementPlaceholderLineLength2';
c.append(ElementPlaceholderLineLength2);
import ElementPlaceholderFluid1 from './elements/placeholder/ElementPlaceholderFluid1';
c.append(ElementPlaceholderFluid1);
import ElementPlaceholderInverted1 from './elements/placeholder/ElementPlaceholderInverted1';
c.append(ElementPlaceholderInverted1);
b.append(['placeholder', c]); c = [];
// end of element [placeholder]
// begin of element [rail]
import ElementRail1 from './elements/rail/ElementRail1';
c.append(ElementRail1);
import ElementRailRail1 from './elements/rail/ElementRailRail1';
c.append(ElementRailRail1);
import ElementRailInternal1 from './elements/rail/ElementRailInternal1';
c.append(ElementRailInternal1);
import ElementRailDividing1 from './elements/rail/ElementRailDividing1';
c.append(ElementRailDividing1);
import ElementRailAttached1 from './elements/rail/ElementRailAttached1';
c.append(ElementRailAttached1);
import ElementRailAttached2 from './elements/rail/ElementRailAttached2';
c.append(ElementRailAttached2);
import ElementRailClose1 from './elements/rail/ElementRailClose1';
c.append(ElementRailClose1);
import ElementRailClose2 from './elements/rail/ElementRailClose2';
c.append(ElementRailClose2);
import ElementRailSize1 from './elements/rail/ElementRailSize1';
c.append(ElementRailSize1);
b.append(['rail', c]); c = [];
// end of element [rail]
// begin of element [reveal]
import ElementRevealFade1 from './elements/reveal/ElementRevealFade1';
c.append(ElementRevealFade1);
import ElementRevealFade2 from './elements/reveal/ElementRevealFade2';
c.append(ElementRevealFade2);
import ElementRevealMove1 from './elements/reveal/ElementRevealMove1';
c.append(ElementRevealMove1);
import ElementRevealMove2 from './elements/reveal/ElementRevealMove2';
c.append(ElementRevealMove2);
import ElementRevealMove3 from './elements/reveal/ElementRevealMove3';
c.append(ElementRevealMove3);
import ElementRevealMove4 from './elements/reveal/ElementRevealMove4';
c.append(ElementRevealMove4);
import ElementRevealRotate1 from './elements/reveal/ElementRevealRotate1';
c.append(ElementRevealRotate1);
import ElementRevealRotate2 from './elements/reveal/ElementRevealRotate2';
c.append(ElementRevealRotate2);
import ElementRevealVisibleContent1 from './elements/reveal/ElementRevealVisibleContent1';
c.append(ElementRevealVisibleContent1);
import ElementRevealHiddenContent1 from './elements/reveal/ElementRevealHiddenContent1';
c.append(ElementRevealHiddenContent1);
import ElementRevealActive1 from './elements/reveal/ElementRevealActive1';
c.append(ElementRevealActive1);
import ElementRevealInstant1 from './elements/reveal/ElementRevealInstant1';
c.append(ElementRevealInstant1);
import ElementRevealDisabled1 from './elements/reveal/ElementRevealDisabled1';
c.append(ElementRevealDisabled1);
b.append(['reveal', c]); c = [];
// end of element [reveal]
// begin of element [segment]
import ElementSegmentSegment1 from './elements/segment/ElementSegmentSegment1';
c.append(ElementSegmentSegment1);
import ElementSegmentPlaceholderSegment1 from './elements/segment/ElementSegmentPlaceholderSegment1';
c.append(ElementSegmentPlaceholderSegment1);
import ElementSegmentPlaceholderSegment2 from './elements/segment/ElementSegmentPlaceholderSegment2';
c.append(ElementSegmentPlaceholderSegment2);
import ElementSegmentPlaceholderSegment3 from './elements/segment/ElementSegmentPlaceholderSegment3';
c.append(ElementSegmentPlaceholderSegment3);
import ElementSegmentRaised1 from './elements/segment/ElementSegmentRaised1';
c.append(ElementSegmentRaised1);
import ElementSegmentStacked1 from './elements/segment/ElementSegmentStacked1';
c.append(ElementSegmentStacked1);
import ElementSegmentStacked2 from './elements/segment/ElementSegmentStacked2';
c.append(ElementSegmentStacked2);
import ElementSegmentPiled1 from './elements/segment/ElementSegmentPiled1';
c.append(ElementSegmentPiled1);
import ElementSegmentVerticalSegment1 from './elements/segment/ElementSegmentVerticalSegment1';
c.append(ElementSegmentVerticalSegment1);
import ElementSegmentSegments1 from './elements/segment/ElementSegmentSegments1';
c.append(ElementSegmentSegments1);
import ElementSegmentSegments2 from './elements/segment/ElementSegmentSegments2';
c.append(ElementSegmentSegments2);
import ElementSegmentSegments3 from './elements/segment/ElementSegmentSegments3';
c.append(ElementSegmentSegments3);
import ElementSegmentSegments4 from './elements/segment/ElementSegmentSegments4';
c.append(ElementSegmentSegments4);
import ElementSegmentNestedSegments1 from './elements/segment/ElementSegmentNestedSegments1';
c.append(ElementSegmentNestedSegments1);
import ElementSegmentHorizontalSegments1 from './elements/segment/ElementSegmentHorizontalSegments1';
c.append(ElementSegmentHorizontalSegments1);
import ElementSegmentHorizontalSegments2 from './elements/segment/ElementSegmentHorizontalSegments2';
c.append(ElementSegmentHorizontalSegments2);
import ElementSegmentHorizontalstackableSegments1 from './elements/segment/ElementSegmentHorizontalstackableSegments1';
c.append(ElementSegmentHorizontalstackableSegments1);
import ElementSegmentRaisedSegments1 from './elements/segment/ElementSegmentRaisedSegments1';
c.append(ElementSegmentRaisedSegments1);
import ElementSegmentStackedSegments1 from './elements/segment/ElementSegmentStackedSegments1';
c.append(ElementSegmentStackedSegments1);
import ElementSegmentPiledSegments1 from './elements/segment/ElementSegmentPiledSegments1';
c.append(ElementSegmentPiledSegments1);
import ElementSegmentDisabled1 from './elements/segment/ElementSegmentDisabled1';
c.append(ElementSegmentDisabled1);
import ElementSegmentLoading1 from './elements/segment/ElementSegmentLoading1';
c.append(ElementSegmentLoading1);
import ElementSegmentLoading2 from './elements/segment/ElementSegmentLoading2';
c.append(ElementSegmentLoading2);
import ElementSegmentInverted1 from './elements/segment/ElementSegmentInverted1';
c.append(ElementSegmentInverted1);
import ElementSegmentAttached1 from './elements/segment/ElementSegmentAttached1';
c.append(ElementSegmentAttached1);
import ElementSegmentAttached2 from './elements/segment/ElementSegmentAttached2';
c.append(ElementSegmentAttached2);
import ElementSegmentPadded1 from './elements/segment/ElementSegmentPadded1';
c.append(ElementSegmentPadded1);
import ElementSegmentPadded2 from './elements/segment/ElementSegmentPadded2';
c.append(ElementSegmentPadded2);
import ElementSegmentFitted1 from './elements/segment/ElementSegmentFitted1';
c.append(ElementSegmentFitted1);
import ElementSegmentCompact1 from './elements/segment/ElementSegmentCompact1';
c.append(ElementSegmentCompact1);
import ElementSegmentCompact2 from './elements/segment/ElementSegmentCompact2';
c.append(ElementSegmentCompact2);
import ElementSegmentColored1 from './elements/segment/ElementSegmentColored1';
c.append(ElementSegmentColored1);
import ElementSegmentColored2 from './elements/segment/ElementSegmentColored2';
c.append(ElementSegmentColored2);
import ElementSegmentEmphasis1 from './elements/segment/ElementSegmentEmphasis1';
c.append(ElementSegmentEmphasis1);
import ElementSegmentEmphasis2 from './elements/segment/ElementSegmentEmphasis2';
c.append(ElementSegmentEmphasis2);
import ElementSegmentEmphasis3 from './elements/segment/ElementSegmentEmphasis3';
c.append(ElementSegmentEmphasis3);
import ElementSegmentCircular1 from './elements/segment/ElementSegmentCircular1';
c.append(ElementSegmentCircular1);
import ElementSegmentClearing1 from './elements/segment/ElementSegmentClearing1';
c.append(ElementSegmentClearing1);
import ElementSegmentFloated1 from './elements/segment/ElementSegmentFloated1';
c.append(ElementSegmentFloated1);
import ElementSegmentTextAlignment1 from './elements/segment/ElementSegmentTextAlignment1';
c.append(ElementSegmentTextAlignment1);
import ElementSegmentBasic1 from './elements/segment/ElementSegmentBasic1';
c.append(ElementSegmentBasic1);
b.append(['segment', c]); c = [];
// end of element [segment]
// begin of element [step]
import ElementStepStep1 from './elements/step/ElementStepStep1';
c.append(ElementStepStep1);
import ElementStepSteps1 from './elements/step/ElementStepSteps1';
c.append(ElementStepSteps1);
import ElementStepOrdered1 from './elements/step/ElementStepOrdered1';
c.append(ElementStepOrdered1);
import ElementStepVertical1 from './elements/step/ElementStepVertical1';
c.append(ElementStepVertical1);
import ElementStepDescription1 from './elements/step/ElementStepDescription1';
c.append(ElementStepDescription1);
import ElementStepIcon1 from './elements/step/ElementStepIcon1';
c.append(ElementStepIcon1);
import ElementStepLink1 from './elements/step/ElementStepLink1';
c.append(ElementStepLink1);
import ElementStepLink2 from './elements/step/ElementStepLink2';
c.append(ElementStepLink2);
import ElementStepActive1 from './elements/step/ElementStepActive1';
c.append(ElementStepActive1);
import ElementStepCompleted1 from './elements/step/ElementStepCompleted1';
c.append(ElementStepCompleted1);
import ElementStepCompleted2 from './elements/step/ElementStepCompleted2';
c.append(ElementStepCompleted2);
import ElementStepDisabled1 from './elements/step/ElementStepDisabled1';
c.append(ElementStepDisabled1);
import ElementStepStackable1 from './elements/step/ElementStepStackable1';
c.append(ElementStepStackable1);
import ElementStepFluid1 from './elements/step/ElementStepFluid1';
c.append(ElementStepFluid1);
import ElementStepUnstackable1 from './elements/step/ElementStepUnstackable1';
c.append(ElementStepUnstackable1);
import ElementStepAttached1 from './elements/step/ElementStepAttached1';
c.append(ElementStepAttached1);
import ElementStepEvenlyDivided1 from './elements/step/ElementStepEvenlyDivided1';
c.append(ElementStepEvenlyDivided1);
import ElementStepEvenlyDivided2 from './elements/step/ElementStepEvenlyDivided2';
c.append(ElementStepEvenlyDivided2);
import ElementStepSize1 from './elements/step/ElementStepSize1';
c.append(ElementStepSize1);
import ElementStepSize2 from './elements/step/ElementStepSize2';
c.append(ElementStepSize2);
import ElementStepSize3 from './elements/step/ElementStepSize3';
c.append(ElementStepSize3);
import ElementStepSize4 from './elements/step/ElementStepSize4';
c.append(ElementStepSize4);
import ElementStepSize5 from './elements/step/ElementStepSize5';
c.append(ElementStepSize5);
import ElementStepSize6 from './elements/step/ElementStepSize6';
c.append(ElementStepSize6);
import ElementStepSize7 from './elements/step/ElementStepSize7';
c.append(ElementStepSize7);
import ElementStepInverted1 from './elements/step/ElementStepInverted1';
c.append(ElementStepInverted1);
import ElementStepInverted2 from './elements/step/ElementStepInverted2';
c.append(ElementStepInverted2);
import ElementStepInverted3 from './elements/step/ElementStepInverted3';
c.append(ElementStepInverted3);
b.append(['step', c]); c = [];
// end of element [step]
// begin of element [text]
import ElementText1 from './elements/text/ElementText1';
c.append(ElementText1);
b.append(['text', c]); c = [];
// end of element [text]
a.append(['elements', b]); b = [];
// end of element type [elements]
// begin of element type [collections]
// begin of element [breadcrumb]
import CollectionBreadcrumbBreadcrumb1 from './collections/breadcrumb/CollectionBreadcrumbBreadcrumb1';
c.append(CollectionBreadcrumbBreadcrumb1);
import CollectionBreadcrumbBreadcrumb2 from './collections/breadcrumb/CollectionBreadcrumbBreadcrumb2';
c.append(CollectionBreadcrumbBreadcrumb2);
import CollectionBreadcrumbDivider1 from './collections/breadcrumb/CollectionBreadcrumbDivider1';
c.append(CollectionBreadcrumbDivider1);
import CollectionBreadcrumbDivider2 from './collections/breadcrumb/CollectionBreadcrumbDivider2';
c.append(CollectionBreadcrumbDivider2);
import CollectionBreadcrumbSection1 from './collections/breadcrumb/CollectionBreadcrumbSection1';
c.append(CollectionBreadcrumbSection1);
import CollectionBreadcrumbLink1 from './collections/breadcrumb/CollectionBreadcrumbLink1';
c.append(CollectionBreadcrumbLink1);
import CollectionBreadcrumbActive1 from './collections/breadcrumb/CollectionBreadcrumbActive1';
c.append(CollectionBreadcrumbActive1);
import CollectionBreadcrumbInverted1 from './collections/breadcrumb/CollectionBreadcrumbInverted1';
c.append(CollectionBreadcrumbInverted1);
import CollectionBreadcrumbSize1 from './collections/breadcrumb/CollectionBreadcrumbSize1';
c.append(CollectionBreadcrumbSize1);
import CollectionBreadcrumbSize2 from './collections/breadcrumb/CollectionBreadcrumbSize2';
c.append(CollectionBreadcrumbSize2);
import CollectionBreadcrumbSize3 from './collections/breadcrumb/CollectionBreadcrumbSize3';
c.append(CollectionBreadcrumbSize3);
import CollectionBreadcrumbSize4 from './collections/breadcrumb/CollectionBreadcrumbSize4';
c.append(CollectionBreadcrumbSize4);
import CollectionBreadcrumbSize5 from './collections/breadcrumb/CollectionBreadcrumbSize5';
c.append(CollectionBreadcrumbSize5);
import CollectionBreadcrumbSize6 from './collections/breadcrumb/CollectionBreadcrumbSize6';
c.append(CollectionBreadcrumbSize6);
import CollectionBreadcrumbSize7 from './collections/breadcrumb/CollectionBreadcrumbSize7';
c.append(CollectionBreadcrumbSize7);
b.append(['breadcrumb', c]); c = [];
// end of element [breadcrumb]
// begin of element [form]
import CollectionFormForm1 from './collections/form/CollectionFormForm1';
c.append(CollectionFormForm1);
import CollectionFormForm2 from './collections/form/CollectionFormForm2';
c.append(CollectionFormForm2);
import CollectionFormField1 from './collections/form/CollectionFormField1';
c.append(CollectionFormField1);
import CollectionFormFields1 from './collections/form/CollectionFormFields1';
c.append(CollectionFormFields1);
import CollectionFormFields2 from './collections/form/CollectionFormFields2';
c.append(CollectionFormFields2);
import CollectionFormFields3 from './collections/form/CollectionFormFields3';
c.append(CollectionFormFields3);
import CollectionFormTextArea1 from './collections/form/CollectionFormTextArea1';
c.append(CollectionFormTextArea1);
import CollectionFormCheckbox1 from './collections/form/CollectionFormCheckbox1';
c.append(CollectionFormCheckbox1);
import CollectionFormRadioCheckbox1 from './collections/form/CollectionFormRadioCheckbox1';
c.append(CollectionFormRadioCheckbox1);
import CollectionFormDropdown1 from './collections/form/CollectionFormDropdown1';
c.append(CollectionFormDropdown1);
import CollectionFormDropdown2 from './collections/form/CollectionFormDropdown2';
c.append(CollectionFormDropdown2);
import CollectionFormMultipleSelect1 from './collections/form/CollectionFormMultipleSelect1';
c.append(CollectionFormMultipleSelect1);
import CollectionFormHTMLSelect1 from './collections/form/CollectionFormHTMLSelect1';
c.append(CollectionFormHTMLSelect1);
import CollectionFormCalendar1 from './collections/form/CollectionFormCalendar1';
c.append(CollectionFormCalendar1);
import CollectionFormMessage1 from './collections/form/CollectionFormMessage1';
c.append(CollectionFormMessage1);
import CollectionFormLoading1 from './collections/form/CollectionFormLoading1';
c.append(CollectionFormLoading1);
import CollectionFormSuccess1 from './collections/form/CollectionFormSuccess1';
c.append(CollectionFormSuccess1);
import CollectionFormError1 from './collections/form/CollectionFormError1';
c.append(CollectionFormError1);
import CollectionFormWarning1 from './collections/form/CollectionFormWarning1';
c.append(CollectionFormWarning1);
import CollectionFormFieldError1 from './collections/form/CollectionFormFieldError1';
c.append(CollectionFormFieldError1);
import CollectionFormDisabledField1 from './collections/form/CollectionFormDisabledField1';
c.append(CollectionFormDisabledField1);
import CollectionFormReadOnlyField1 from './collections/form/CollectionFormReadOnlyField1';
c.append(CollectionFormReadOnlyField1);
import CollectionFormSize1 from './collections/form/CollectionFormSize1';
c.append(CollectionFormSize1);
import CollectionFormSize2 from './collections/form/CollectionFormSize2';
c.append(CollectionFormSize2);
import CollectionFormSize3 from './collections/form/CollectionFormSize3';
c.append(CollectionFormSize3);
import CollectionFormSize4 from './collections/form/CollectionFormSize4';
c.append(CollectionFormSize4);
import CollectionFormSize5 from './collections/form/CollectionFormSize5';
c.append(CollectionFormSize5);
import CollectionFormSize6 from './collections/form/CollectionFormSize6';
c.append(CollectionFormSize6);
import CollectionFormSize7 from './collections/form/CollectionFormSize7';
c.append(CollectionFormSize7);
import CollectionFormEqualWidthForm1 from './collections/form/CollectionFormEqualWidthForm1';
c.append(CollectionFormEqualWidthForm1);
import CollectionFormInverted1 from './collections/form/CollectionFormInverted1';
c.append(CollectionFormInverted1);
import CollectionFormInlineField1 from './collections/form/CollectionFormInlineField1';
c.append(CollectionFormInlineField1);
import CollectionFormWidth1 from './collections/form/CollectionFormWidth1';
c.append(CollectionFormWidth1);
import CollectionFormRequired1 from './collections/form/CollectionFormRequired1';
c.append(CollectionFormRequired1);
import CollectionFormTransparentTextarea1 from './collections/form/CollectionFormTransparentTextarea1';
c.append(CollectionFormTransparentTextarea1);
import CollectionFormEvenlyDivided1 from './collections/form/CollectionFormEvenlyDivided1';
c.append(CollectionFormEvenlyDivided1);
import CollectionFormGroupedFields1 from './collections/form/CollectionFormGroupedFields1';
c.append(CollectionFormGroupedFields1);
import CollectionFormEqualWidthFields1 from './collections/form/CollectionFormEqualWidthFields1';
c.append(CollectionFormEqualWidthFields1);
import CollectionFormInlineFields1 from './collections/form/CollectionFormInlineFields1';
c.append(CollectionFormInlineFields1);
import CollectionFormInlineFields2 from './collections/form/CollectionFormInlineFields2';
c.append(CollectionFormInlineFields2);
b.append(['form', c]); c = [];
// end of element [form]
// begin of element [grid]
import CollectionGrid1 from './collections/grid/CollectionGrid1';
c.append(CollectionGrid1);
import CollectionGrid1A from './collections/grid/CollectionGrid1A';
c.append(CollectionGrid1A);
b.append(['grid', c]); c = [];
// end of element [grid]
// begin of element [menu]
import CollectionMenuMenu1 from './collections/menu/CollectionMenuMenu1';
c.append(CollectionMenuMenu1);
import CollectionMenuMenu2 from './collections/menu/CollectionMenuMenu2';
c.append(CollectionMenuMenu2);
import CollectionMenuMenu3 from './collections/menu/CollectionMenuMenu3';
c.append(CollectionMenuMenu3);
import CollectionMenuSecondaryMenu1 from './collections/menu/CollectionMenuSecondaryMenu1';
c.append(CollectionMenuSecondaryMenu1);
import CollectionMenuPointing1 from './collections/menu/CollectionMenuPointing1';
c.append(CollectionMenuPointing1);
import CollectionMenuPointing2 from './collections/menu/CollectionMenuPointing2';
c.append(CollectionMenuPointing2);
import CollectionMenuTabular1 from './collections/menu/CollectionMenuTabular1';
c.append(CollectionMenuTabular1);
import CollectionMenuTabular2 from './collections/menu/CollectionMenuTabular2';
c.append(CollectionMenuTabular2);
import CollectionMenuTabular3 from './collections/menu/CollectionMenuTabular3';
c.append(CollectionMenuTabular3);
import CollectionMenuTabular4 from './collections/menu/CollectionMenuTabular4';
c.append(CollectionMenuTabular4);
import CollectionMenuTabular5 from './collections/menu/CollectionMenuTabular5';
c.append(CollectionMenuTabular5);
import CollectionMenuText1 from './collections/menu/CollectionMenuText1';
c.append(CollectionMenuText1);
import CollectionMenuVerticalMenu1 from './collections/menu/CollectionMenuVerticalMenu1';
c.append(CollectionMenuVerticalMenu1);
import CollectionMenuVerticalMenu2 from './collections/menu/CollectionMenuVerticalMenu2';
c.append(CollectionMenuVerticalMenu2);
import CollectionMenuVerticalMenu3 from './collections/menu/CollectionMenuVerticalMenu3';
c.append(CollectionMenuVerticalMenu3);
import CollectionMenuVerticalMenu4 from './collections/menu/CollectionMenuVerticalMenu4';
c.append(CollectionMenuVerticalMenu4);
import CollectionMenuVerticalMenu5 from './collections/menu/CollectionMenuVerticalMenu5';
c.append(CollectionMenuVerticalMenu5);
import CollectionMenuPagination1 from './collections/menu/CollectionMenuPagination1';
c.append(CollectionMenuPagination1);
import CollectionMenuHeader1 from './collections/menu/CollectionMenuHeader1';
c.append(CollectionMenuHeader1);
import CollectionMenuHeader2 from './collections/menu/CollectionMenuHeader2';
c.append(CollectionMenuHeader2);
import CollectionMenuText1A from './collections/menu/CollectionMenuText1A';
c.append(CollectionMenuText1A);
import CollectionMenuInput1 from './collections/menu/CollectionMenuInput1';
c.append(CollectionMenuInput1);
import CollectionMenuButton1 from './collections/menu/CollectionMenuButton1';
c.append(CollectionMenuButton1);
import CollectionMenuLinkItem1 from './collections/menu/CollectionMenuLinkItem1';
c.append(CollectionMenuLinkItem1);
import CollectionMenuDropdownItem1 from './collections/menu/CollectionMenuDropdownItem1';
c.append(CollectionMenuDropdownItem1);
import CollectionMenuPopupMenu1 from './collections/menu/CollectionMenuPopupMenu1';
c.append(CollectionMenuPopupMenu1);
import CollectionMenuSearch1 from './collections/menu/CollectionMenuSearch1';
c.append(CollectionMenuSearch1);
import CollectionMenuMenu1A from './collections/menu/CollectionMenuMenu1A';
c.append(CollectionMenuMenu1A);
import CollectionMenuSubMenu1 from './collections/menu/CollectionMenuSubMenu1';
c.append(CollectionMenuSubMenu1);
import CollectionMenuHover1 from './collections/menu/CollectionMenuHover1';
c.append(CollectionMenuHover1);
import CollectionMenuActive1 from './collections/menu/CollectionMenuActive1';
c.append(CollectionMenuActive1);
import CollectionMenuFixed1 from './collections/menu/CollectionMenuFixed1';
c.append(CollectionMenuFixed1);
import CollectionMenuFixed2 from './collections/menu/CollectionMenuFixed2';
c.append(CollectionMenuFixed2);
import CollectionMenuStackable1 from './collections/menu/CollectionMenuStackable1';
c.append(CollectionMenuStackable1);
import CollectionMenuInverted1 from './collections/menu/CollectionMenuInverted1';
c.append(CollectionMenuInverted1);
import CollectionMenuInverted2 from './collections/menu/CollectionMenuInverted2';
c.append(CollectionMenuInverted2);
import CollectionMenuInverted3 from './collections/menu/CollectionMenuInverted3';
c.append(CollectionMenuInverted3);
import CollectionMenuInverted4 from './collections/menu/CollectionMenuInverted4';
c.append(CollectionMenuInverted4);
import CollectionMenuInverted5 from './collections/menu/CollectionMenuInverted5';
c.append(CollectionMenuInverted5);
import CollectionMenuColored1 from './collections/menu/CollectionMenuColored1';
c.append(CollectionMenuColored1);
import CollectionMenuColored2 from './collections/menu/CollectionMenuColored2';
c.append(CollectionMenuColored2);
import CollectionMenuColored3 from './collections/menu/CollectionMenuColored3';
c.append(CollectionMenuColored3);
import CollectionMenuColored4 from './collections/menu/CollectionMenuColored4';
c.append(CollectionMenuColored4);
import CollectionMenuIcons1 from './collections/menu/CollectionMenuIcons1';
c.append(CollectionMenuIcons1);
import CollectionMenuLabeledIcon1 from './collections/menu/CollectionMenuLabeledIcon1';
c.append(CollectionMenuLabeledIcon1);
import CollectionMenuFluid1 from './collections/menu/CollectionMenuFluid1';
c.append(CollectionMenuFluid1);
import CollectionMenuCompact1 from './collections/menu/CollectionMenuCompact1';
c.append(CollectionMenuCompact1);
import CollectionMenuCompact2 from './collections/menu/CollectionMenuCompact2';
c.append(CollectionMenuCompact2);
import CollectionMenuEvenlyDivided1 from './collections/menu/CollectionMenuEvenlyDivided1';
c.append(CollectionMenuEvenlyDivided1);
import CollectionMenu1 from './collections/menu/CollectionMenu1';
c.append(CollectionMenu1);
import CollectionMenuAttached1 from './collections/menu/CollectionMenuAttached1';
c.append(CollectionMenuAttached1);
import CollectionMenuAttached2 from './collections/menu/CollectionMenuAttached2';
c.append(CollectionMenuAttached2);
import CollectionMenuSize1 from './collections/menu/CollectionMenuSize1';
c.append(CollectionMenuSize1);
import CollectionMenuSize2 from './collections/menu/CollectionMenuSize2';
c.append(CollectionMenuSize2);
import CollectionMenuSize3 from './collections/menu/CollectionMenuSize3';
c.append(CollectionMenuSize3);
import CollectionMenuSize4 from './collections/menu/CollectionMenuSize4';
c.append(CollectionMenuSize4);
import CollectionMenuSize5 from './collections/menu/CollectionMenuSize5';
c.append(CollectionMenuSize5);
import CollectionMenuSize6 from './collections/menu/CollectionMenuSize6';
c.append(CollectionMenuSize6);
import CollectionMenu1A from './collections/menu/CollectionMenu1A';
c.append(CollectionMenu1A);
import CollectionMenu2 from './collections/menu/CollectionMenu2';
c.append(CollectionMenu2);
import CollectionMenu3 from './collections/menu/CollectionMenu3';
c.append(CollectionMenu3);
import CollectionMenu4 from './collections/menu/CollectionMenu4';
c.append(CollectionMenu4);
import CollectionMenuFitted1 from './collections/menu/CollectionMenuFitted1';
c.append(CollectionMenuFitted1);
import CollectionMenuBorderless1 from './collections/menu/CollectionMenuBorderless1';
c.append(CollectionMenuBorderless1);
b.append(['menu', c]); c = [];
// end of element [menu]
// begin of element [message]
import CollectionMessageMessage1 from './collections/message/CollectionMessageMessage1';
c.append(CollectionMessageMessage1);
import CollectionMessageListMessage1 from './collections/message/CollectionMessageListMessage1';
c.append(CollectionMessageListMessage1);
import CollectionMessageIconMessage1 from './collections/message/CollectionMessageIconMessage1';
c.append(CollectionMessageIconMessage1);
import CollectionMessageIconMessage2 from './collections/message/CollectionMessageIconMessage2';
c.append(CollectionMessageIconMessage2);
import CollectionMessageDismissableBlock1 from './collections/message/CollectionMessageDismissableBlock1';
c.append(CollectionMessageDismissableBlock1);
import CollectionMessageHidden1 from './collections/message/CollectionMessageHidden1';
c.append(CollectionMessageHidden1);
import CollectionMessageVisible1 from './collections/message/CollectionMessageVisible1';
c.append(CollectionMessageVisible1);
import CollectionMessageFloating1 from './collections/message/CollectionMessageFloating1';
c.append(CollectionMessageFloating1);
import CollectionMessageCompact1 from './collections/message/CollectionMessageCompact1';
c.append(CollectionMessageCompact1);
import CollectionMessageAttached1 from './collections/message/CollectionMessageAttached1';
c.append(CollectionMessageAttached1);
import CollectionMessageWarning1 from './collections/message/CollectionMessageWarning1';
c.append(CollectionMessageWarning1);
import CollectionMessageInfo1 from './collections/message/CollectionMessageInfo1';
c.append(CollectionMessageInfo1);
import CollectionMessagePositiveSuccess1 from './collections/message/CollectionMessagePositiveSuccess1';
c.append(CollectionMessagePositiveSuccess1);
import CollectionMessagePositiveSuccess2 from './collections/message/CollectionMessagePositiveSuccess2';
c.append(CollectionMessagePositiveSuccess2);
import CollectionMessageNegativeError1 from './collections/message/CollectionMessageNegativeError1';
c.append(CollectionMessageNegativeError1);
import CollectionMessageNegativeError2 from './collections/message/CollectionMessageNegativeError2';
c.append(CollectionMessageNegativeError2);
import CollectionMessageColored1 from './collections/message/CollectionMessageColored1';
c.append(CollectionMessageColored1);
import CollectionMessageSize1 from './collections/message/CollectionMessageSize1';
c.append(CollectionMessageSize1);
b.append(['message', c]); c = [];
// end of element [message]
// begin of element [table]
import CollectionTableTable1 from './collections/table/CollectionTableTable1';
c.append(CollectionTableTable1);
import CollectionTableTable2 from './collections/table/CollectionTableTable2';
c.append(CollectionTableTable2);
import CollectionTableTable3 from './collections/table/CollectionTableTable3';
c.append(CollectionTableTable3);
import CollectionTableTable4 from './collections/table/CollectionTableTable4';
c.append(CollectionTableTable4);
import CollectionTableDefinition1 from './collections/table/CollectionTableDefinition1';
c.append(CollectionTableDefinition1);
import CollectionTableDefinition2 from './collections/table/CollectionTableDefinition2';
c.append(CollectionTableDefinition2);
import CollectionTableStructured1 from './collections/table/CollectionTableStructured1';
c.append(CollectionTableStructured1);
import CollectionTablePositiveNegative1 from './collections/table/CollectionTablePositiveNegative1';
c.append(CollectionTablePositiveNegative1);
import CollectionTableError1 from './collections/table/CollectionTableError1';
c.append(CollectionTableError1);
import CollectionTableWarning1 from './collections/table/CollectionTableWarning1';
c.append(CollectionTableWarning1);
import CollectionTableActive1 from './collections/table/CollectionTableActive1';
c.append(CollectionTableActive1);
import CollectionTableDisabled1 from './collections/table/CollectionTableDisabled1';
c.append(CollectionTableDisabled1);
import CollectionTableColoredCells1 from './collections/table/CollectionTableColoredCells1';
c.append(CollectionTableColoredCells1);
import CollectionTableSingleLine1 from './collections/table/CollectionTableSingleLine1';
c.append(CollectionTableSingleLine1);
import CollectionTableFixed1 from './collections/table/CollectionTableFixed1';
c.append(CollectionTableFixed1);
import CollectionTableFixed2 from './collections/table/CollectionTableFixed2';
c.append(CollectionTableFixed2);
import CollectionTableStacking1 from './collections/table/CollectionTableStacking1';
c.append(CollectionTableStacking1);
import CollectionTableSelectableRow1 from './collections/table/CollectionTableSelectableRow1';
c.append(CollectionTableSelectableRow1);
import CollectionTableSelectableRow2 from './collections/table/CollectionTableSelectableRow2';
c.append(CollectionTableSelectableRow2);
import CollectionTableSelectableCell1 from './collections/table/CollectionTableSelectableCell1';
c.append(CollectionTableSelectableCell1);
import CollectionTableVerticalAlignment1 from './collections/table/CollectionTableVerticalAlignment1';
c.append(CollectionTableVerticalAlignment1);
import CollectionTableTextAlignment1 from './collections/table/CollectionTableTextAlignment1';
c.append(CollectionTableTextAlignment1);
import CollectionTableStriped1 from './collections/table/CollectionTableStriped1';
c.append(CollectionTableStriped1);
import CollectionTableCelled1 from './collections/table/CollectionTableCelled1';
c.append(CollectionTableCelled1);
import CollectionTableBasic1 from './collections/table/CollectionTableBasic1';
c.append(CollectionTableBasic1);
import CollectionTableBasic2 from './collections/table/CollectionTableBasic2';
c.append(CollectionTableBasic2);
import CollectionTableCollapsingCell1 from './collections/table/CollectionTableCollapsingCell1';
c.append(CollectionTableCollapsingCell1);
import CollectionTableColumnCount1 from './collections/table/CollectionTableColumnCount1';
c.append(CollectionTableColumnCount1);
import CollectionTableColumnWidth1 from './collections/table/CollectionTableColumnWidth1';
c.append(CollectionTableColumnWidth1);
import CollectionTableCollapsing1 from './collections/table/CollectionTableCollapsing1';
c.append(CollectionTableCollapsing1);
import CollectionTableColored1 from './collections/table/CollectionTableColored1';
c.append(CollectionTableColored1);
import CollectionTableInverted1 from './collections/table/CollectionTableInverted1';
c.append(CollectionTableInverted1);
import CollectionTableInverted2 from './collections/table/CollectionTableInverted2';
c.append(CollectionTableInverted2);
import CollectionTableSortable1 from './collections/table/CollectionTableSortable1';
c.append(CollectionTableSortable1);
import CollectionTableFullWidthHeaderFooter1 from './collections/table/CollectionTableFullWidthHeaderFooter1';
c.append(CollectionTableFullWidthHeaderFooter1);
import CollectionTablePadded1 from './collections/table/CollectionTablePadded1';
c.append(CollectionTablePadded1);
import CollectionTablePadded2 from './collections/table/CollectionTablePadded2';
c.append(CollectionTablePadded2);
import CollectionTableCompact1 from './collections/table/CollectionTableCompact1';
c.append(CollectionTableCompact1);
import CollectionTableCompact2 from './collections/table/CollectionTableCompact2';
c.append(CollectionTableCompact2);
import CollectionTableSize1 from './collections/table/CollectionTableSize1';
c.append(CollectionTableSize1);
import CollectionTableSize2 from './collections/table/CollectionTableSize2';
c.append(CollectionTableSize2);
b.append(['table', c]); c = [];
// end of element [table]
a.append(['collections', b]); b = [];
// end of element type [collections]
// begin of element type [views]
// begin of element [advertisement]
import ViewAdvertisementAd1 from './views/advertisement/ViewAdvertisementAd1';
c.append(ViewAdvertisementAd1);
import ViewAdvertisementCommonUnits1 from './views/advertisement/ViewAdvertisementCommonUnits1';
c.append(ViewAdvertisementCommonUnits1);
import ViewAdvertisementMobile1 from './views/advertisement/ViewAdvertisementMobile1';
c.append(ViewAdvertisementMobile1);
import ViewAdvertisementRectangle1 from './views/advertisement/ViewAdvertisementRectangle1';
c.append(ViewAdvertisementRectangle1);
import ViewAdvertisementButton1 from './views/advertisement/ViewAdvertisementButton1';
c.append(ViewAdvertisementButton1);
import ViewAdvertisementSkyscraper1 from './views/advertisement/ViewAdvertisementSkyscraper1';
c.append(ViewAdvertisementSkyscraper1);
import ViewAdvertisementBanner1 from './views/advertisement/ViewAdvertisementBanner1';
c.append(ViewAdvertisementBanner1);
import ViewAdvertisementLeaderboards1 from './views/advertisement/ViewAdvertisementLeaderboards1';
c.append(ViewAdvertisementLeaderboards1);
import ViewAdvertisementPanorama1 from './views/advertisement/ViewAdvertisementPanorama1';
c.append(ViewAdvertisementPanorama1);
import ViewAdvertisementNetboard1 from './views/advertisement/ViewAdvertisementNetboard1';
c.append(ViewAdvertisementNetboard1);
import ViewAdvertisementCentered1 from './views/advertisement/ViewAdvertisementCentered1';
c.append(ViewAdvertisementCentered1);
import ViewAdvertisementTest1 from './views/advertisement/ViewAdvertisementTest1';
c.append(ViewAdvertisementTest1);
b.append(['advertisement', c]); c = [];
// end of element [advertisement]
// begin of element [card]
import ViewCardCard1 from './views/card/ViewCardCard1';
c.append(ViewCardCard1);
import ViewCardCard2 from './views/card/ViewCardCard2';
c.append(ViewCardCard2);
import ViewCardCards1 from './views/card/ViewCardCards1';
c.append(ViewCardCards1);
import ViewCardCards2 from './views/card/ViewCardCards2';
c.append(ViewCardCards2);
import ViewCardContentBlock1 from './views/card/ViewCardContentBlock1';
c.append(ViewCardContentBlock1);
import ViewCardImage1 from './views/card/ViewCardImage1';
c.append(ViewCardImage1);
import ViewCardImage2 from './views/card/ViewCardImage2';
c.append(ViewCardImage2);
import ViewCardHeader1 from './views/card/ViewCardHeader1';
c.append(ViewCardHeader1);
import ViewCardMetadata1 from './views/card/ViewCardMetadata1';
c.append(ViewCardMetadata1);
import ViewCardLink1 from './views/card/ViewCardLink1';
c.append(ViewCardLink1);
import ViewCardButtons1 from './views/card/ViewCardButtons1';
c.append(ViewCardButtons1);
import ViewCardApproval1 from './views/card/ViewCardApproval1';
c.append(ViewCardApproval1);
import ViewCardDescription1 from './views/card/ViewCardDescription1';
c.append(ViewCardDescription1);
import ViewCardExtraContent1 from './views/card/ViewCardExtraContent1';
c.append(ViewCardExtraContent1);
import ViewCardFluidCard1 from './views/card/ViewCardFluidCard1';
c.append(ViewCardFluidCard1);
import ViewCardCenteredCard1 from './views/card/ViewCardCenteredCard1';
c.append(ViewCardCenteredCard1);
import ViewCardHorizontalCards1 from './views/card/ViewCardHorizontalCards1';
c.append(ViewCardHorizontalCards1);
import ViewCardHorizontalCards2 from './views/card/ViewCardHorizontalCards2';
c.append(ViewCardHorizontalCards2);
import ViewCardRaisedCard1 from './views/card/ViewCardRaisedCard1';
c.append(ViewCardRaisedCard1);
import ViewCardRaisedCard2 from './views/card/ViewCardRaisedCard2';
c.append(ViewCardRaisedCard2);
import ViewCardLinkCard1 from './views/card/ViewCardLinkCard1';
c.append(ViewCardLinkCard1);
import ViewCardLinkCard2 from './views/card/ViewCardLinkCard2';
c.append(ViewCardLinkCard2);
import ViewCardFloatedContent1 from './views/card/ViewCardFloatedContent1';
c.append(ViewCardFloatedContent1);
import ViewCardTextAlignment1 from './views/card/ViewCardTextAlignment1';
c.append(ViewCardTextAlignment1);
import ViewCardInverted1 from './views/card/ViewCardInverted1';
c.append(ViewCardInverted1);
import ViewCardColored1 from './views/card/ViewCardColored1';
c.append(ViewCardColored1);
import ViewCardColumnCount1 from './views/card/ViewCardColumnCount1';
c.append(ViewCardColumnCount1);
import ViewCardStackable1 from './views/card/ViewCardStackable1';
c.append(ViewCardStackable1);
import ViewCardDoubling1 from './views/card/ViewCardDoubling1';
c.append(ViewCardDoubling1);
b.append(['card', c]); c = [];
// end of element [card]
// begin of element [comment]
import ViewCommentComments1 from './views/comment/ViewCommentComments1';
c.append(ViewCommentComments1);
import ViewCommentAvatar1 from './views/comment/ViewCommentAvatar1';
c.append(ViewCommentAvatar1);
import ViewCommentMetadata1 from './views/comment/ViewCommentMetadata1';
c.append(ViewCommentMetadata1);
import ViewCommentActions1 from './views/comment/ViewCommentActions1';
c.append(ViewCommentActions1);
import ViewCommentReplyForm1 from './views/comment/ViewCommentReplyForm1';
c.append(ViewCommentReplyForm1);
import ViewCommentReplyForm2 from './views/comment/ViewCommentReplyForm2';
c.append(ViewCommentReplyForm2);
import ViewCommentCollapsed1 from './views/comment/ViewCommentCollapsed1';
c.append(ViewCommentCollapsed1);
import ViewCommentThreaded1 from './views/comment/ViewCommentThreaded1';
c.append(ViewCommentThreaded1);
import ViewCommentMinimal1 from './views/comment/ViewCommentMinimal1';
c.append(ViewCommentMinimal1);
import ViewCommentSize1 from './views/comment/ViewCommentSize1';
c.append(ViewCommentSize1);
import ViewCommentSize2 from './views/comment/ViewCommentSize2';
c.append(ViewCommentSize2);
import ViewCommentInverted1 from './views/comment/ViewCommentInverted1';
c.append(ViewCommentInverted1);
b.append(['comment', c]); c = [];
// end of element [comment]
// begin of element [feed]
import ViewFeedFeed1 from './views/feed/ViewFeedFeed1';
c.append(ViewFeedFeed1);
import ViewFeedLabel1 from './views/feed/ViewFeedLabel1';
c.append(ViewFeedLabel1);
import ViewFeedLabel2 from './views/feed/ViewFeedLabel2';
c.append(ViewFeedLabel2);
import ViewFeedDate1 from './views/feed/ViewFeedDate1';
c.append(ViewFeedDate1);
import ViewFeedDate2 from './views/feed/ViewFeedDate2';
c.append(ViewFeedDate2);
import ViewFeedAdditionalinformation1 from './views/feed/ViewFeedAdditionalinformation1';
c.append(ViewFeedAdditionalinformation1);
import ViewFeedSize1 from './views/feed/ViewFeedSize1';
c.append(ViewFeedSize1);
import ViewFeedSize2 from './views/feed/ViewFeedSize2';
c.append(ViewFeedSize2);
b.append(['feed', c]); c = [];
// end of element [feed]
// begin of element [item]
import ViewItemItems1 from './views/item/ViewItemItems1';
c.append(ViewItemItems1);
import ViewItemImage1 from './views/item/ViewItemImage1';
c.append(ViewItemImage1);
import ViewItemContent1 from './views/item/ViewItemContent1';
c.append(ViewItemContent1);
import ViewItemHeader1 from './views/item/ViewItemHeader1';
c.append(ViewItemHeader1);
import ViewItemMetadata1 from './views/item/ViewItemMetadata1';
c.append(ViewItemMetadata1);
import ViewItemLink1 from './views/item/ViewItemLink1';
c.append(ViewItemLink1);
import ViewItemDescription1 from './views/item/ViewItemDescription1';
c.append(ViewItemDescription1);
import ViewItemExtraContent1 from './views/item/ViewItemExtraContent1';
c.append(ViewItemExtraContent1);
import ViewItemRating1 from './views/item/ViewItemRating1';
c.append(ViewItemRating1);
import ViewItemStacking1 from './views/item/ViewItemStacking1';
c.append(ViewItemStacking1);
import ViewItemDivided1 from './views/item/ViewItemDivided1';
c.append(ViewItemDivided1);
import ViewItemRelaxed1 from './views/item/ViewItemRelaxed1';
c.append(ViewItemRelaxed1);
import ViewItemRelaxed2 from './views/item/ViewItemRelaxed2';
c.append(ViewItemRelaxed2);
import ViewItemLinkItem1 from './views/item/ViewItemLinkItem1';
c.append(ViewItemLinkItem1);
import ViewItemVerticalAlignment1 from './views/item/ViewItemVerticalAlignment1';
c.append(ViewItemVerticalAlignment1);
import ViewItemFloatedContent1 from './views/item/ViewItemFloatedContent1';
c.append(ViewItemFloatedContent1);
import ViewItemInverted1 from './views/item/ViewItemInverted1';
c.append(ViewItemInverted1);
b.append(['item', c]); c = [];
// end of element [item]
// begin of element [statistic]
import ViewStatisticStatistic1 from './views/statistic/ViewStatisticStatistic1';
c.append(ViewStatisticStatistic1);
import ViewStatisticStatistic2 from './views/statistic/ViewStatisticStatistic2';
c.append(ViewStatisticStatistic2);
import ViewStatisticStatisticGroup1 from './views/statistic/ViewStatisticStatisticGroup1';
c.append(ViewStatisticStatisticGroup1);
import ViewStatisticValue1 from './views/statistic/ViewStatisticValue1';
c.append(ViewStatisticValue1);
import ViewStatisticLabel1 from './views/statistic/ViewStatisticLabel1';
c.append(ViewStatisticLabel1);
import ViewStatisticHorizontalStatistic1 from './views/statistic/ViewStatisticHorizontalStatistic1';
c.append(ViewStatisticHorizontalStatistic1);
import ViewStatisticHorizontalStatistic2 from './views/statistic/ViewStatisticHorizontalStatistic2';
c.append(ViewStatisticHorizontalStatistic2);
import ViewStatisticColored1 from './views/statistic/ViewStatisticColored1';
c.append(ViewStatisticColored1);
import ViewStatisticInverted1 from './views/statistic/ViewStatisticInverted1';
c.append(ViewStatisticInverted1);
import ViewStatisticStackable1 from './views/statistic/ViewStatisticStackable1';
c.append(ViewStatisticStackable1);
import ViewStatisticEvenlyDivided1 from './views/statistic/ViewStatisticEvenlyDivided1';
c.append(ViewStatisticEvenlyDivided1);
import ViewStatisticFloated1 from './views/statistic/ViewStatisticFloated1';
c.append(ViewStatisticFloated1);
import ViewStatisticSize1 from './views/statistic/ViewStatisticSize1';
c.append(ViewStatisticSize1);
import ViewStatisticSize2 from './views/statistic/ViewStatisticSize2';
c.append(ViewStatisticSize2);
b.append(['statistic', c]); c = [];
// end of element [statistic]
a.append(['views', b]); b = [];
// end of element type [views]
export default a;
