<template>
  <div>
    <div class="ui form">
      <div class="field">
        <label>Country</label>
        <select multiple="multiple" class="ui dropdown">
          <option value="">Select Country</option>
          <option value="AF">Afghanistan</option>
          <option value="AX">Åland Islands</option>
          <option value="AL">Albania</option>
          <option value="DZ">Algeria</option>
          <option value="AS">American Samoa</option>
          <option value="AD">Andorra</option>
          <option value="AO">Angola</option>
          <option value="AI">Anguilla</option>
          <option value="AQ">Antarctica</option>
          <option value="AG">Antigua and Barbuda</option>
          <option value="AR">Argentina</option>
          <option value="AM">Armenia</option>
          <option value="AW">Aruba</option>
          <option value="AU">Australia</option>
          <option value="AT">Austria</option>
          <option value="AZ">Azerbaijan</option>
          <option value="BS">Bahamas</option>
          <option value="BH">Bahrain</option>
          <option value="BD">Bangladesh</option>
          <option value="BB">Barbados</option>
          <option value="BY">Belarus</option>
          <option value="BE">Belgium</option>
          <option value="BZ">Belize</option>
          <option value="BJ">Benin</option>
          <option value="BM">Bermuda</option>
          <option value="BT">Bhutan</option>
          <option value="BO">Bolivia, Plurinational State of</option>
          <option value="BQ">Bonaire, Sint Eustatius and Saba</option>
          <option value="BA">Bosnia and Herzegovina</option>
          <option value="BW">Botswana</option>
          <option value="BV">Bouvet Island</option>
          <option value="BR">Brazil</option>
          <option value="IO">British Indian Ocean Territory</option>
          <option value="BN">Brunei Darussalam</option>
          <option value="BG">Bulgaria</option>
          <option value="BF">Burkina Faso</option>
          <option value="BI">Burundi</option>
          <option value="KH">Cambodia</option>
          <option value="CM">Cameroon</option>
          <option value="CA">Canada</option>
          <option value="CV">Cape Verde</option>
          <option value="KY">Cayman Islands</option>
          <option value="CF">Central African Republic</option>
          <option value="TD">Chad</option>
          <option value="CL">Chile</option>
          <option value="CN">China</option>
          <option value="CX">Christmas Island</option>
          <option value="CC">Cocos (Keeling) Islands</option>
          <option value="CO">Colombia</option>
          <option value="KM">Comoros</option>
          <option value="CG">Congo</option>
          <option value="CD">Congo, the Democratic Republic of the</option>
          <option value="CK">Cook Islands</option>
          <option value="CR">Costa Rica</option>
          <option value="CI">Côte d'Ivoire</option>
          <option value="HR">Croatia</option>
          <option value="CU">Cuba</option>
          <option value="CW">Curaçao</option>
          <option value="CY">Cyprus</option>
          <option value="CZ">Czech Republic</option>
          <option value="DK">Denmark</option>
          <option value="DJ">Djibouti</option>
          <option value="DM">Dominica</option>
          <option value="DO">Dominican Republic</option>
          <option value="EC">Ecuador</option>
          <option value="EG">Egypt</option>
          <option value="SV">El Salvador</option>
          <option value="GQ">Equatorial Guinea</option>
          <option value="ER">Eritrea</option>
          <option value="EE">Estonia</option>
          <option value="ET">Ethiopia</option>
          <option value="FK">Falkland Islands (Malvinas)</option>
          <option value="FO">Faroe Islands</option>
          <option value="FJ">Fiji</option>
          <option value="FI">Finland</option>
          <option value="FR">France</option>
          <option value="GF">French Guiana</option>
          <option value="PF">French Polynesia</option>
          <option value="TF">French Southern Territories</option>
          <option value="GA">Gabon</option>
          <option value="GM">Gambia</option>
          <option value="GE">Georgia</option>
          <option value="DE">Germany</option>
          <option value="GH">Ghana</option>
          <option value="GI">Gibraltar</option>
          <option value="GR">Greece</option>
          <option value="GL">Greenland</option>
          <option value="GD">Grenada</option>
          <option value="GP">Guadeloupe</option>
          <option value="GU">Guam</option>
          <option value="GT">Guatemala</option>
          <option value="GG">Guernsey</option>
          <option value="GN">Guinea</option>
          <option value="GW">Guinea-Bissau</option>
          <option value="GY">Guyana</option>
          <option value="HT">Haiti</option>
          <option value="HM">Heard Island and McDonald Islands</option>
          <option value="VA">Holy See (Vatican City State)</option>
          <option value="HN">Honduras</option>
          <option value="HK">Hong Kong</option>
          <option value="HU">Hungary</option>
          <option value="IS">Iceland</option>
          <option value="IN">India</option>
          <option value="ID">Indonesia</option>
          <option value="IR">Iran, Islamic Republic of</option>
          <option value="IQ">Iraq</option>
          <option value="IE">Ireland</option>
          <option value="IM">Isle of Man</option>
          <option value="IL">Israel</option>
          <option value="IT">Italy</option>
          <option value="JM">Jamaica</option>
          <option value="JP">Japan</option>
          <option value="JE">Jersey</option>
          <option value="JO">Jordan</option>
          <option value="KZ">Kazakhstan</option>
          <option value="KE">Kenya</option>
          <option value="KI">Kiribati</option>
          <option value="KP">Korea, Democratic People's Republic of</option>
          <option value="KR">Korea, Republic of</option>
          <option value="KW">Kuwait</option>
          <option value="KG">Kyrgyzstan</option>
          <option value="LA">Lao People's Democratic Republic</option>
          <option value="LV">Latvia</option>
          <option value="LB">Lebanon</option>
          <option value="LS">Lesotho</option>
          <option value="LR">Liberia</option>
          <option value="LY">Libya</option>
          <option value="LI">Liechtenstein</option>
          <option value="LT">Lithuania</option>
          <option value="LU">Luxembourg</option>
          <option value="MO">Macao</option>
          <option value="MK">Macedonia, the former Yugoslav Republic of</option>
          <option value="MG">Madagascar</option>
          <option value="MW">Malawi</option>
          <option value="MY">Malaysia</option>
          <option value="MV">Maldives</option>
          <option value="ML">Mali</option>
          <option value="MT">Malta</option>
          <option value="MH">Marshall Islands</option>
          <option value="MQ">Martinique</option>
          <option value="MR">Mauritania</option>
          <option value="MU">Mauritius</option>
          <option value="YT">Mayotte</option>
          <option value="MX">Mexico</option>
          <option value="FM">Micronesia, Federated States of</option>
          <option value="MD">Moldova, Republic of</option>
          <option value="MC">Monaco</option>
          <option value="MN">Mongolia</option>
          <option value="ME">Montenegro</option>
          <option value="MS">Montserrat</option>
          <option value="MA">Morocco</option>
          <option value="MZ">Mozambique</option>
          <option value="MM">Myanmar</option>
          <option value="NA">Namibia</option>
          <option value="NR">Nauru</option>
          <option value="NP">Nepal</option>
          <option value="NL">Netherlands</option>
          <option value="NC">New Caledonia</option>
          <option value="NZ">New Zealand</option>
          <option value="NI">Nicaragua</option>
          <option value="NE">Niger</option>
          <option value="NG">Nigeria</option>
          <option value="NU">Niue</option>
          <option value="NF">Norfolk Island</option>
          <option value="MP">Northern Mariana Islands</option>
          <option value="NO">Norway</option>
          <option value="OM">Oman</option>
          <option value="PK">Pakistan</option>
          <option value="PW">Palau</option>
          <option value="PS">Palestinian Territory, Occupied</option>
          <option value="PA">Panama</option>
          <option value="PG">Papua New Guinea</option>
          <option value="PY">Paraguay</option>
          <option value="PE">Peru</option>
          <option value="PH">Philippines</option>
          <option value="PN">Pitcairn</option>
          <option value="PL">Poland</option>
          <option value="PT">Portugal</option>
          <option value="PR">Puerto Rico</option>
          <option value="QA">Qatar</option>
          <option value="RE">Réunion</option>
          <option value="RO">Romania</option>
          <option value="RU">Russian Federation</option>
          <option value="RW">Rwanda</option>
          <option value="BL">Saint Barthélemy</option>
          <option value="SH">Saint Helena, Ascension and Tristan da Cunha</option>
          <option value="KN">Saint Kitts and Nevis</option>
          <option value="LC">Saint Lucia</option>
          <option value="MF">Saint Martin (French part)</option>
          <option value="PM">Saint Pierre and Miquelon</option>
          <option value="VC">Saint Vincent and the Grenadines</option>
          <option value="WS">Samoa</option>
          <option value="SM">San Marino</option>
          <option value="ST">Sao Tome and Principe</option>
          <option value="SA">Saudi Arabia</option>
          <option value="SN">Senegal</option>
          <option value="RS">Serbia</option>
          <option value="SC">Seychelles</option>
          <option value="SL">Sierra Leone</option>
          <option value="SG">Singapore</option>
          <option value="SX">Sint Maarten (Dutch part)</option>
          <option value="SK">Slovakia</option>
          <option value="SI">Slovenia</option>
          <option value="SB">Solomon Islands</option>
          <option value="SO">Somalia</option>
          <option value="ZA">South Africa</option>
          <option value="GS">South Georgia and the South Sandwich Islands</option>
          <option value="SS">South Sudan</option>
          <option value="ES">Spain</option>
          <option value="LK">Sri Lanka</option>
          <option value="SD">Sudan</option>
          <option value="SR">Suriname</option>
          <option value="SJ">Svalbard and Jan Mayen</option>
          <option value="SZ">Swaziland</option>
          <option value="SE">Sweden</option>
          <option value="CH">Switzerland</option>
          <option value="SY">Syrian Arab Republic</option>
          <option value="TW">Taiwan, Province of China</option>
          <option value="TJ">Tajikistan</option>
          <option value="TZ">Tanzania, United Republic of</option>
          <option value="TH">Thailand</option>
          <option value="TL">Timor-Leste</option>
          <option value="TG">Togo</option>
          <option value="TK">Tokelau</option>
          <option value="TO">Tonga</option>
          <option value="TT">Trinidad and Tobago</option>
          <option value="TN">Tunisia</option>
          <option value="TR">Turkey</option>
          <option value="TM">Turkmenistan</option>
          <option value="TC">Turks and Caicos Islands</option>
          <option value="TV">Tuvalu</option>
          <option value="UG">Uganda</option>
          <option value="UA">Ukraine</option>
          <option value="AE">United Arab Emirates</option>
          <option value="GB">United Kingdom</option>
          <option value="US">United States</option>
          <option value="UM">United States Minor Outlying Islands</option>
          <option value="UY">Uruguay</option>
          <option value="UZ">Uzbekistan</option>
          <option value="VU">Vanuatu</option>
          <option value="VE">Venezuela, Bolivarian Republic of</option>
          <option value="VN">Viet Nam</option>
          <option value="VG">Virgin Islands, British</option>
          <option value="VI">Virgin Islands, U.S.</option>
          <option value="WF">Wallis and Futuna</option>
          <option value="EH">Western Sahara</option>
          <option value="YE">Yemen</option>
          <option value="ZM">Zambia</option>
          <option value="ZW">Zimbabwe</option>
        </select>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'CollectionFormMultipleSelect1',
  info: {
    converted: false,
    elementType: 'collections',
    element: 'form',
    title1: 'Content',
    title2: 'Multiple Select',
    description: 'A',
    model: '    <div class="ui form">\n' +
      '      <div class="field">\n' +
      '        <label>Country</label>\n' +
      '        <select multiple="multiple" class="ui dropdown">\n' +
      '          <option value="">Select Country</option>\n' +
      '          <option value="AF">Afghanistan</option>\n' +
      '          <option value="AX">Åland Islands</option>\n' +
      '          <option value="AL">Albania</option>\n' +
      '          <option value="DZ">Algeria</option>\n' +
      '          <option value="AS">American Samoa</option>\n' +
      '          <option value="AD">Andorra</option>\n' +
      '          <option value="AO">Angola</option>\n' +
      '          <option value="AI">Anguilla</option>\n' +
      '          <option value="AQ">Antarctica</option>\n' +
      '          <option value="AG">Antigua and Barbuda</option>\n' +
      '          <option value="AR">Argentina</option>\n' +
      '          <option value="AM">Armenia</option>\n' +
      '          <option value="AW">Aruba</option>\n' +
      '          <option value="AU">Australia</option>\n' +
      '          <option value="AT">Austria</option>\n' +
      '          <option value="AZ">Azerbaijan</option>\n' +
      '          <option value="BS">Bahamas</option>\n' +
      '          <option value="BH">Bahrain</option>\n' +
      '          <option value="BD">Bangladesh</option>\n' +
      '          <option value="BB">Barbados</option>\n' +
      '          <option value="BY">Belarus</option>\n' +
      '          <option value="BE">Belgium</option>\n' +
      '          <option value="BZ">Belize</option>\n' +
      '          <option value="BJ">Benin</option>\n' +
      '          <option value="BM">Bermuda</option>\n' +
      '          <option value="BT">Bhutan</option>\n' +
      '          <option value="BO">Bolivia, Plurinational State of</option>\n' +
      '          <option value="BQ">Bonaire, Sint Eustatius and Saba</option>\n' +
      '          <option value="BA">Bosnia and Herzegovina</option>\n' +
      '          <option value="BW">Botswana</option>\n' +
      '          <option value="BV">Bouvet Island</option>\n' +
      '          <option value="BR">Brazil</option>\n' +
      '          <option value="IO">British Indian Ocean Territory</option>\n' +
      '          <option value="BN">Brunei Darussalam</option>\n' +
      '          <option value="BG">Bulgaria</option>\n' +
      '          <option value="BF">Burkina Faso</option>\n' +
      '          <option value="BI">Burundi</option>\n' +
      '          <option value="KH">Cambodia</option>\n' +
      '          <option value="CM">Cameroon</option>\n' +
      '          <option value="CA">Canada</option>\n' +
      '          <option value="CV">Cape Verde</option>\n' +
      '          <option value="KY">Cayman Islands</option>\n' +
      '          <option value="CF">Central African Republic</option>\n' +
      '          <option value="TD">Chad</option>\n' +
      '          <option value="CL">Chile</option>\n' +
      '          <option value="CN">China</option>\n' +
      '          <option value="CX">Christmas Island</option>\n' +
      '          <option value="CC">Cocos (Keeling) Islands</option>\n' +
      '          <option value="CO">Colombia</option>\n' +
      '          <option value="KM">Comoros</option>\n' +
      '          <option value="CG">Congo</option>\n' +
      '          <option value="CD">Congo, the Democratic Republic of the</option>\n' +
      '          <option value="CK">Cook Islands</option>\n' +
      '          <option value="CR">Costa Rica</option>\n' +
      '          <option value="CI">Côte d\'Ivoire</option>\n' +
      '          <option value="HR">Croatia</option>\n' +
      '          <option value="CU">Cuba</option>\n' +
      '          <option value="CW">Curaçao</option>\n' +
      '          <option value="CY">Cyprus</option>\n' +
      '          <option value="CZ">Czech Republic</option>\n' +
      '          <option value="DK">Denmark</option>\n' +
      '          <option value="DJ">Djibouti</option>\n' +
      '          <option value="DM">Dominica</option>\n' +
      '          <option value="DO">Dominican Republic</option>\n' +
      '          <option value="EC">Ecuador</option>\n' +
      '          <option value="EG">Egypt</option>\n' +
      '          <option value="SV">El Salvador</option>\n' +
      '          <option value="GQ">Equatorial Guinea</option>\n' +
      '          <option value="ER">Eritrea</option>\n' +
      '          <option value="EE">Estonia</option>\n' +
      '          <option value="ET">Ethiopia</option>\n' +
      '          <option value="FK">Falkland Islands (Malvinas)</option>\n' +
      '          <option value="FO">Faroe Islands</option>\n' +
      '          <option value="FJ">Fiji</option>\n' +
      '          <option value="FI">Finland</option>\n' +
      '          <option value="FR">France</option>\n' +
      '          <option value="GF">French Guiana</option>\n' +
      '          <option value="PF">French Polynesia</option>\n' +
      '          <option value="TF">French Southern Territories</option>\n' +
      '          <option value="GA">Gabon</option>\n' +
      '          <option value="GM">Gambia</option>\n' +
      '          <option value="GE">Georgia</option>\n' +
      '          <option value="DE">Germany</option>\n' +
      '          <option value="GH">Ghana</option>\n' +
      '          <option value="GI">Gibraltar</option>\n' +
      '          <option value="GR">Greece</option>\n' +
      '          <option value="GL">Greenland</option>\n' +
      '          <option value="GD">Grenada</option>\n' +
      '          <option value="GP">Guadeloupe</option>\n' +
      '          <option value="GU">Guam</option>\n' +
      '          <option value="GT">Guatemala</option>\n' +
      '          <option value="GG">Guernsey</option>\n' +
      '          <option value="GN">Guinea</option>\n' +
      '          <option value="GW">Guinea-Bissau</option>\n' +
      '          <option value="GY">Guyana</option>\n' +
      '          <option value="HT">Haiti</option>\n' +
      '          <option value="HM">Heard Island and McDonald Islands</option>\n' +
      '          <option value="VA">Holy See (Vatican City State)</option>\n' +
      '          <option value="HN">Honduras</option>\n' +
      '          <option value="HK">Hong Kong</option>\n' +
      '          <option value="HU">Hungary</option>\n' +
      '          <option value="IS">Iceland</option>\n' +
      '          <option value="IN">India</option>\n' +
      '          <option value="ID">Indonesia</option>\n' +
      '          <option value="IR">Iran, Islamic Republic of</option>\n' +
      '          <option value="IQ">Iraq</option>\n' +
      '          <option value="IE">Ireland</option>\n' +
      '          <option value="IM">Isle of Man</option>\n' +
      '          <option value="IL">Israel</option>\n' +
      '          <option value="IT">Italy</option>\n' +
      '          <option value="JM">Jamaica</option>\n' +
      '          <option value="JP">Japan</option>\n' +
      '          <option value="JE">Jersey</option>\n' +
      '          <option value="JO">Jordan</option>\n' +
      '          <option value="KZ">Kazakhstan</option>\n' +
      '          <option value="KE">Kenya</option>\n' +
      '          <option value="KI">Kiribati</option>\n' +
      '          <option value="KP">Korea, Democratic People\'s Republic of</option>\n' +
      '          <option value="KR">Korea, Republic of</option>\n' +
      '          <option value="KW">Kuwait</option>\n' +
      '          <option value="KG">Kyrgyzstan</option>\n' +
      '          <option value="LA">Lao People\'s Democratic Republic</option>\n' +
      '          <option value="LV">Latvia</option>\n' +
      '          <option value="LB">Lebanon</option>\n' +
      '          <option value="LS">Lesotho</option>\n' +
      '          <option value="LR">Liberia</option>\n' +
      '          <option value="LY">Libya</option>\n' +
      '          <option value="LI">Liechtenstein</option>\n' +
      '          <option value="LT">Lithuania</option>\n' +
      '          <option value="LU">Luxembourg</option>\n' +
      '          <option value="MO">Macao</option>\n' +
      '          <option value="MK">Macedonia, the former Yugoslav Republic of</option>\n' +
      '          <option value="MG">Madagascar</option>\n' +
      '          <option value="MW">Malawi</option>\n' +
      '          <option value="MY">Malaysia</option>\n' +
      '          <option value="MV">Maldives</option>\n' +
      '          <option value="ML">Mali</option>\n' +
      '          <option value="MT">Malta</option>\n' +
      '          <option value="MH">Marshall Islands</option>\n' +
      '          <option value="MQ">Martinique</option>\n' +
      '          <option value="MR">Mauritania</option>\n' +
      '          <option value="MU">Mauritius</option>\n' +
      '          <option value="YT">Mayotte</option>\n' +
      '          <option value="MX">Mexico</option>\n' +
      '          <option value="FM">Micronesia, Federated States of</option>\n' +
      '          <option value="MD">Moldova, Republic of</option>\n' +
      '          <option value="MC">Monaco</option>\n' +
      '          <option value="MN">Mongolia</option>\n' +
      '          <option value="ME">Montenegro</option>\n' +
      '          <option value="MS">Montserrat</option>\n' +
      '          <option value="MA">Morocco</option>\n' +
      '          <option value="MZ">Mozambique</option>\n' +
      '          <option value="MM">Myanmar</option>\n' +
      '          <option value="NA">Namibia</option>\n' +
      '          <option value="NR">Nauru</option>\n' +
      '          <option value="NP">Nepal</option>\n' +
      '          <option value="NL">Netherlands</option>\n' +
      '          <option value="NC">New Caledonia</option>\n' +
      '          <option value="NZ">New Zealand</option>\n' +
      '          <option value="NI">Nicaragua</option>\n' +
      '          <option value="NE">Niger</option>\n' +
      '          <option value="NG">Nigeria</option>\n' +
      '          <option value="NU">Niue</option>\n' +
      '          <option value="NF">Norfolk Island</option>\n' +
      '          <option value="MP">Northern Mariana Islands</option>\n' +
      '          <option value="NO">Norway</option>\n' +
      '          <option value="OM">Oman</option>\n' +
      '          <option value="PK">Pakistan</option>\n' +
      '          <option value="PW">Palau</option>\n' +
      '          <option value="PS">Palestinian Territory, Occupied</option>\n' +
      '          <option value="PA">Panama</option>\n' +
      '          <option value="PG">Papua New Guinea</option>\n' +
      '          <option value="PY">Paraguay</option>\n' +
      '          <option value="PE">Peru</option>\n' +
      '          <option value="PH">Philippines</option>\n' +
      '          <option value="PN">Pitcairn</option>\n' +
      '          <option value="PL">Poland</option>\n' +
      '          <option value="PT">Portugal</option>\n' +
      '          <option value="PR">Puerto Rico</option>\n' +
      '          <option value="QA">Qatar</option>\n' +
      '          <option value="RE">Réunion</option>\n' +
      '          <option value="RO">Romania</option>\n' +
      '          <option value="RU">Russian Federation</option>\n' +
      '          <option value="RW">Rwanda</option>\n' +
      '          <option value="BL">Saint Barthélemy</option>\n' +
      '          <option value="SH">Saint Helena, Ascension and Tristan da Cunha</option>\n' +
      '          <option value="KN">Saint Kitts and Nevis</option>\n' +
      '          <option value="LC">Saint Lucia</option>\n' +
      '          <option value="MF">Saint Martin (French part)</option>\n' +
      '          <option value="PM">Saint Pierre and Miquelon</option>\n' +
      '          <option value="VC">Saint Vincent and the Grenadines</option>\n' +
      '          <option value="WS">Samoa</option>\n' +
      '          <option value="SM">San Marino</option>\n' +
      '          <option value="ST">Sao Tome and Principe</option>\n' +
      '          <option value="SA">Saudi Arabia</option>\n' +
      '          <option value="SN">Senegal</option>\n' +
      '          <option value="RS">Serbia</option>\n' +
      '          <option value="SC">Seychelles</option>\n' +
      '          <option value="SL">Sierra Leone</option>\n' +
      '          <option value="SG">Singapore</option>\n' +
      '          <option value="SX">Sint Maarten (Dutch part)</option>\n' +
      '          <option value="SK">Slovakia</option>\n' +
      '          <option value="SI">Slovenia</option>\n' +
      '          <option value="SB">Solomon Islands</option>\n' +
      '          <option value="SO">Somalia</option>\n' +
      '          <option value="ZA">South Africa</option>\n' +
      '          <option value="GS">South Georgia and the South Sandwich Islands</option>\n' +
      '          <option value="SS">South Sudan</option>\n' +
      '          <option value="ES">Spain</option>\n' +
      '          <option value="LK">Sri Lanka</option>\n' +
      '          <option value="SD">Sudan</option>\n' +
      '          <option value="SR">Suriname</option>\n' +
      '          <option value="SJ">Svalbard and Jan Mayen</option>\n' +
      '          <option value="SZ">Swaziland</option>\n' +
      '          <option value="SE">Sweden</option>\n' +
      '          <option value="CH">Switzerland</option>\n' +
      '          <option value="SY">Syrian Arab Republic</option>\n' +
      '          <option value="TW">Taiwan, Province of China</option>\n' +
      '          <option value="TJ">Tajikistan</option>\n' +
      '          <option value="TZ">Tanzania, United Republic of</option>\n' +
      '          <option value="TH">Thailand</option>\n' +
      '          <option value="TL">Timor-Leste</option>\n' +
      '          <option value="TG">Togo</option>\n' +
      '          <option value="TK">Tokelau</option>\n' +
      '          <option value="TO">Tonga</option>\n' +
      '          <option value="TT">Trinidad and Tobago</option>\n' +
      '          <option value="TN">Tunisia</option>\n' +
      '          <option value="TR">Turkey</option>\n' +
      '          <option value="TM">Turkmenistan</option>\n' +
      '          <option value="TC">Turks and Caicos Islands</option>\n' +
      '          <option value="TV">Tuvalu</option>\n' +
      '          <option value="UG">Uganda</option>\n' +
      '          <option value="UA">Ukraine</option>\n' +
      '          <option value="AE">United Arab Emirates</option>\n' +
      '          <option value="GB">United Kingdom</option>\n' +
      '          <option value="US">United States</option>\n' +
      '          <option value="UM">United States Minor Outlying Islands</option>\n' +
      '          <option value="UY">Uruguay</option>\n' +
      '          <option value="UZ">Uzbekistan</option>\n' +
      '          <option value="VU">Vanuatu</option>\n' +
      '          <option value="VE">Venezuela, Bolivarian Republic of</option>\n' +
      '          <option value="VN">Viet Nam</option>\n' +
      '          <option value="VG">Virgin Islands, British</option>\n' +
      '          <option value="VI">Virgin Islands, U.S.</option>\n' +
      '          <option value="WF">Wallis and Futuna</option>\n' +
      '          <option value="EH">Western Sahara</option>\n' +
      '          <option value="YE">Yemen</option>\n' +
      '          <option value="ZM">Zambia</option>\n' +
      '          <option value="ZW">Zimbabwe</option>\n' +
      '        </select>\n' +
      '      </div>\n' +
      '    </div>\n',
  },
};
</script>
