<template>
  <div>
    Andorra (<FuiFlag country=andorra></FuiFlag>),
    U.A.E (<FuiFlag country=uae></FuiFlag>),
    Afghanistan (<FuiFlag country=afghanistan></FuiFlag>),
    Antigua (<FuiFlag country=antigua></FuiFlag>),
    Anguilla (<FuiFlag country=anguilla></FuiFlag>),
    Albania (<FuiFlag country=albania></FuiFlag>),
    Armenia (<FuiFlag country=armenia></FuiFlag>),
    Netherlands Antilles (<FuiFlag country="netherlands antilles"></FuiFlag>),
    Angola (<FuiFlag country=angola></FuiFlag>),
    Argentina (<FuiFlag country=argentina></FuiFlag>),
    American Samoa (<FuiFlag country="american samoa"></FuiFlag>),
    Austria (<FuiFlag country=austria></FuiFlag>),
    Australia (<FuiFlag country=australia></FuiFlag>),
    Aruba (<FuiFlag country=aruba></FuiFlag>),
    Aland Islands (<FuiFlag country="aland islands"></FuiFlag>),
    Azerbaijan (<FuiFlag country=azerbaijan></FuiFlag>),
    Bosnia (<FuiFlag country=bosnia></FuiFlag>),
    Barbados (<FuiFlag country=barbados></FuiFlag>),
    Bangladesh (<FuiFlag country=bangladesh></FuiFlag>),
    Belgium (<FuiFlag country=belgium></FuiFlag>),
    Burkina Faso (<FuiFlag country="burkina faso"></FuiFlag>),
    Bulgaria (<FuiFlag country=bulgaria></FuiFlag>),
    Bahrain (<FuiFlag country=bahrain></FuiFlag>),
    Burundi (<FuiFlag country=burundi></FuiFlag>),
    Benin (<FuiFlag country=benin></FuiFlag>),
    Bermuda (<FuiFlag country=bermuda></FuiFlag>),
    Brunei (<FuiFlag country=brunei></FuiFlag>),
    Bolivia (<FuiFlag country=bolivia></FuiFlag>),
    Brazil (<FuiFlag country=brazil></FuiFlag>),
    Bahamas (<FuiFlag country=bahamas></FuiFlag>),
    Bhutan (<FuiFlag country=bhutan></FuiFlag>),
    Bouvet Island (<FuiFlag country="bouvet island"></FuiFlag>),
    Botswana (<FuiFlag country=botswana></FuiFlag>),
    Belarus (<FuiFlag country=belarus></FuiFlag>),
    Belize (<FuiFlag country=belize></FuiFlag>),
    Canada (<FuiFlag country=canada></FuiFlag>),
    Cocos Islands (<FuiFlag country="cocos islands"></FuiFlag>),
    Congo (<FuiFlag country=congo></FuiFlag>),
    Central African Republic (<FuiFlag country="central african republic"></FuiFlag>),
    Congo Brazzaville (<FuiFlag country="congo brazzaville"></FuiFlag>),
    Switzerland (<FuiFlag country=switzerland></FuiFlag>),
    Cote Divoire (<FuiFlag country="cote divoire"></FuiFlag>),
    Cook Islands (<FuiFlag country="cook islands"></FuiFlag>),
    Chile (<FuiFlag country=chile></FuiFlag>),
    Cameroon (<FuiFlag country=cameroon></FuiFlag>),
    China (<FuiFlag country=china></FuiFlag>),
    Colombia (<FuiFlag country=colombia></FuiFlag>),
    Costa Rica (<FuiFlag country="costa rica"></FuiFlag>),
    Serbia (<FuiFlag country=serbia></FuiFlag>),
    Cuba (<FuiFlag country=cuba></FuiFlag>),
    Cape Verde (<FuiFlag country="cape verde"></FuiFlag>),
    Christmas Island (<FuiFlag country="christmas island"></FuiFlag>),
    Cyprus (<FuiFlag country=cyprus></FuiFlag>),
    Czech Republic (<FuiFlag country="czech republic"></FuiFlag>),
    Germany (<FuiFlag country=germany></FuiFlag>),
    Djibouti (<FuiFlag country=djibouti></FuiFlag>),
    Denmark (<FuiFlag country=denmark></FuiFlag>),
    Dominica (<FuiFlag country=dominica></FuiFlag>),
    Dominican Republic (<FuiFlag country="dominican republic"></FuiFlag>),
    Algeria (<FuiFlag country=algeria></FuiFlag>),
    Ecuador (<FuiFlag country=ecuador></FuiFlag>),
    Estonia (<FuiFlag country=estonia></FuiFlag>),
    Egypt (<FuiFlag country=egypt></FuiFlag>),
    Western Sahara (<FuiFlag country="western sahara"></FuiFlag>),
    Eritrea (<FuiFlag country=eritrea></FuiFlag>),
    Spain (<FuiFlag country=spain></FuiFlag>),
    Ethiopia (<FuiFlag country=ethiopia></FuiFlag>),
    European Union (<FuiFlag country="european union"></FuiFlag>),
    Finland (<FuiFlag country=finland></FuiFlag>),
    Fiji (<FuiFlag country=fiji></FuiFlag>),
    Falkland Islands (<FuiFlag country="falkland islands"></FuiFlag>),
    Micronesia (<FuiFlag country=micronesia></FuiFlag>),
    Faroe Islands (<FuiFlag country="faroe islands"></FuiFlag>),
    France (<FuiFlag country=france></FuiFlag>),
    Gabon (<FuiFlag country=gabon></FuiFlag>),
    United Kingdom (<FuiFlag country="united kingdom"></FuiFlag>),
    England (<FuiFlag country=england></FuiFlag>),
    Scotland (<FuiFlag country=scotland></FuiFlag>),
    Wales (<FuiFlag country=wales></FuiFlag>),
    Grenada (<FuiFlag country=grenada></FuiFlag>),
    Georgia (<FuiFlag country=georgia></FuiFlag>),
    French Guiana (<FuiFlag country="french guiana"></FuiFlag>),
    Ghana (<FuiFlag country=ghana></FuiFlag>),
    Gibraltar (<FuiFlag country=gibraltar></FuiFlag>),
    Greenland (<FuiFlag country=greenland></FuiFlag>),
    Gambia (<FuiFlag country=gambia></FuiFlag>),
    Guinea (<FuiFlag country=guinea></FuiFlag>),
    Guadeloupe (<FuiFlag country=guadeloupe></FuiFlag>),
    Equatorial Guinea (<FuiFlag country="equatorial guinea"></FuiFlag>),
    Greece (<FuiFlag country=greece></FuiFlag>),
    Sandwich Islands (<FuiFlag country="sandwich islands"></FuiFlag>),
    Guatemala (<FuiFlag country=guatemala></FuiFlag>),
    Guam (<FuiFlag country=guam></FuiFlag>),
    Guinea-bissau (<FuiFlag country=guinea-bissau></FuiFlag>),
    Guyana (<FuiFlag country=guyana></FuiFlag>),
    Hong Kong (<FuiFlag country="hong kong"></FuiFlag>),
    Heard Island (<FuiFlag country="heard island"></FuiFlag>),
    Honduras (<FuiFlag country=honduras></FuiFlag>),
    Croatia (<FuiFlag country=croatia></FuiFlag>),
    Haiti (<FuiFlag country=haiti></FuiFlag>),
    Hungary (<FuiFlag country=hungary></FuiFlag>),
    Indonesia (<FuiFlag country=indonesia></FuiFlag>),
    Ireland (<FuiFlag country=ireland></FuiFlag>),
    Israel (<FuiFlag country=israel></FuiFlag>),
    India (<FuiFlag country=india></FuiFlag>),
    Indian Ocean Territory (<FuiFlag country="indian ocean territory"></FuiFlag>),
    Iraq (<FuiFlag country=iraq></FuiFlag>),
    Iran (<FuiFlag country=iran></FuiFlag>),
    Iceland (<FuiFlag country=iceland></FuiFlag>),
    Italy (<FuiFlag country=italy></FuiFlag>),
    Jamaica (<FuiFlag country=jamaica></FuiFlag>),
    Jordan (<FuiFlag country=jordan></FuiFlag>),
    Japan (<FuiFlag country=japan></FuiFlag>),
    Kenya (<FuiFlag country=kenya></FuiFlag>),
    Kyrgyzstan (<FuiFlag country=kyrgyzstan></FuiFlag>),
    Cambodia (<FuiFlag country=cambodia></FuiFlag>),
    Kiribati (<FuiFlag country=kiribati></FuiFlag>),
    Comoros (<FuiFlag country=comoros></FuiFlag>),
    Saint Kitts And Nevis (<FuiFlag country="saint kitts and nevis"></FuiFlag>),
    North Korea (<FuiFlag country="north korea"></FuiFlag>),
    South Korea (<FuiFlag country="south korea"></FuiFlag>),
    Kuwait (<FuiFlag country=kuwait></FuiFlag>),
    Cayman Islands (<FuiFlag country="cayman islands"></FuiFlag>),
    Kazakhstan (<FuiFlag country=kazakhstan></FuiFlag>),
    Laos (<FuiFlag country=laos></FuiFlag>),
    Lebanon (<FuiFlag country=lebanon></FuiFlag>),
    Saint Lucia (<FuiFlag country="saint lucia"></FuiFlag>),
    Liechtenstein (<FuiFlag country=liechtenstein></FuiFlag>),
    Sri Lanka (<FuiFlag country="sri lanka"></FuiFlag>),
    Liberia (<FuiFlag country=liberia></FuiFlag>),
    Lesotho (<FuiFlag country=lesotho></FuiFlag>),
    Lithuania (<FuiFlag country=lithuania></FuiFlag>),
    Luxembourg (<FuiFlag country=luxembourg></FuiFlag>),
    Latvia (<FuiFlag country=latvia></FuiFlag>),
    Libya (<FuiFlag country=libya></FuiFlag>),
    Morocco (<FuiFlag country=morocco></FuiFlag>),
    Monaco (<FuiFlag country=monaco></FuiFlag>),
    Moldova (<FuiFlag country=moldova></FuiFlag>),
    Montenegro (<FuiFlag country=montenegro></FuiFlag>),
    Madagascar (<FuiFlag country=madagascar></FuiFlag>),
    Marshall Islands (<FuiFlag country="marshall islands"></FuiFlag>),
    Macedonia (<FuiFlag country=macedonia></FuiFlag>),
    Mali (<FuiFlag country=mali></FuiFlag>),
    Burma (<FuiFlag country=burma></FuiFlag>),
    Mongolia (<FuiFlag country=mongolia></FuiFlag>),
    Macau (<FuiFlag country=macau></FuiFlag>),
    Northern Mariana Islands (<FuiFlag country="northern mariana islands"></FuiFlag>),
    Martinique (<FuiFlag country=martinique></FuiFlag>),
    Mauritania (<FuiFlag country=mauritania></FuiFlag>),
    Montserrat (<FuiFlag country=montserrat></FuiFlag>),
    Malta (<FuiFlag country=malta></FuiFlag>),
    Mauritius (<FuiFlag country=mauritius></FuiFlag>),
    Maldives (<FuiFlag country=maldives></FuiFlag>),
    Malawi (<FuiFlag country=malawi></FuiFlag>),
    Mexico (<FuiFlag country=mexico></FuiFlag>),
    Malaysia (<FuiFlag country=malaysia></FuiFlag>),
    Mozambique (<FuiFlag country=mozambique></FuiFlag>),
    Namibia (<FuiFlag country=namibia></FuiFlag>),
    New Caledonia (<FuiFlag country="new caledonia"></FuiFlag>),
    Niger (<FuiFlag country=niger></FuiFlag>),
    Norfolk Island (<FuiFlag country="norfolk island"></FuiFlag>),
    Nigeria (<FuiFlag country=nigeria></FuiFlag>),
    Nicaragua (<FuiFlag country=nicaragua></FuiFlag>),
    Netherlands (<FuiFlag country=netherlands></FuiFlag>),
    Norway (<FuiFlag country=norway></FuiFlag>),
    Nepal (<FuiFlag country=nepal></FuiFlag>),
    Nauru (<FuiFlag country=nauru></FuiFlag>),
    Niue (<FuiFlag country=niue></FuiFlag>),
    New Zealand (<FuiFlag country="new zealand"></FuiFlag>),
    Oman (<FuiFlag country=oman></FuiFlag>),
    Panama (<FuiFlag country=panama></FuiFlag>),
    Peru (<FuiFlag country=peru></FuiFlag>),
    French Polynesia (<FuiFlag country="french polynesia"></FuiFlag>),
    New Guinea (<FuiFlag country="new guinea"></FuiFlag>),
    Philippines (<FuiFlag country=philippines></FuiFlag>),
    Pakistan (<FuiFlag country=pakistan></FuiFlag>),
    Poland (<FuiFlag country=poland></FuiFlag>),
    Saint Pierre (<FuiFlag country="saint pierre"></FuiFlag>),
    Pitcairn Islands (<FuiFlag country="pitcairn islands"></FuiFlag>),
    Puerto Rico (<FuiFlag country="puerto rico"></FuiFlag>),
    Palestine (<FuiFlag country=palestine></FuiFlag>),
    Portugal (<FuiFlag country=portugal></FuiFlag>),
    Palau (<FuiFlag country=palau></FuiFlag>),
    Paraguay (<FuiFlag country=paraguay></FuiFlag>),
    Qatar (<FuiFlag country=qatar></FuiFlag>),
    Reunion (<FuiFlag country=reunion></FuiFlag>),
    Romania (<FuiFlag country=romania></FuiFlag>),
    Serbia (<FuiFlag country=serbia></FuiFlag>),
    Russia (<FuiFlag country=russia></FuiFlag>),
    Rwanda (<FuiFlag country=rwanda></FuiFlag>),
    Saudi Arabia (<FuiFlag country="saudi arabia"></FuiFlag>),
    Solomon Islands (<FuiFlag country="solomon islands"></FuiFlag>),
    Seychelles (<FuiFlag country=seychelles></FuiFlag>),
    Sudan (<FuiFlag country=sudan></FuiFlag>),
    Sweden (<FuiFlag country=sweden></FuiFlag>),
    Singapore (<FuiFlag country=singapore></FuiFlag>),
    Saint Helena (<FuiFlag country="saint helena"></FuiFlag>),
    Slovenia (<FuiFlag country=slovenia></FuiFlag>),
    Jan Mayen (<FuiFlag country="jan mayen"></FuiFlag>),
    Slovakia (<FuiFlag country=slovakia></FuiFlag>),
    Sierra Leone (<FuiFlag country="sierra leone"></FuiFlag>),
    San Marino (<FuiFlag country="san marino"></FuiFlag>),
    Senegal (<FuiFlag country=senegal></FuiFlag>),
    Somalia (<FuiFlag country=somalia></FuiFlag>),
    Suriname (<FuiFlag country=suriname></FuiFlag>),
    Sao Tome (<FuiFlag country="sao tome"></FuiFlag>),
    El Salvador (<FuiFlag country="el salvador"></FuiFlag>),
    Syria (<FuiFlag country=syria></FuiFlag>),
    Swaziland (<FuiFlag country=swaziland></FuiFlag>),
    Caicos Islands (<FuiFlag country="caicos islands"></FuiFlag>),
    Chad (<FuiFlag country=chad></FuiFlag>),
    French Territories (<FuiFlag country="french territories"></FuiFlag>),
    Togo (<FuiFlag country=togo></FuiFlag>),
    Thailand (<FuiFlag country=thailand></FuiFlag>),
    Tajikistan (<FuiFlag country=tajikistan></FuiFlag>),
    Tokelau (<FuiFlag country=tokelau></FuiFlag>),
    Timorleste (<FuiFlag country=timorleste></FuiFlag>),
    Turkmenistan (<FuiFlag country=turkmenistan></FuiFlag>),
    Tunisia (<FuiFlag country=tunisia></FuiFlag>),
    Tonga (<FuiFlag country=tonga></FuiFlag>),
    Turkey (<FuiFlag country=turkey></FuiFlag>),
    Trinidad (<FuiFlag country=trinidad></FuiFlag>),
    Tuvalu (<FuiFlag country=tuvalu></FuiFlag>),
    Taiwan (<FuiFlag country=taiwan></FuiFlag>),
    Tanzania (<FuiFlag country=tanzania></FuiFlag>),
    Ukraine (<FuiFlag country=ukraine></FuiFlag>),
    Uganda (<FuiFlag country=uganda></FuiFlag>),
    Us Minor Islands (<FuiFlag country="us minor islands"></FuiFlag>),
    United States (<FuiFlag country="united states"></FuiFlag>),
    Uruguay (<FuiFlag country=uruguay></FuiFlag>),
    Uzbekistan (<FuiFlag country=uzbekistan></FuiFlag>),
    Vatican City (<FuiFlag country="vatican city"></FuiFlag>),
    Saint Vincent (<FuiFlag country="saint vincent"></FuiFlag>),
    Venezuela (<FuiFlag country=venezuela></FuiFlag>),
    British Virgin Islands (<FuiFlag country="british virgin islands"></FuiFlag>),
    Us Virgin Islands (<FuiFlag country="us virgin islands"></FuiFlag>),
    Vietnam (<FuiFlag country=vietnam></FuiFlag>),
    Vanuatu (<FuiFlag country=vanuatu></FuiFlag>),
    Wallis And Futuna (<FuiFlag country="wallis and futuna"></FuiFlag>),
    Samoa (<FuiFlag country=samoa></FuiFlag>),
    Yemen (<FuiFlag country=yemen></FuiFlag>),
    Mayotte (<FuiFlag country=mayotte></FuiFlag>),
    South Africa (<FuiFlag country="south africa"></FuiFlag>),
    Zambia (<FuiFlag country=zambia></FuiFlag>),
    Zimbabwe (<FuiFlag country=zimbabwe></FuiFlag>),
  </div>
</template>

<script>
export default {
  name: 'ElementFlag1',
  info: {
    converted: true,
    elementType: 'elements',
    element: 'flag',
    title1: '???',
    title2: '???',
    description: '???',
    model: 'Andorra (<i class="andorra flag"></i>),\n ' +
      'U.A.E (<i class="uae flag"></i>),\n ' +
      'Afghanistan (<i class="afghanistan flag"></i>),\n ' +
      'Antigua (<i class="antigua flag"></i>),\n ' +
      'Anguilla (<i class="anguilla flag"></i>),\n ' +
      'Albania (<i class="albania flag"></i>),\n ' +
      'Armenia (<i class="armenia flag"></i>),\n ' +
      'Netherlands Antilles (<i class="netherlands antilles flag"></i>),\n ' +
      'Angola (<i class="angola flag"></i>),\n ' +
      'Argentina (<i class="argentina flag"></i>),\n ' +
      'American Samoa (<i class="american samoa flag"></i>),\n ' +
      'Austria (<i class="austria flag"></i>),\n ' +
      'Australia (<i class="australia flag"></i>),\n ' +
      'Aruba (<i class="aruba flag"></i>),\n ' +
      'Aland Islands (<i class="aland islands flag"></i>),\n ' +
      'Azerbaijan (<i class="azerbaijan flag"></i>),\n ' +
      'Bosnia (<i class="bosnia flag"></i>),\n ' +
      'Barbados (<i class="barbados flag"></i>),\n ' +
      'Bangladesh (<i class="bangladesh flag"></i>),\n ' +
      'Belgium (<i class="belgium flag"></i>),\n ' +
      'Burkina Faso (<i class="burkina faso flag"></i>),\n ' +
      'Bulgaria (<i class="bulgaria flag"></i>),\n ' +
      'Bahrain (<i class="bahrain flag"></i>),\n ' +
      'Burundi (<i class="burundi flag"></i>),\n ' +
      'Benin (<i class="benin flag"></i>),\n ' +
      'Bermuda (<i class="bermuda flag"></i>),\n ' +
      'Brunei (<i class="brunei flag"></i>),\n ' +
      'Bolivia (<i class="bolivia flag"></i>),\n ' +
      'Brazil (<i class="brazil flag"></i>),\n ' +
      'Bahamas (<i class="bahamas flag"></i>),\n ' +
      'Bhutan (<i class="bhutan flag"></i>),\n ' +
      'Bouvet Island (<i class="bouvet island flag"></i>),\n ' +
      'Botswana (<i class="botswana flag"></i>),\n ' +
      'Belarus (<i class="belarus flag"></i>),\n ' +
      'Belize (<i class="belize flag"></i>),\n ' +
      'Canada (<i class="canada flag"></i>),\n ' +
      'Cocos Islands (<i class="cocos islands flag"></i>),\n ' +
      'Congo (<i class="congo flag"></i>),\n ' +
      'Central African Republic (<i class="central african republic flag"></i>),\n ' +
      'Congo Brazzaville (<i class="congo brazzaville flag"></i>),\n ' +
      'Switzerland (<i class="switzerland flag"></i>),\n ' +
      'Cote Divoire (<i class="cote divoire flag"></i>),\n ' +
      'Cook Islands (<i class="cook islands flag"></i>),\n ' +
      'Chile (<i class="chile flag"></i>),\n ' +
      'Cameroon (<i class="cameroon flag"></i>),\n ' +
      'China (<i class="china flag"></i>),\n ' +
      'Colombia (<i class="colombia flag"></i>),\n ' +
      'Costa Rica (<i class="costa rica flag"></i>),\n ' +
      'Serbia (<i class="serbia flag"></i>),\n ' +
      'Cuba (<i class="cuba flag"></i>),\n ' +
      'Cape Verde (<i class="cape verde flag"></i>),\n ' +
      'Christmas Island (<i class="christmas island flag"></i>),\n ' +
      'Cyprus (<i class="cyprus flag"></i>),\n ' +
      'Czech Republic (<i class="czech republic flag"></i>),\n ' +
      'Germany (<i class="germany flag"></i>),\n ' +
      'Djibouti (<i class="djibouti flag"></i>),\n ' +
      'Denmark (<i class="denmark flag"></i>),\n ' +
      'Dominica (<i class="dominica flag"></i>),\n ' +
      'Dominican Republic (<i class="dominican republic flag"></i>),\n ' +
      'Algeria (<i class="algeria flag"></i>),\n ' +
      'Ecuador (<i class="ecuador flag"></i>),\n ' +
      'Estonia (<i class="estonia flag"></i>),\n ' +
      'Egypt (<i class="egypt flag"></i>),\n ' +
      'Western Sahara (<i class="western sahara flag"></i>),\n ' +
      'Eritrea (<i class="eritrea flag"></i>),\n ' +
      'Spain (<i class="spain flag"></i>),\n ' +
      'Ethiopia (<i class="ethiopia flag"></i>),\n ' +
      'European Union (<i class="european union flag"></i>),\n ' +
      'Finland (<i class="finland flag"></i>),\n ' +
      'Fiji (<i class="fiji flag"></i>),\n ' +
      'Falkland Islands (<i class="falkland islands flag"></i>),\n ' +
      'Micronesia (<i class="micronesia flag"></i>),\n ' +
      'Faroe Islands (<i class="faroe islands flag"></i>),\n ' +
      'France (<i class="france flag"></i>),\n ' +
      'Gabon (<i class="gabon flag"></i>),\n ' +
      'United Kingdom (<i class="united kingdom flag"></i>),\n ' +
      'England (<i class="england flag"></i>),\n ' +
      'Scotland (<i class="scotland flag"></i>),\n ' +
      'Wales (<i class="wales flag"></i>),\n ' +
      'Grenada (<i class="grenada flag"></i>),\n ' +
      'Georgia (<i class="georgia flag"></i>),\n ' +
      'French Guiana (<i class="french guiana flag"></i>),\n ' +
      'Ghana (<i class="ghana flag"></i>),\n ' +
      'Gibraltar (<i class="gibraltar flag"></i>),\n ' +
      'Greenland (<i class="greenland flag"></i>),\n ' +
      'Gambia (<i class="gambia flag"></i>),\n ' +
      'Guinea (<i class="guinea flag"></i>),\n ' +
      'Guadeloupe (<i class="guadeloupe flag"></i>),\n ' +
      'Equatorial Guinea (<i class="equatorial guinea flag"></i>),\n ' +
      'Greece (<i class="greece flag"></i>),\n ' +
      'Sandwich Islands (<i class="sandwich islands flag"></i>),\n ' +
      'Guatemala (<i class="guatemala flag"></i>),\n ' +
      'Guam (<i class="guam flag"></i>),\n ' +
      'Guinea-bissau (<i class="guinea-bissau flag"></i>),\n ' +
      'Guyana (<i class="guyana flag"></i>),\n ' +
      'Hong Kong (<i class="hong kong flag"></i>),\n ' +
      'Heard Island (<i class="heard island flag"></i>),\n ' +
      'Honduras (<i class="honduras flag"></i>),\n ' +
      'Croatia (<i class="croatia flag"></i>),\n ' +
      'Haiti (<i class="haiti flag"></i>),\n ' +
      'Hungary (<i class="hungary flag"></i>),\n ' +
      'Indonesia (<i class="indonesia flag"></i>),\n ' +
      'Ireland (<i class="ireland flag"></i>),\n ' +
      'Israel (<i class="israel flag"></i>),\n ' +
      'India (<i class="india flag"></i>),\n ' +
      'Indian Ocean Territory (<i class="indian ocean territory flag"></i>),\n ' +
      'Iraq (<i class="iraq flag"></i>),\n ' +
      'Iran (<i class="iran flag"></i>),\n ' +
      'Iceland (<i class="iceland flag"></i>),\n ' +
      'Italy (<i class="italy flag"></i>),\n ' +
      'Jamaica (<i class="jamaica flag"></i>),\n ' +
      'Jordan (<i class="jordan flag"></i>),\n ' +
      'Japan (<i class="japan flag"></i>),\n ' +
      'Kenya (<i class="kenya flag"></i>),\n ' +
      'Kyrgyzstan (<i class="kyrgyzstan flag"></i>),\n ' +
      'Cambodia (<i class="cambodia flag"></i>),\n ' +
      'Kiribati (<i class="kiribati flag"></i>),\n ' +
      'Comoros (<i class="comoros flag"></i>),\n ' +
      'Saint Kitts And Nevis (<i class="saint kitts and nevis flag"></i>),\n ' +
      'North Korea (<i class="north korea flag"></i>),\n ' +
      'South Korea (<i class="south korea flag"></i>),\n ' +
      'Kuwait (<i class="kuwait flag"></i>),\n ' +
      'Cayman Islands (<i class="cayman islands flag"></i>),\n ' +
      'Kazakhstan (<i class="kazakhstan flag"></i>),\n ' +
      'Laos (<i class="laos flag"></i>),\n ' +
      'Lebanon (<i class="lebanon flag"></i>),\n ' +
      'Saint Lucia (<i class="saint lucia flag"></i>),\n ' +
      'Liechtenstein (<i class="liechtenstein flag"></i>),\n ' +
      'Sri Lanka (<i class="sri lanka flag"></i>),\n ' +
      'Liberia (<i class="liberia flag"></i>),\n ' +
      'Lesotho (<i class="lesotho flag"></i>),\n ' +
      'Lithuania (<i class="lithuania flag"></i>),\n ' +
      'Luxembourg (<i class="luxembourg flag"></i>),\n ' +
      'Latvia (<i class="latvia flag"></i>),\n ' +
      'Libya (<i class="libya flag"></i>),\n ' +
      'Morocco (<i class="morocco flag"></i>),\n ' +
      'Monaco (<i class="monaco flag"></i>),\n ' +
      'Moldova (<i class="moldova flag"></i>),\n ' +
      'Montenegro (<i class="montenegro flag"></i>),\n ' +
      'Madagascar (<i class="madagascar flag"></i>),\n ' +
      'Marshall Islands (<i class="marshall islands flag"></i>),\n ' +
      'Macedonia (<i class="macedonia flag"></i>),\n ' +
      'Mali (<i class="mali flag"></i>),\n ' +
      'Burma (<i class="burma flag"></i>),\n ' +
      'Mongolia (<i class="mongolia flag"></i>),\n ' +
      'Macau (<i class="macau flag"></i>),\n ' +
      'Northern Mariana Islands (<i class="northern mariana islands flag"></i>),\n ' +
      'Martinique (<i class="martinique flag"></i>),\n ' +
      'Mauritania (<i class="mauritania flag"></i>),\n ' +
      'Montserrat (<i class="montserrat flag"></i>),\n ' +
      'Malta (<i class="malta flag"></i>),\n ' +
      'Mauritius (<i class="mauritius flag"></i>),\n ' +
      'Maldives (<i class="maldives flag"></i>),\n ' +
      'Malawi (<i class="malawi flag"></i>),\n ' +
      'Mexico (<i class="mexico flag"></i>),\n ' +
      'Malaysia (<i class="malaysia flag"></i>),\n ' +
      'Mozambique (<i class="mozambique flag"></i>),\n ' +
      'Namibia (<i class="namibia flag"></i>),\n ' +
      'New Caledonia (<i class="new caledonia flag"></i>),\n ' +
      'Niger (<i class="niger flag"></i>),\n ' +
      'Norfolk Island (<i class="norfolk island flag"></i>),\n ' +
      'Nigeria (<i class="nigeria flag"></i>),\n ' +
      'Nicaragua (<i class="nicaragua flag"></i>),\n ' +
      'Netherlands (<i class="netherlands flag"></i>),\n ' +
      'Norway (<i class="norway flag"></i>),\n ' +
      'Nepal (<i class="nepal flag"></i>),\n ' +
      'Nauru (<i class="nauru flag"></i>),\n ' +
      'Niue (<i class="niue flag"></i>),\n ' +
      'New Zealand (<i class="new zealand flag"></i>),\n ' +
      'Oman (<i class="oman flag"></i>),\n ' +
      'Panama (<i class="panama flag"></i>),\n ' +
      'Peru (<i class="peru flag"></i>),\n ' +
      'French Polynesia (<i class="french polynesia flag"></i>),\n ' +
      'New Guinea (<i class="new guinea flag"></i>),\n ' +
      'Philippines (<i class="philippines flag"></i>),\n ' +
      'Pakistan (<i class="pakistan flag"></i>),\n ' +
      'Poland (<i class="poland flag"></i>),\n ' +
      'Saint Pierre (<i class="saint pierre flag"></i>),\n ' +
      'Pitcairn Islands (<i class="pitcairn islands flag"></i>),\n ' +
      'Puerto Rico (<i class="puerto rico flag"></i>),\n ' +
      'Palestine (<i class="palestine flag"></i>),\n ' +
      'Portugal (<i class="portugal flag"></i>),\n ' +
      'Palau (<i class="palau flag"></i>),\n ' +
      'Paraguay (<i class="paraguay flag"></i>),\n ' +
      'Qatar (<i class="qatar flag"></i>),\n ' +
      'Reunion (<i class="reunion flag"></i>),\n ' +
      'Romania (<i class="romania flag"></i>),\n ' +
      'Serbia (<i class="serbia flag"></i>),\n ' +
      'Russia (<i class="russia flag"></i>),\n ' +
      'Rwanda (<i class="rwanda flag"></i>),\n ' +
      'Saudi Arabia (<i class="saudi arabia flag"></i>),\n ' +
      'Solomon Islands (<i class="solomon islands flag"></i>),\n ' +
      'Seychelles (<i class="seychelles flag"></i>),\n ' +
      'Sudan (<i class="sudan flag"></i>),\n ' +
      'Sweden (<i class="sweden flag"></i>),\n ' +
      'Singapore (<i class="singapore flag"></i>),\n ' +
      'Saint Helena (<i class="saint helena flag"></i>),\n ' +
      'Slovenia (<i class="slovenia flag"></i>),\n ' +
      'Jan Mayen (<i class="jan mayen flag"></i>),\n ' +
      'Slovakia (<i class="slovakia flag"></i>),\n ' +
      'Sierra Leone (<i class="sierra leone flag"></i>),\n ' +
      'San Marino (<i class="san marino flag"></i>),\n ' +
      'Senegal (<i class="senegal flag"></i>),\n ' +
      'Somalia (<i class="somalia flag"></i>),\n ' +
      'Suriname (<i class="suriname flag"></i>),\n ' +
      'Sao Tome (<i class="sao tome flag"></i>),\n ' +
      'El Salvador (<i class="el salvador flag"></i>),\n ' +
      'Syria (<i class="syria flag"></i>),\n ' +
      'Swaziland (<i class="swaziland flag"></i>),\n ' +
      'Caicos Islands (<i class="caicos islands flag"></i>),\n ' +
      'Chad (<i class="chad flag"></i>),\n ' +
      'French Territories (<i class="french territories flag"></i>),\n ' +
      'Togo (<i class="togo flag"></i>),\n ' +
      'Thailand (<i class="thailand flag"></i>),\n ' +
      'Tajikistan (<i class="tajikistan flag"></i>),\n ' +
      'Tokelau (<i class="tokelau flag"></i>),\n ' +
      'Timorleste (<i class="timorleste flag"></i>),\n ' +
      'Turkmenistan (<i class="turkmenistan flag"></i>),\n ' +
      'Tunisia (<i class="tunisia flag"></i>),\n ' +
      'Tonga (<i class="tonga flag"></i>),\n ' +
      'Turkey (<i class="turkey flag"></i>),\n ' +
      'Trinidad (<i class="trinidad flag"></i>),\n ' +
      'Tuvalu (<i class="tuvalu flag"></i>),\n ' +
      'Taiwan (<i class="taiwan flag"></i>),\n ' +
      'Tanzania (<i class="tanzania flag"></i>),\n ' +
      'Ukraine (<i class="ukraine flag"></i>),\n ' +
      'Uganda (<i class="uganda flag"></i>),\n ' +
      'Us Minor Islands (<i class="us minor islands flag"></i>),\n ' +
      'United States (<i class="united states flag"></i>),\n ' +
      'Uruguay (<i class="uruguay flag"></i>),\n ' +
      'Uzbekistan (<i class="uzbekistan flag"></i>),\n ' +
      'Vatican City (<i class="vatican city flag"></i>),\n ' +
      'Saint Vincent (<i class="saint vincent flag"></i>),\n ' +
      'Venezuela (<i class="venezuela flag"></i>),\n ' +
      'British Virgin Islands (<i class="british virgin islands flag"></i>),\n ' +
      'Us Virgin Islands (<i class="us virgin islands flag"></i>),\n ' +
      'Vietnam (<i class="vietnam flag"></i>),\n ' +
      'Vanuatu (<i class="vanuatu flag"></i>),\n ' +
      'Wallis And Futuna (<i class="wallis and futuna flag"></i>),\n ' +
      'Samoa (<i class="samoa flag"></i>),\n ' +
      'Yemen (<i class="yemen flag"></i>),\n ' +
      'Mayotte (<i class="mayotte flag"></i>),\n ' +
      'South Africa (<i class="south africa flag"></i>),\n ' +
      'Zambia (<i class="zambia flag"></i>),\n ' +
      'Zimbabwe (<i class="zimbabwe flag"></i>),\n ',
  },
};
</script>
